// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: jwt/claims.proto

package authapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Claims represents JWT claims for encoding
type Claims struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subject (JWT "sub") - the principal_id this credential represents
	Sub string `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	// Audience (JWT "aud") - the intended recipient/resource server(s)
	Aud []string `protobuf:"bytes,2,rep,name=aud,proto3" json:"aud,omitempty"`
	// Issuer (JWT "iss") - who issued this token
	Iss string `protobuf:"bytes,3,opt,name=iss,proto3" json:"iss,omitempty"`
	// Expiration time (JWT "exp") - Unix timestamp (0 = never expires)
	Exp int64 `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	// Issued at (JWT "iat") - Unix timestamp
	Iat int64 `protobuf:"varint,5,opt,name=iat,proto3" json:"iat,omitempty"`
	// Not before (JWT "nbf") - Unix timestamp
	Nbf int64 `protobuf:"varint,6,opt,name=nbf,proto3" json:"nbf,omitempty"`
	// JWT ID (JWT "jti") - unique identifier for this credential
	Jti           string `protobuf:"bytes,7,opt,name=jti,proto3" json:"jti,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Claims) Reset() {
	*x = Claims{}
	mi := &file_jwt_claims_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claims) ProtoMessage() {}

func (x *Claims) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_claims_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claims.ProtoReflect.Descriptor instead.
func (*Claims) Descriptor() ([]byte, []int) {
	return file_jwt_claims_proto_rawDescGZIP(), []int{0}
}

func (x *Claims) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *Claims) GetAud() []string {
	if x != nil {
		return x.Aud
	}
	return nil
}

func (x *Claims) GetIss() string {
	if x != nil {
		return x.Iss
	}
	return ""
}

func (x *Claims) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *Claims) GetIat() int64 {
	if x != nil {
		return x.Iat
	}
	return 0
}

func (x *Claims) GetNbf() int64 {
	if x != nil {
		return x.Nbf
	}
	return 0
}

func (x *Claims) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

var File_jwt_claims_proto protoreflect.FileDescriptor

const file_jwt_claims_proto_rawDesc = "" +
	"\n" +
	"\x10jwt/claims.proto\x12\x03jwt\"\x86\x01\n" +
	"\x06Claims\x12\x10\n" +
	"\x03sub\x18\x01 \x01(\tR\x03sub\x12\x10\n" +
	"\x03aud\x18\x02 \x03(\tR\x03aud\x12\x10\n" +
	"\x03iss\x18\x03 \x01(\tR\x03iss\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\x03R\x03exp\x12\x10\n" +
	"\x03iat\x18\x05 \x01(\x03R\x03iat\x12\x10\n" +
	"\x03nbf\x18\x06 \x01(\x03R\x03nbf\x12\x10\n" +
	"\x03jti\x18\a \x01(\tR\x03jtiB2Z0git.sonicoriginal.software/grpc-auth-api;authapib\x06proto3"

var (
	file_jwt_claims_proto_rawDescOnce sync.Once
	file_jwt_claims_proto_rawDescData []byte
)

func file_jwt_claims_proto_rawDescGZIP() []byte {
	file_jwt_claims_proto_rawDescOnce.Do(func() {
		file_jwt_claims_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jwt_claims_proto_rawDesc), len(file_jwt_claims_proto_rawDesc)))
	})
	return file_jwt_claims_proto_rawDescData
}

var file_jwt_claims_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_jwt_claims_proto_goTypes = []any{
	(*Claims)(nil), // 0: jwt.Claims
}
var file_jwt_claims_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jwt_claims_proto_init() }
func file_jwt_claims_proto_init() {
	if File_jwt_claims_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jwt_claims_proto_rawDesc), len(file_jwt_claims_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jwt_claims_proto_goTypes,
		DependencyIndexes: file_jwt_claims_proto_depIdxs,
		MessageInfos:      file_jwt_claims_proto_msgTypes,
	}.Build()
	File_jwt_claims_proto = out.File
	file_jwt_claims_proto_goTypes = nil
	file_jwt_claims_proto_depIdxs = nil
}
