// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: membership/membership_service.proto

package authapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Add member to group
type AddMemberRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GroupPrincipalId  *Principal             `protobuf:"bytes,1,opt,name=group_principal_id,json=groupPrincipalId,proto3" json:"group_principal_id,omitempty"`
	MemberPrincipalId *Principal             `protobuf:"bytes,2,opt,name=member_principal_id,json=memberPrincipalId,proto3" json:"member_principal_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_membership_membership_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_membership_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_membership_membership_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddMemberRequest) GetGroupPrincipalId() *Principal {
	if x != nil {
		return x.GroupPrincipalId
	}
	return nil
}

func (x *AddMemberRequest) GetMemberPrincipalId() *Principal {
	if x != nil {
		return x.MemberPrincipalId
	}
	return nil
}

type AddMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberResponse) Reset() {
	*x = AddMemberResponse{}
	mi := &file_membership_membership_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberResponse) ProtoMessage() {}

func (x *AddMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_membership_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberResponse.ProtoReflect.Descriptor instead.
func (*AddMemberResponse) Descriptor() ([]byte, []int) {
	return file_membership_membership_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddMemberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Remove member from group
type RemoveMemberRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GroupPrincipalId  *Principal             `protobuf:"bytes,1,opt,name=group_principal_id,json=groupPrincipalId,proto3" json:"group_principal_id,omitempty"`
	MemberPrincipalId *Principal             `protobuf:"bytes,2,opt,name=member_principal_id,json=memberPrincipalId,proto3" json:"member_principal_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_membership_membership_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_membership_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_membership_membership_service_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveMemberRequest) GetGroupPrincipalId() *Principal {
	if x != nil {
		return x.GroupPrincipalId
	}
	return nil
}

func (x *RemoveMemberRequest) GetMemberPrincipalId() *Principal {
	if x != nil {
		return x.MemberPrincipalId
	}
	return nil
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_membership_membership_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_membership_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_membership_membership_service_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveMemberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Get direct members of a group
type GetDirectMembersRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GroupPrincipalId *Principal             `protobuf:"bytes,1,opt,name=group_principal_id,json=groupPrincipalId,proto3" json:"group_principal_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetDirectMembersRequest) Reset() {
	*x = GetDirectMembersRequest{}
	mi := &file_membership_membership_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectMembersRequest) ProtoMessage() {}

func (x *GetDirectMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_membership_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectMembersRequest.ProtoReflect.Descriptor instead.
func (*GetDirectMembersRequest) Descriptor() ([]byte, []int) {
	return file_membership_membership_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetDirectMembersRequest) GetGroupPrincipalId() *Principal {
	if x != nil {
		return x.GroupPrincipalId
	}
	return nil
}

type GetDirectMembersResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MemberPrincipalIds []*Principal           `protobuf:"bytes,1,rep,name=member_principal_ids,json=memberPrincipalIds,proto3" json:"member_principal_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetDirectMembersResponse) Reset() {
	*x = GetDirectMembersResponse{}
	mi := &file_membership_membership_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectMembersResponse) ProtoMessage() {}

func (x *GetDirectMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_membership_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectMembersResponse.ProtoReflect.Descriptor instead.
func (*GetDirectMembersResponse) Descriptor() ([]byte, []int) {
	return file_membership_membership_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetDirectMembersResponse) GetMemberPrincipalIds() []*Principal {
	if x != nil {
		return x.MemberPrincipalIds
	}
	return nil
}

// Get all members of a group
type GetAllMembersRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GroupPrincipalId *Principal             `protobuf:"bytes,1,opt,name=group_principal_id,json=groupPrincipalId,proto3" json:"group_principal_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAllMembersRequest) Reset() {
	*x = GetAllMembersRequest{}
	mi := &file_membership_membership_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMembersRequest) ProtoMessage() {}

func (x *GetAllMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_membership_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMembersRequest.ProtoReflect.Descriptor instead.
func (*GetAllMembersRequest) Descriptor() ([]byte, []int) {
	return file_membership_membership_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllMembersRequest) GetGroupPrincipalId() *Principal {
	if x != nil {
		return x.GroupPrincipalId
	}
	return nil
}

type GetAllMembersResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MemberPrincipalIds []*Principal           `protobuf:"bytes,1,rep,name=member_principal_ids,json=memberPrincipalIds,proto3" json:"member_principal_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetAllMembersResponse) Reset() {
	*x = GetAllMembersResponse{}
	mi := &file_membership_membership_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMembersResponse) ProtoMessage() {}

func (x *GetAllMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_membership_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMembersResponse.ProtoReflect.Descriptor instead.
func (*GetAllMembersResponse) Descriptor() ([]byte, []int) {
	return file_membership_membership_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllMembersResponse) GetMemberPrincipalIds() []*Principal {
	if x != nil {
		return x.MemberPrincipalIds
	}
	return nil
}

// Get direct groups a principal belongs to
type GetDirectGroupsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MemberPrincipalId *Principal             `protobuf:"bytes,1,opt,name=member_principal_id,json=memberPrincipalId,proto3" json:"member_principal_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetDirectGroupsRequest) Reset() {
	*x = GetDirectGroupsRequest{}
	mi := &file_membership_membership_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectGroupsRequest) ProtoMessage() {}

func (x *GetDirectGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_membership_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetDirectGroupsRequest) Descriptor() ([]byte, []int) {
	return file_membership_membership_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetDirectGroupsRequest) GetMemberPrincipalId() *Principal {
	if x != nil {
		return x.MemberPrincipalId
	}
	return nil
}

type GetDirectGroupsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GroupPrincipalIds []*Principal           `protobuf:"bytes,1,rep,name=group_principal_ids,json=groupPrincipalIds,proto3" json:"group_principal_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetDirectGroupsResponse) Reset() {
	*x = GetDirectGroupsResponse{}
	mi := &file_membership_membership_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectGroupsResponse) ProtoMessage() {}

func (x *GetDirectGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_membership_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetDirectGroupsResponse) Descriptor() ([]byte, []int) {
	return file_membership_membership_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetDirectGroupsResponse) GetGroupPrincipalIds() []*Principal {
	if x != nil {
		return x.GroupPrincipalIds
	}
	return nil
}

// Get all groups a principal belongs to
type GetAllGroupsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MemberPrincipalId *Principal             `protobuf:"bytes,1,opt,name=member_principal_id,json=memberPrincipalId,proto3" json:"member_principal_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetAllGroupsRequest) Reset() {
	*x = GetAllGroupsRequest{}
	mi := &file_membership_membership_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllGroupsRequest) ProtoMessage() {}

func (x *GetAllGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_membership_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetAllGroupsRequest) Descriptor() ([]byte, []int) {
	return file_membership_membership_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllGroupsRequest) GetMemberPrincipalId() *Principal {
	if x != nil {
		return x.MemberPrincipalId
	}
	return nil
}

type GetAllGroupsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GroupPrincipalIds []*Principal           `protobuf:"bytes,1,rep,name=group_principal_ids,json=groupPrincipalIds,proto3" json:"group_principal_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetAllGroupsResponse) Reset() {
	*x = GetAllGroupsResponse{}
	mi := &file_membership_membership_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllGroupsResponse) ProtoMessage() {}

func (x *GetAllGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_membership_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetAllGroupsResponse) Descriptor() ([]byte, []int) {
	return file_membership_membership_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllGroupsResponse) GetGroupPrincipalIds() []*Principal {
	if x != nil {
		return x.GroupPrincipalIds
	}
	return nil
}

// Check if principal is member of group
type IsMemberRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GroupPrincipalId  *Principal             `protobuf:"bytes,1,opt,name=group_principal_id,json=groupPrincipalId,proto3" json:"group_principal_id,omitempty"`
	MemberPrincipalId *Principal             `protobuf:"bytes,2,opt,name=member_principal_id,json=memberPrincipalId,proto3" json:"member_principal_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IsMemberRequest) Reset() {
	*x = IsMemberRequest{}
	mi := &file_membership_membership_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberRequest) ProtoMessage() {}

func (x *IsMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_membership_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberRequest.ProtoReflect.Descriptor instead.
func (*IsMemberRequest) Descriptor() ([]byte, []int) {
	return file_membership_membership_service_proto_rawDescGZIP(), []int{12}
}

func (x *IsMemberRequest) GetGroupPrincipalId() *Principal {
	if x != nil {
		return x.GroupPrincipalId
	}
	return nil
}

func (x *IsMemberRequest) GetMemberPrincipalId() *Principal {
	if x != nil {
		return x.MemberPrincipalId
	}
	return nil
}

type IsMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMemberResponse) Reset() {
	*x = IsMemberResponse{}
	mi := &file_membership_membership_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberResponse) ProtoMessage() {}

func (x *IsMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_membership_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberResponse.ProtoReflect.Descriptor instead.
func (*IsMemberResponse) Descriptor() ([]byte, []int) {
	return file_membership_membership_service_proto_rawDescGZIP(), []int{13}
}

func (x *IsMemberResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

// List all groups
type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_membership_membership_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_membership_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_membership_membership_service_proto_rawDescGZIP(), []int{14}
}

type ListGroupsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GroupPrincipalIds []*Principal           `protobuf:"bytes,1,rep,name=group_principal_ids,json=groupPrincipalIds,proto3" json:"group_principal_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_membership_membership_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_membership_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_membership_membership_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListGroupsResponse) GetGroupPrincipalIds() []*Principal {
	if x != nil {
		return x.GroupPrincipalIds
	}
	return nil
}

var File_membership_membership_service_proto protoreflect.FileDescriptor

const file_membership_membership_service_proto_rawDesc = "" +
	"\n" +
	"#membership/membership_service.proto\x12\n" +
	"membership\x1a\x18identity/principal.proto\"\x9a\x01\n" +
	"\x10AddMemberRequest\x12A\n" +
	"\x12group_principal_id\x18\x01 \x01(\v2\x13.identity.PrincipalR\x10groupPrincipalId\x12C\n" +
	"\x13member_principal_id\x18\x02 \x01(\v2\x13.identity.PrincipalR\x11memberPrincipalId\"-\n" +
	"\x11AddMemberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9d\x01\n" +
	"\x13RemoveMemberRequest\x12A\n" +
	"\x12group_principal_id\x18\x01 \x01(\v2\x13.identity.PrincipalR\x10groupPrincipalId\x12C\n" +
	"\x13member_principal_id\x18\x02 \x01(\v2\x13.identity.PrincipalR\x11memberPrincipalId\"0\n" +
	"\x14RemoveMemberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\\\n" +
	"\x17GetDirectMembersRequest\x12A\n" +
	"\x12group_principal_id\x18\x01 \x01(\v2\x13.identity.PrincipalR\x10groupPrincipalId\"a\n" +
	"\x18GetDirectMembersResponse\x12E\n" +
	"\x14member_principal_ids\x18\x01 \x03(\v2\x13.identity.PrincipalR\x12memberPrincipalIds\"Y\n" +
	"\x14GetAllMembersRequest\x12A\n" +
	"\x12group_principal_id\x18\x01 \x01(\v2\x13.identity.PrincipalR\x10groupPrincipalId\"^\n" +
	"\x15GetAllMembersResponse\x12E\n" +
	"\x14member_principal_ids\x18\x01 \x03(\v2\x13.identity.PrincipalR\x12memberPrincipalIds\"]\n" +
	"\x16GetDirectGroupsRequest\x12C\n" +
	"\x13member_principal_id\x18\x01 \x01(\v2\x13.identity.PrincipalR\x11memberPrincipalId\"^\n" +
	"\x17GetDirectGroupsResponse\x12C\n" +
	"\x13group_principal_ids\x18\x01 \x03(\v2\x13.identity.PrincipalR\x11groupPrincipalIds\"Z\n" +
	"\x13GetAllGroupsRequest\x12C\n" +
	"\x13member_principal_id\x18\x01 \x01(\v2\x13.identity.PrincipalR\x11memberPrincipalId\"[\n" +
	"\x14GetAllGroupsResponse\x12C\n" +
	"\x13group_principal_ids\x18\x01 \x03(\v2\x13.identity.PrincipalR\x11groupPrincipalIds\"\x99\x01\n" +
	"\x0fIsMemberRequest\x12A\n" +
	"\x12group_principal_id\x18\x01 \x01(\v2\x13.identity.PrincipalR\x10groupPrincipalId\x12C\n" +
	"\x13member_principal_id\x18\x02 \x01(\v2\x13.identity.PrincipalR\x11memberPrincipalId\"/\n" +
	"\x10IsMemberResponse\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember\"\x13\n" +
	"\x11ListGroupsRequest\"Y\n" +
	"\x12ListGroupsResponse\x12C\n" +
	"\x13group_principal_ids\x18\x01 \x03(\v2\x13.identity.PrincipalR\x11groupPrincipalIds2\xa8\x05\n" +
	"\x11MembershipService\x12H\n" +
	"\tAddMember\x12\x1c.membership.AddMemberRequest\x1a\x1d.membership.AddMemberResponse\x12Q\n" +
	"\fRemoveMember\x12\x1f.membership.RemoveMemberRequest\x1a .membership.RemoveMemberResponse\x12]\n" +
	"\x10GetDirectMembers\x12#.membership.GetDirectMembersRequest\x1a$.membership.GetDirectMembersResponse\x12T\n" +
	"\rGetAllMembers\x12 .membership.GetAllMembersRequest\x1a!.membership.GetAllMembersResponse\x12Z\n" +
	"\x0fGetDirectGroups\x12\".membership.GetDirectGroupsRequest\x1a#.membership.GetDirectGroupsResponse\x12Q\n" +
	"\fGetAllGroups\x12\x1f.membership.GetAllGroupsRequest\x1a .membership.GetAllGroupsResponse\x12E\n" +
	"\bIsMember\x12\x1b.membership.IsMemberRequest\x1a\x1c.membership.IsMemberResponse\x12K\n" +
	"\n" +
	"ListGroups\x12\x1d.membership.ListGroupsRequest\x1a\x1e.membership.ListGroupsResponseB2Z0git.sonicoriginal.software/grpc-auth-api;authapib\x06proto3"

var (
	file_membership_membership_service_proto_rawDescOnce sync.Once
	file_membership_membership_service_proto_rawDescData []byte
)

func file_membership_membership_service_proto_rawDescGZIP() []byte {
	file_membership_membership_service_proto_rawDescOnce.Do(func() {
		file_membership_membership_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_membership_membership_service_proto_rawDesc), len(file_membership_membership_service_proto_rawDesc)))
	})
	return file_membership_membership_service_proto_rawDescData
}

var file_membership_membership_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_membership_membership_service_proto_goTypes = []any{
	(*AddMemberRequest)(nil),         // 0: membership.AddMemberRequest
	(*AddMemberResponse)(nil),        // 1: membership.AddMemberResponse
	(*RemoveMemberRequest)(nil),      // 2: membership.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),     // 3: membership.RemoveMemberResponse
	(*GetDirectMembersRequest)(nil),  // 4: membership.GetDirectMembersRequest
	(*GetDirectMembersResponse)(nil), // 5: membership.GetDirectMembersResponse
	(*GetAllMembersRequest)(nil),     // 6: membership.GetAllMembersRequest
	(*GetAllMembersResponse)(nil),    // 7: membership.GetAllMembersResponse
	(*GetDirectGroupsRequest)(nil),   // 8: membership.GetDirectGroupsRequest
	(*GetDirectGroupsResponse)(nil),  // 9: membership.GetDirectGroupsResponse
	(*GetAllGroupsRequest)(nil),      // 10: membership.GetAllGroupsRequest
	(*GetAllGroupsResponse)(nil),     // 11: membership.GetAllGroupsResponse
	(*IsMemberRequest)(nil),          // 12: membership.IsMemberRequest
	(*IsMemberResponse)(nil),         // 13: membership.IsMemberResponse
	(*ListGroupsRequest)(nil),        // 14: membership.ListGroupsRequest
	(*ListGroupsResponse)(nil),       // 15: membership.ListGroupsResponse
	(*Principal)(nil),                // 16: identity.Principal
}
var file_membership_membership_service_proto_depIdxs = []int32{
	16, // 0: membership.AddMemberRequest.group_principal_id:type_name -> identity.Principal
	16, // 1: membership.AddMemberRequest.member_principal_id:type_name -> identity.Principal
	16, // 2: membership.RemoveMemberRequest.group_principal_id:type_name -> identity.Principal
	16, // 3: membership.RemoveMemberRequest.member_principal_id:type_name -> identity.Principal
	16, // 4: membership.GetDirectMembersRequest.group_principal_id:type_name -> identity.Principal
	16, // 5: membership.GetDirectMembersResponse.member_principal_ids:type_name -> identity.Principal
	16, // 6: membership.GetAllMembersRequest.group_principal_id:type_name -> identity.Principal
	16, // 7: membership.GetAllMembersResponse.member_principal_ids:type_name -> identity.Principal
	16, // 8: membership.GetDirectGroupsRequest.member_principal_id:type_name -> identity.Principal
	16, // 9: membership.GetDirectGroupsResponse.group_principal_ids:type_name -> identity.Principal
	16, // 10: membership.GetAllGroupsRequest.member_principal_id:type_name -> identity.Principal
	16, // 11: membership.GetAllGroupsResponse.group_principal_ids:type_name -> identity.Principal
	16, // 12: membership.IsMemberRequest.group_principal_id:type_name -> identity.Principal
	16, // 13: membership.IsMemberRequest.member_principal_id:type_name -> identity.Principal
	16, // 14: membership.ListGroupsResponse.group_principal_ids:type_name -> identity.Principal
	0,  // 15: membership.MembershipService.AddMember:input_type -> membership.AddMemberRequest
	2,  // 16: membership.MembershipService.RemoveMember:input_type -> membership.RemoveMemberRequest
	4,  // 17: membership.MembershipService.GetDirectMembers:input_type -> membership.GetDirectMembersRequest
	6,  // 18: membership.MembershipService.GetAllMembers:input_type -> membership.GetAllMembersRequest
	8,  // 19: membership.MembershipService.GetDirectGroups:input_type -> membership.GetDirectGroupsRequest
	10, // 20: membership.MembershipService.GetAllGroups:input_type -> membership.GetAllGroupsRequest
	12, // 21: membership.MembershipService.IsMember:input_type -> membership.IsMemberRequest
	14, // 22: membership.MembershipService.ListGroups:input_type -> membership.ListGroupsRequest
	1,  // 23: membership.MembershipService.AddMember:output_type -> membership.AddMemberResponse
	3,  // 24: membership.MembershipService.RemoveMember:output_type -> membership.RemoveMemberResponse
	5,  // 25: membership.MembershipService.GetDirectMembers:output_type -> membership.GetDirectMembersResponse
	7,  // 26: membership.MembershipService.GetAllMembers:output_type -> membership.GetAllMembersResponse
	9,  // 27: membership.MembershipService.GetDirectGroups:output_type -> membership.GetDirectGroupsResponse
	11, // 28: membership.MembershipService.GetAllGroups:output_type -> membership.GetAllGroupsResponse
	13, // 29: membership.MembershipService.IsMember:output_type -> membership.IsMemberResponse
	15, // 30: membership.MembershipService.ListGroups:output_type -> membership.ListGroupsResponse
	23, // [23:31] is the sub-list for method output_type
	15, // [15:23] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_membership_membership_service_proto_init() }
func file_membership_membership_service_proto_init() {
	if File_membership_membership_service_proto != nil {
		return
	}
	file_identity_principal_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_membership_membership_service_proto_rawDesc), len(file_membership_membership_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_membership_membership_service_proto_goTypes,
		DependencyIndexes: file_membership_membership_service_proto_depIdxs,
		MessageInfos:      file_membership_membership_service_proto_msgTypes,
	}.Build()
	File_membership_membership_service_proto = out.File
	file_membership_membership_service_proto_goTypes = nil
	file_membership_membership_service_proto_depIdxs = nil
}
