// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: membership/membership_service.proto

package authapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MembershipService_AddMember_FullMethodName        = "/membership.MembershipService/AddMember"
	MembershipService_RemoveMember_FullMethodName     = "/membership.MembershipService/RemoveMember"
	MembershipService_GetDirectMembers_FullMethodName = "/membership.MembershipService/GetDirectMembers"
	MembershipService_GetAllMembers_FullMethodName    = "/membership.MembershipService/GetAllMembers"
	MembershipService_GetDirectGroups_FullMethodName  = "/membership.MembershipService/GetDirectGroups"
	MembershipService_GetAllGroups_FullMethodName     = "/membership.MembershipService/GetAllGroups"
	MembershipService_IsMember_FullMethodName         = "/membership.MembershipService/IsMember"
	MembershipService_ListGroups_FullMethodName       = "/membership.MembershipService/ListGroups"
)

// MembershipServiceClient is the client API for MembershipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MembershipService manages principal group membership relationships
type MembershipServiceClient interface {
	// Add a principal as a member of a group
	AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*AddMemberResponse, error)
	// Remove a principal from a group
	RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberResponse, error)
	// Get direct members of a group (non-transitive)
	GetDirectMembers(ctx context.Context, in *GetDirectMembersRequest, opts ...grpc.CallOption) (*GetDirectMembersResponse, error)
	// Get all members of a group (transitive - includes nested groups)
	GetAllMembers(ctx context.Context, in *GetAllMembersRequest, opts ...grpc.CallOption) (*GetAllMembersResponse, error)
	// Get direct groups a principal belongs to (non-transitive)
	GetDirectGroups(ctx context.Context, in *GetDirectGroupsRequest, opts ...grpc.CallOption) (*GetDirectGroupsResponse, error)
	// Get all groups a principal belongs to (transitive)
	GetAllGroups(ctx context.Context, in *GetAllGroupsRequest, opts ...grpc.CallOption) (*GetAllGroupsResponse, error)
	// Check if a principal is a member of a group (transitive)
	IsMember(ctx context.Context, in *IsMemberRequest, opts ...grpc.CallOption) (*IsMemberResponse, error)
	// List all groups (principals that have at least one member)
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
}

type membershipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMembershipServiceClient(cc grpc.ClientConnInterface) MembershipServiceClient {
	return &membershipServiceClient{cc}
}

func (c *membershipServiceClient) AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*AddMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMemberResponse)
	err := c.cc.Invoke(ctx, MembershipService_AddMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMemberResponse)
	err := c.cc.Invoke(ctx, MembershipService_RemoveMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) GetDirectMembers(ctx context.Context, in *GetDirectMembersRequest, opts ...grpc.CallOption) (*GetDirectMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDirectMembersResponse)
	err := c.cc.Invoke(ctx, MembershipService_GetDirectMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) GetAllMembers(ctx context.Context, in *GetAllMembersRequest, opts ...grpc.CallOption) (*GetAllMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllMembersResponse)
	err := c.cc.Invoke(ctx, MembershipService_GetAllMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) GetDirectGroups(ctx context.Context, in *GetDirectGroupsRequest, opts ...grpc.CallOption) (*GetDirectGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDirectGroupsResponse)
	err := c.cc.Invoke(ctx, MembershipService_GetDirectGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) GetAllGroups(ctx context.Context, in *GetAllGroupsRequest, opts ...grpc.CallOption) (*GetAllGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllGroupsResponse)
	err := c.cc.Invoke(ctx, MembershipService_GetAllGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) IsMember(ctx context.Context, in *IsMemberRequest, opts ...grpc.CallOption) (*IsMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsMemberResponse)
	err := c.cc.Invoke(ctx, MembershipService_IsMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, MembershipService_ListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MembershipServiceServer is the server API for MembershipService service.
// All implementations must embed UnimplementedMembershipServiceServer
// for forward compatibility.
//
// MembershipService manages principal group membership relationships
type MembershipServiceServer interface {
	// Add a principal as a member of a group
	AddMember(context.Context, *AddMemberRequest) (*AddMemberResponse, error)
	// Remove a principal from a group
	RemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberResponse, error)
	// Get direct members of a group (non-transitive)
	GetDirectMembers(context.Context, *GetDirectMembersRequest) (*GetDirectMembersResponse, error)
	// Get all members of a group (transitive - includes nested groups)
	GetAllMembers(context.Context, *GetAllMembersRequest) (*GetAllMembersResponse, error)
	// Get direct groups a principal belongs to (non-transitive)
	GetDirectGroups(context.Context, *GetDirectGroupsRequest) (*GetDirectGroupsResponse, error)
	// Get all groups a principal belongs to (transitive)
	GetAllGroups(context.Context, *GetAllGroupsRequest) (*GetAllGroupsResponse, error)
	// Check if a principal is a member of a group (transitive)
	IsMember(context.Context, *IsMemberRequest) (*IsMemberResponse, error)
	// List all groups (principals that have at least one member)
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	mustEmbedUnimplementedMembershipServiceServer()
}

// UnimplementedMembershipServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMembershipServiceServer struct{}

func (UnimplementedMembershipServiceServer) AddMember(context.Context, *AddMemberRequest) (*AddMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMember not implemented")
}
func (UnimplementedMembershipServiceServer) RemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMember not implemented")
}
func (UnimplementedMembershipServiceServer) GetDirectMembers(context.Context, *GetDirectMembersRequest) (*GetDirectMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDirectMembers not implemented")
}
func (UnimplementedMembershipServiceServer) GetAllMembers(context.Context, *GetAllMembersRequest) (*GetAllMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllMembers not implemented")
}
func (UnimplementedMembershipServiceServer) GetDirectGroups(context.Context, *GetDirectGroupsRequest) (*GetDirectGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDirectGroups not implemented")
}
func (UnimplementedMembershipServiceServer) GetAllGroups(context.Context, *GetAllGroupsRequest) (*GetAllGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllGroups not implemented")
}
func (UnimplementedMembershipServiceServer) IsMember(context.Context, *IsMemberRequest) (*IsMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsMember not implemented")
}
func (UnimplementedMembershipServiceServer) ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedMembershipServiceServer) mustEmbedUnimplementedMembershipServiceServer() {}
func (UnimplementedMembershipServiceServer) testEmbeddedByValue()                           {}

// UnsafeMembershipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MembershipServiceServer will
// result in compilation errors.
type UnsafeMembershipServiceServer interface {
	mustEmbedUnimplementedMembershipServiceServer()
}

func RegisterMembershipServiceServer(s grpc.ServiceRegistrar, srv MembershipServiceServer) {
	// If the following call panics, it indicates UnimplementedMembershipServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MembershipService_ServiceDesc, srv)
}

func _MembershipService_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_AddMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).AddMember(ctx, req.(*AddMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_RemoveMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).RemoveMember(ctx, req.(*RemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_GetDirectMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDirectMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).GetDirectMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_GetDirectMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).GetDirectMembers(ctx, req.(*GetDirectMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_GetAllMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).GetAllMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_GetAllMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).GetAllMembers(ctx, req.(*GetAllMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_GetDirectGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDirectGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).GetDirectGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_GetDirectGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).GetDirectGroups(ctx, req.(*GetDirectGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_GetAllGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).GetAllGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_GetAllGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).GetAllGroups(ctx, req.(*GetAllGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_IsMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).IsMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_IsMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).IsMember(ctx, req.(*IsMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_ListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MembershipService_ServiceDesc is the grpc.ServiceDesc for MembershipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MembershipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "membership.MembershipService",
	HandlerType: (*MembershipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMember",
			Handler:    _MembershipService_AddMember_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _MembershipService_RemoveMember_Handler,
		},
		{
			MethodName: "GetDirectMembers",
			Handler:    _MembershipService_GetDirectMembers_Handler,
		},
		{
			MethodName: "GetAllMembers",
			Handler:    _MembershipService_GetAllMembers_Handler,
		},
		{
			MethodName: "GetDirectGroups",
			Handler:    _MembershipService_GetDirectGroups_Handler,
		},
		{
			MethodName: "GetAllGroups",
			Handler:    _MembershipService_GetAllGroups_Handler,
		},
		{
			MethodName: "IsMember",
			Handler:    _MembershipService_IsMember_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _MembershipService_ListGroups_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "membership/membership_service.proto",
}
