// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: identity/principal_service.proto

package authapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Create new principal
type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_identity_principal_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_principal_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_identity_principal_service_proto_rawDescGZIP(), []int{0}
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     *Principal             `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_identity_principal_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_principal_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_identity_principal_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetPrincipal() *Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

// Delete principal
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     *Principal             `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_identity_principal_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_principal_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_identity_principal_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRequest) GetPrincipal() *Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_identity_principal_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_principal_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_identity_principal_service_proto_rawDescGZIP(), []int{3}
}

var File_identity_principal_service_proto protoreflect.FileDescriptor

const file_identity_principal_service_proto_rawDesc = "" +
	"\n" +
	" identity/principal_service.proto\x12\bidentity\x1a\x18identity/principal.proto\"\x0f\n" +
	"\rCreateRequest\"C\n" +
	"\x0eCreateResponse\x121\n" +
	"\tprincipal\x18\x01 \x01(\v2\x13.identity.PrincipalR\tprincipal\"B\n" +
	"\rDeleteRequest\x121\n" +
	"\tprincipal\x18\x01 \x01(\v2\x13.identity.PrincipalR\tprincipal\"\x10\n" +
	"\x0eDeleteResponse2\x8c\x01\n" +
	"\x10PrincipalService\x12;\n" +
	"\x06Create\x12\x17.identity.CreateRequest\x1a\x18.identity.CreateResponse\x12;\n" +
	"\x06Delete\x12\x17.identity.DeleteRequest\x1a\x18.identity.DeleteResponseB.Z,git.sonicoriginal.software/grpc-auth;authapib\x06proto3"

var (
	file_identity_principal_service_proto_rawDescOnce sync.Once
	file_identity_principal_service_proto_rawDescData []byte
)

func file_identity_principal_service_proto_rawDescGZIP() []byte {
	file_identity_principal_service_proto_rawDescOnce.Do(func() {
		file_identity_principal_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_principal_service_proto_rawDesc), len(file_identity_principal_service_proto_rawDesc)))
	})
	return file_identity_principal_service_proto_rawDescData
}

var file_identity_principal_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_identity_principal_service_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: identity.CreateRequest
	(*CreateResponse)(nil), // 1: identity.CreateResponse
	(*DeleteRequest)(nil),  // 2: identity.DeleteRequest
	(*DeleteResponse)(nil), // 3: identity.DeleteResponse
	(*Principal)(nil),      // 4: identity.Principal
}
var file_identity_principal_service_proto_depIdxs = []int32{
	4, // 0: identity.CreateResponse.principal:type_name -> identity.Principal
	4, // 1: identity.DeleteRequest.principal:type_name -> identity.Principal
	0, // 2: identity.PrincipalService.Create:input_type -> identity.CreateRequest
	2, // 3: identity.PrincipalService.Delete:input_type -> identity.DeleteRequest
	1, // 4: identity.PrincipalService.Create:output_type -> identity.CreateResponse
	3, // 5: identity.PrincipalService.Delete:output_type -> identity.DeleteResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_identity_principal_service_proto_init() }
func file_identity_principal_service_proto_init() {
	if File_identity_principal_service_proto != nil {
		return
	}
	file_identity_principal_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_principal_service_proto_rawDesc), len(file_identity_principal_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_principal_service_proto_goTypes,
		DependencyIndexes: file_identity_principal_service_proto_depIdxs,
		MessageInfos:      file_identity_principal_service_proto_msgTypes,
	}.Build()
	File_identity_principal_service_proto = out.File
	file_identity_principal_service_proto_goTypes = nil
	file_identity_principal_service_proto_depIdxs = nil
}
