// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: identity/principal_service.proto

package authapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Create new principal
type CreatePrincipalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePrincipalRequest) Reset() {
	*x = CreatePrincipalRequest{}
	mi := &file_identity_principal_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrincipalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrincipalRequest) ProtoMessage() {}

func (x *CreatePrincipalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_principal_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrincipalRequest.ProtoReflect.Descriptor instead.
func (*CreatePrincipalRequest) Descriptor() ([]byte, []int) {
	return file_identity_principal_service_proto_rawDescGZIP(), []int{0}
}

type CreatePrincipalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     *Principal             `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePrincipalResponse) Reset() {
	*x = CreatePrincipalResponse{}
	mi := &file_identity_principal_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrincipalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrincipalResponse) ProtoMessage() {}

func (x *CreatePrincipalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_principal_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrincipalResponse.ProtoReflect.Descriptor instead.
func (*CreatePrincipalResponse) Descriptor() ([]byte, []int) {
	return file_identity_principal_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePrincipalResponse) GetPrincipal() *Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

// Delete principal
type DeletePrincipalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     *Principal             `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePrincipalRequest) Reset() {
	*x = DeletePrincipalRequest{}
	mi := &file_identity_principal_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePrincipalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePrincipalRequest) ProtoMessage() {}

func (x *DeletePrincipalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_principal_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePrincipalRequest.ProtoReflect.Descriptor instead.
func (*DeletePrincipalRequest) Descriptor() ([]byte, []int) {
	return file_identity_principal_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeletePrincipalRequest) GetPrincipal() *Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

type DeletePrincipalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePrincipalResponse) Reset() {
	*x = DeletePrincipalResponse{}
	mi := &file_identity_principal_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePrincipalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePrincipalResponse) ProtoMessage() {}

func (x *DeletePrincipalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_principal_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePrincipalResponse.ProtoReflect.Descriptor instead.
func (*DeletePrincipalResponse) Descriptor() ([]byte, []int) {
	return file_identity_principal_service_proto_rawDescGZIP(), []int{3}
}

var File_identity_principal_service_proto protoreflect.FileDescriptor

const file_identity_principal_service_proto_rawDesc = "" +
	"\n" +
	" identity/principal_service.proto\x12\bidentity\x1a\x18identity/principal.proto\"\x18\n" +
	"\x16CreatePrincipalRequest\"L\n" +
	"\x17CreatePrincipalResponse\x121\n" +
	"\tprincipal\x18\x01 \x01(\v2\x13.identity.PrincipalR\tprincipal\"K\n" +
	"\x16DeletePrincipalRequest\x121\n" +
	"\tprincipal\x18\x01 \x01(\v2\x13.identity.PrincipalR\tprincipal\"\x19\n" +
	"\x17DeletePrincipalResponse2\xc2\x01\n" +
	"\x10PrincipalService\x12V\n" +
	"\x0fCreatePrincipal\x12 .identity.CreatePrincipalRequest\x1a!.identity.CreatePrincipalResponse\x12V\n" +
	"\x0fDeletePrincipal\x12 .identity.DeletePrincipalRequest\x1a!.identity.DeletePrincipalResponseB2Z0git.sonicoriginal.software/grpc-auth-api;authapib\x06proto3"

var (
	file_identity_principal_service_proto_rawDescOnce sync.Once
	file_identity_principal_service_proto_rawDescData []byte
)

func file_identity_principal_service_proto_rawDescGZIP() []byte {
	file_identity_principal_service_proto_rawDescOnce.Do(func() {
		file_identity_principal_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_principal_service_proto_rawDesc), len(file_identity_principal_service_proto_rawDesc)))
	})
	return file_identity_principal_service_proto_rawDescData
}

var file_identity_principal_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_identity_principal_service_proto_goTypes = []any{
	(*CreatePrincipalRequest)(nil),  // 0: identity.CreatePrincipalRequest
	(*CreatePrincipalResponse)(nil), // 1: identity.CreatePrincipalResponse
	(*DeletePrincipalRequest)(nil),  // 2: identity.DeletePrincipalRequest
	(*DeletePrincipalResponse)(nil), // 3: identity.DeletePrincipalResponse
	(*Principal)(nil),               // 4: identity.Principal
}
var file_identity_principal_service_proto_depIdxs = []int32{
	4, // 0: identity.CreatePrincipalResponse.principal:type_name -> identity.Principal
	4, // 1: identity.DeletePrincipalRequest.principal:type_name -> identity.Principal
	0, // 2: identity.PrincipalService.CreatePrincipal:input_type -> identity.CreatePrincipalRequest
	2, // 3: identity.PrincipalService.DeletePrincipal:input_type -> identity.DeletePrincipalRequest
	1, // 4: identity.PrincipalService.CreatePrincipal:output_type -> identity.CreatePrincipalResponse
	3, // 5: identity.PrincipalService.DeletePrincipal:output_type -> identity.DeletePrincipalResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_identity_principal_service_proto_init() }
func file_identity_principal_service_proto_init() {
	if File_identity_principal_service_proto != nil {
		return
	}
	file_identity_principal_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_principal_service_proto_rawDesc), len(file_identity_principal_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_principal_service_proto_goTypes,
		DependencyIndexes: file_identity_principal_service_proto_depIdxs,
		MessageInfos:      file_identity_principal_service_proto_msgTypes,
	}.Build()
	File_identity_principal_service_proto = out.File
	file_identity_principal_service_proto_goTypes = nil
	file_identity_principal_service_proto_depIdxs = nil
}
