// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: token/token_service.proto

package authapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Issue a signed JWT
type IssueTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Audience      []string               `protobuf:"bytes,2,rep,name=audience,proto3" json:"audience,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Optional - If empty, doesn't expire
	NotBefore     int64                  `protobuf:"varint,4,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"` // Optional - If empty, set to now
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenRequest) Reset() {
	*x = IssueTokenRequest{}
	mi := &file_token_token_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenRequest) ProtoMessage() {}

func (x *IssueTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_token_service_proto_rawDescGZIP(), []int{0}
}

func (x *IssueTokenRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *IssueTokenRequest) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *IssueTokenRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *IssueTokenRequest) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

type IssueTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenResponse) Reset() {
	*x = IssueTokenResponse{}
	mi := &file_token_token_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenResponse) ProtoMessage() {}

func (x *IssueTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_token_service_proto_rawDescGZIP(), []int{1}
}

func (x *IssueTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Decode JWT into claims
type DecodeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeTokenRequest) Reset() {
	*x = DecodeTokenRequest{}
	mi := &file_token_token_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeTokenRequest) ProtoMessage() {}

func (x *DecodeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeTokenRequest.ProtoReflect.Descriptor instead.
func (*DecodeTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_token_service_proto_rawDescGZIP(), []int{2}
}

func (x *DecodeTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DecodeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        *Claims                `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeTokenResponse) Reset() {
	*x = DecodeTokenResponse{}
	mi := &file_token_token_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeTokenResponse) ProtoMessage() {}

func (x *DecodeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeTokenResponse.ProtoReflect.Descriptor instead.
func (*DecodeTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_token_service_proto_rawDescGZIP(), []int{3}
}

func (x *DecodeTokenResponse) GetClaims() *Claims {
	if x != nil {
		return x.Claims
	}
	return nil
}

var File_token_token_service_proto protoreflect.FileDescriptor

const file_token_token_service_proto_rawDesc = "" +
	"\n" +
	"\x19token/token_service.proto\x12\x05token\x1a\x10jwt/claims.proto\"\x87\x01\n" +
	"\x11IssueTokenRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1a\n" +
	"\baudience\x18\x02 \x03(\tR\baudience\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x1d\n" +
	"\n" +
	"not_before\x18\x04 \x01(\x03R\tnotBefore\"*\n" +
	"\x12IssueTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"*\n" +
	"\x12DecodeTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\":\n" +
	"\x13DecodeTokenResponse\x12#\n" +
	"\x06claims\x18\x01 \x01(\v2\v.jwt.ClaimsR\x06claims2\x97\x01\n" +
	"\fTokenService\x12A\n" +
	"\n" +
	"IssueToken\x12\x18.token.IssueTokenRequest\x1a\x19.token.IssueTokenResponse\x12D\n" +
	"\vDecodeToken\x12\x19.token.DecodeTokenRequest\x1a\x1a.token.DecodeTokenResponseB2Z0git.sonicoriginal.software/grpc-auth-api;authapib\x06proto3"

var (
	file_token_token_service_proto_rawDescOnce sync.Once
	file_token_token_service_proto_rawDescData []byte
)

func file_token_token_service_proto_rawDescGZIP() []byte {
	file_token_token_service_proto_rawDescOnce.Do(func() {
		file_token_token_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_token_token_service_proto_rawDesc), len(file_token_token_service_proto_rawDesc)))
	})
	return file_token_token_service_proto_rawDescData
}

var file_token_token_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_token_token_service_proto_goTypes = []any{
	(*IssueTokenRequest)(nil),   // 0: token.IssueTokenRequest
	(*IssueTokenResponse)(nil),  // 1: token.IssueTokenResponse
	(*DecodeTokenRequest)(nil),  // 2: token.DecodeTokenRequest
	(*DecodeTokenResponse)(nil), // 3: token.DecodeTokenResponse
	(*Claims)(nil),              // 4: jwt.Claims
}
var file_token_token_service_proto_depIdxs = []int32{
	4, // 0: token.DecodeTokenResponse.claims:type_name -> jwt.Claims
	0, // 1: token.TokenService.IssueToken:input_type -> token.IssueTokenRequest
	2, // 2: token.TokenService.DecodeToken:input_type -> token.DecodeTokenRequest
	1, // 3: token.TokenService.IssueToken:output_type -> token.IssueTokenResponse
	3, // 4: token.TokenService.DecodeToken:output_type -> token.DecodeTokenResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_token_token_service_proto_init() }
func file_token_token_service_proto_init() {
	if File_token_token_service_proto != nil {
		return
	}
	file_jwt_claims_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_token_service_proto_rawDesc), len(file_token_token_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_token_token_service_proto_goTypes,
		DependencyIndexes: file_token_token_service_proto_depIdxs,
		MessageInfos:      file_token_token_service_proto_msgTypes,
	}.Build()
	File_token_token_service_proto = out.File
	file_token_token_service_proto_goTypes = nil
	file_token_token_service_proto_depIdxs = nil
}
