// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: webauthn/webauthn_service.proto

package authapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CredentialFlags contains authenticator flags
type CredentialFlags struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User present (UP) - user was present during authentication
	UserPresent bool `protobuf:"varint,1,opt,name=user_present,json=userPresent,proto3" json:"user_present,omitempty"`
	// User verified (UV) - user was verified (biometric, PIN, etc.)
	UserVerified bool `protobuf:"varint,2,opt,name=user_verified,json=userVerified,proto3" json:"user_verified,omitempty"`
	// Backup eligible (BE) - credential can be backed up
	BackupEligible bool `protobuf:"varint,3,opt,name=backup_eligible,json=backupEligible,proto3" json:"backup_eligible,omitempty"`
	// Backup state (BS) - credential is currently backed up
	BackupState   bool `protobuf:"varint,4,opt,name=backup_state,json=backupState,proto3" json:"backup_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialFlags) Reset() {
	*x = CredentialFlags{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialFlags) ProtoMessage() {}

func (x *CredentialFlags) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialFlags.ProtoReflect.Descriptor instead.
func (*CredentialFlags) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{0}
}

func (x *CredentialFlags) GetUserPresent() bool {
	if x != nil {
		return x.UserPresent
	}
	return false
}

func (x *CredentialFlags) GetUserVerified() bool {
	if x != nil {
		return x.UserVerified
	}
	return false
}

func (x *CredentialFlags) GetBackupEligible() bool {
	if x != nil {
		return x.BackupEligible
	}
	return false
}

func (x *CredentialFlags) GetBackupState() bool {
	if x != nil {
		return x.BackupState
	}
	return false
}

// Authenticator information for a credential
type Authenticator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AAGUID - Authenticator Attestation GUID
	Aaguid []byte `protobuf:"bytes,1,opt,name=aaguid,proto3" json:"aaguid,omitempty"`
	// Sign counter for replay attack detection
	SignCount int64 `protobuf:"varint,2,opt,name=sign_count,json=signCount,proto3" json:"sign_count,omitempty"`
	// Clone warning - if true, possible cloned authenticator detected
	CloneWarning bool `protobuf:"varint,3,opt,name=clone_warning,json=cloneWarning,proto3" json:"clone_warning,omitempty"`
	// Attachment type (platform, cross-platform)
	Attachment    string `protobuf:"bytes,4,opt,name=attachment,proto3" json:"attachment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authenticator) Reset() {
	*x = Authenticator{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authenticator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authenticator) ProtoMessage() {}

func (x *Authenticator) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authenticator.ProtoReflect.Descriptor instead.
func (*Authenticator) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{1}
}

func (x *Authenticator) GetAaguid() []byte {
	if x != nil {
		return x.Aaguid
	}
	return nil
}

func (x *Authenticator) GetSignCount() int64 {
	if x != nil {
		return x.SignCount
	}
	return 0
}

func (x *Authenticator) GetCloneWarning() bool {
	if x != nil {
		return x.CloneWarning
	}
	return false
}

func (x *Authenticator) GetAttachment() string {
	if x != nil {
		return x.Attachment
	}
	return ""
}

// CredentialAttestation contains attestation data from registration
type CredentialAttestation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attestation object - CBOR encoded attestation data
	Object []byte `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// Client data JSON from registration
	ClientDataJson []byte `protobuf:"bytes,2,opt,name=client_data_json,json=clientDataJson,proto3" json:"client_data_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CredentialAttestation) Reset() {
	*x = CredentialAttestation{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialAttestation) ProtoMessage() {}

func (x *CredentialAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialAttestation.ProtoReflect.Descriptor instead.
func (*CredentialAttestation) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{2}
}

func (x *CredentialAttestation) GetObject() []byte {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *CredentialAttestation) GetClientDataJson() []byte {
	if x != nil {
		return x.ClientDataJson
	}
	return nil
}

// WebAuthn credential for passkey authentication
type WebAuthnCredential struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Credential ID - unique identifier for this credential
	CredentialId string `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	// Public key for signature verification
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Attestation type (e.g., "packed", "fido-u2f", "none")
	AttestationType string `protobuf:"bytes,3,opt,name=attestation_type,json=attestationType,proto3" json:"attestation_type,omitempty"`
	// Transport methods supported by this authenticator
	// Values from WebAuthn spec: "usb", "nfc", "ble", "internal", "hybrid", "smart-card"
	// Forward-compatible with future transport types
	Transport []string `protobuf:"bytes,4,rep,name=transport,proto3" json:"transport,omitempty"`
	// Authenticator flags
	Flags *CredentialFlags `protobuf:"bytes,5,opt,name=flags,proto3" json:"flags,omitempty"`
	// Authenticator information
	Authenticator *Authenticator `protobuf:"bytes,6,opt,name=authenticator,proto3" json:"authenticator,omitempty"`
	// Attestation data (can be omitted if attestation_type is "none")
	Attestation *CredentialAttestation `protobuf:"bytes,7,opt,name=attestation,proto3" json:"attestation,omitempty"`
	// Human-readable name for this credential (e.g., "YubiKey 5", "iPhone 15")
	Name string `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	// When this credential was created
	CreatedAt int64 `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last time this credential was used for authentication
	LastUsedAt    int64 `protobuf:"varint,10,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebAuthnCredential) Reset() {
	*x = WebAuthnCredential{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAuthnCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAuthnCredential) ProtoMessage() {}

func (x *WebAuthnCredential) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAuthnCredential.ProtoReflect.Descriptor instead.
func (*WebAuthnCredential) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{3}
}

func (x *WebAuthnCredential) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *WebAuthnCredential) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *WebAuthnCredential) GetAttestationType() string {
	if x != nil {
		return x.AttestationType
	}
	return ""
}

func (x *WebAuthnCredential) GetTransport() []string {
	if x != nil {
		return x.Transport
	}
	return nil
}

func (x *WebAuthnCredential) GetFlags() *CredentialFlags {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *WebAuthnCredential) GetAuthenticator() *Authenticator {
	if x != nil {
		return x.Authenticator
	}
	return nil
}

func (x *WebAuthnCredential) GetAttestation() *CredentialAttestation {
	if x != nil {
		return x.Attestation
	}
	return nil
}

func (x *WebAuthnCredential) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WebAuthnCredential) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *WebAuthnCredential) GetLastUsedAt() int64 {
	if x != nil {
		return x.LastUsedAt
	}
	return 0
}

// Begin WebAuthn registration
type BeginWebAuthnRegistrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional user name (e.g., username or email)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional display name for UI presentation
	DisplayName   string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // NOTE: user.id is always server-generated from principal ID, never client-provided
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginWebAuthnRegistrationRequest) Reset() {
	*x = BeginWebAuthnRegistrationRequest{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginWebAuthnRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginWebAuthnRegistrationRequest) ProtoMessage() {}

func (x *BeginWebAuthnRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginWebAuthnRegistrationRequest.ProtoReflect.Descriptor instead.
func (*BeginWebAuthnRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{4}
}

func (x *BeginWebAuthnRegistrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BeginWebAuthnRegistrationRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type BeginWebAuthnRegistrationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Challenge options to send to browser (JSON-encoded CredentialCreationOptions)
	Options []byte `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	// Session token for completing registration (stateless session via JWT)
	SessionToken  string `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginWebAuthnRegistrationResponse) Reset() {
	*x = BeginWebAuthnRegistrationResponse{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginWebAuthnRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginWebAuthnRegistrationResponse) ProtoMessage() {}

func (x *BeginWebAuthnRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginWebAuthnRegistrationResponse.ProtoReflect.Descriptor instead.
func (*BeginWebAuthnRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{5}
}

func (x *BeginWebAuthnRegistrationResponse) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *BeginWebAuthnRegistrationResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

// Finish WebAuthn registration
type FinishWebAuthnRegistrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WebAuthn credential data from browser
	CredentialData []byte `protobuf:"bytes,1,opt,name=credential_data,json=credentialData,proto3" json:"credential_data,omitempty"`
	// Session token from BeginRegistration
	SessionToken  string `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishWebAuthnRegistrationRequest) Reset() {
	*x = FinishWebAuthnRegistrationRequest{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishWebAuthnRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishWebAuthnRegistrationRequest) ProtoMessage() {}

func (x *FinishWebAuthnRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishWebAuthnRegistrationRequest.ProtoReflect.Descriptor instead.
func (*FinishWebAuthnRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{6}
}

func (x *FinishWebAuthnRegistrationRequest) GetCredentialData() []byte {
	if x != nil {
		return x.CredentialData
	}
	return nil
}

func (x *FinishWebAuthnRegistrationRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type FinishWebAuthnRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        *Claims                `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishWebAuthnRegistrationResponse) Reset() {
	*x = FinishWebAuthnRegistrationResponse{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishWebAuthnRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishWebAuthnRegistrationResponse) ProtoMessage() {}

func (x *FinishWebAuthnRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishWebAuthnRegistrationResponse.ProtoReflect.Descriptor instead.
func (*FinishWebAuthnRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{7}
}

func (x *FinishWebAuthnRegistrationResponse) GetClaims() *Claims {
	if x != nil {
		return x.Claims
	}
	return nil
}

// Begin WebAuthn login
type BeginWebAuthnLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginWebAuthnLoginRequest) Reset() {
	*x = BeginWebAuthnLoginRequest{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginWebAuthnLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginWebAuthnLoginRequest) ProtoMessage() {}

func (x *BeginWebAuthnLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginWebAuthnLoginRequest.ProtoReflect.Descriptor instead.
func (*BeginWebAuthnLoginRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{8}
}

type BeginWebAuthnLoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Challenge options to send to browser (JSON-encoded CredentialRequestOptions)
	Options []byte `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	// Session token for completing login
	SessionToken  string `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginWebAuthnLoginResponse) Reset() {
	*x = BeginWebAuthnLoginResponse{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginWebAuthnLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginWebAuthnLoginResponse) ProtoMessage() {}

func (x *BeginWebAuthnLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginWebAuthnLoginResponse.ProtoReflect.Descriptor instead.
func (*BeginWebAuthnLoginResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{9}
}

func (x *BeginWebAuthnLoginResponse) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *BeginWebAuthnLoginResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

// Finish WebAuthn login
type FinishWebAuthnLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Assertion data from browser
	AssertionData []byte `protobuf:"bytes,1,opt,name=assertion_data,json=assertionData,proto3" json:"assertion_data,omitempty"`
	// Session token from BeginLogin
	SessionToken  string `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishWebAuthnLoginRequest) Reset() {
	*x = FinishWebAuthnLoginRequest{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishWebAuthnLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishWebAuthnLoginRequest) ProtoMessage() {}

func (x *FinishWebAuthnLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishWebAuthnLoginRequest.ProtoReflect.Descriptor instead.
func (*FinishWebAuthnLoginRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{10}
}

func (x *FinishWebAuthnLoginRequest) GetAssertionData() []byte {
	if x != nil {
		return x.AssertionData
	}
	return nil
}

func (x *FinishWebAuthnLoginRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type FinishWebAuthnLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        *Claims                `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishWebAuthnLoginResponse) Reset() {
	*x = FinishWebAuthnLoginResponse{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishWebAuthnLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishWebAuthnLoginResponse) ProtoMessage() {}

func (x *FinishWebAuthnLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishWebAuthnLoginResponse.ProtoReflect.Descriptor instead.
func (*FinishWebAuthnLoginResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{11}
}

func (x *FinishWebAuthnLoginResponse) GetClaims() *Claims {
	if x != nil {
		return x.Claims
	}
	return nil
}

// Add credential request
type AddWebAuthnCredentialRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WebAuthn credential data from browser (contains credential_id, public_key, etc.)
	CredentialData []byte `protobuf:"bytes,1,opt,name=credential_data,json=credentialData,proto3" json:"credential_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddWebAuthnCredentialRequest) Reset() {
	*x = AddWebAuthnCredentialRequest{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWebAuthnCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWebAuthnCredentialRequest) ProtoMessage() {}

func (x *AddWebAuthnCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWebAuthnCredentialRequest.ProtoReflect.Descriptor instead.
func (*AddWebAuthnCredentialRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{12}
}

func (x *AddWebAuthnCredentialRequest) GetCredentialData() []byte {
	if x != nil {
		return x.CredentialData
	}
	return nil
}

// Add credential response
type AddWebAuthnCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWebAuthnCredentialResponse) Reset() {
	*x = AddWebAuthnCredentialResponse{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWebAuthnCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWebAuthnCredentialResponse) ProtoMessage() {}

func (x *AddWebAuthnCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWebAuthnCredentialResponse.ProtoReflect.Descriptor instead.
func (*AddWebAuthnCredentialResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{13}
}

func (x *AddWebAuthnCredentialResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// List credentials request
type ListWebAuthnCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebAuthnCredentialsRequest) Reset() {
	*x = ListWebAuthnCredentialsRequest{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebAuthnCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebAuthnCredentialsRequest) ProtoMessage() {}

func (x *ListWebAuthnCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebAuthnCredentialsRequest.ProtoReflect.Descriptor instead.
func (*ListWebAuthnCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{14}
}

type ListWebAuthnCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []*WebAuthnCredential  `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebAuthnCredentialsResponse) Reset() {
	*x = ListWebAuthnCredentialsResponse{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebAuthnCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebAuthnCredentialsResponse) ProtoMessage() {}

func (x *ListWebAuthnCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebAuthnCredentialsResponse.ProtoReflect.Descriptor instead.
func (*ListWebAuthnCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListWebAuthnCredentialsResponse) GetCredentials() []*WebAuthnCredential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

// Delete credential request
type DeleteWebAuthnCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CredentialId  string                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebAuthnCredentialRequest) Reset() {
	*x = DeleteWebAuthnCredentialRequest{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebAuthnCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebAuthnCredentialRequest) ProtoMessage() {}

func (x *DeleteWebAuthnCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebAuthnCredentialRequest.ProtoReflect.Descriptor instead.
func (*DeleteWebAuthnCredentialRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteWebAuthnCredentialRequest) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

type DeleteWebAuthnCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebAuthnCredentialResponse) Reset() {
	*x = DeleteWebAuthnCredentialResponse{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebAuthnCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebAuthnCredentialResponse) ProtoMessage() {}

func (x *DeleteWebAuthnCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebAuthnCredentialResponse.ProtoReflect.Descriptor instead.
func (*DeleteWebAuthnCredentialResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteWebAuthnCredentialResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_webauthn_webauthn_service_proto protoreflect.FileDescriptor

const file_webauthn_webauthn_service_proto_rawDesc = "" +
	"\n" +
	"\x1fwebauthn/webauthn_service.proto\x12\bwebauthn\x1a\x10jwt/claims.proto\"\xa5\x01\n" +
	"\x0fCredentialFlags\x12!\n" +
	"\fuser_present\x18\x01 \x01(\bR\vuserPresent\x12#\n" +
	"\ruser_verified\x18\x02 \x01(\bR\fuserVerified\x12'\n" +
	"\x0fbackup_eligible\x18\x03 \x01(\bR\x0ebackupEligible\x12!\n" +
	"\fbackup_state\x18\x04 \x01(\bR\vbackupState\"\x8b\x01\n" +
	"\rAuthenticator\x12\x16\n" +
	"\x06aaguid\x18\x01 \x01(\fR\x06aaguid\x12\x1d\n" +
	"\n" +
	"sign_count\x18\x02 \x01(\x03R\tsignCount\x12#\n" +
	"\rclone_warning\x18\x03 \x01(\bR\fcloneWarning\x12\x1e\n" +
	"\n" +
	"attachment\x18\x04 \x01(\tR\n" +
	"attachment\"Y\n" +
	"\x15CredentialAttestation\x12\x16\n" +
	"\x06object\x18\x01 \x01(\fR\x06object\x12(\n" +
	"\x10client_data_json\x18\x02 \x01(\fR\x0eclientDataJson\"\xa9\x03\n" +
	"\x12WebAuthnCredential\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\tR\fcredentialId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12)\n" +
	"\x10attestation_type\x18\x03 \x01(\tR\x0fattestationType\x12\x1c\n" +
	"\ttransport\x18\x04 \x03(\tR\ttransport\x12/\n" +
	"\x05flags\x18\x05 \x01(\v2\x19.webauthn.CredentialFlagsR\x05flags\x12=\n" +
	"\rauthenticator\x18\x06 \x01(\v2\x17.webauthn.AuthenticatorR\rauthenticator\x12A\n" +
	"\vattestation\x18\a \x01(\v2\x1f.webauthn.CredentialAttestationR\vattestation\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12 \n" +
	"\flast_used_at\x18\n" +
	" \x01(\x03R\n" +
	"lastUsedAt\"Y\n" +
	" BeginWebAuthnRegistrationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"b\n" +
	"!BeginWebAuthnRegistrationResponse\x12\x18\n" +
	"\aoptions\x18\x01 \x01(\fR\aoptions\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\"q\n" +
	"!FinishWebAuthnRegistrationRequest\x12'\n" +
	"\x0fcredential_data\x18\x01 \x01(\fR\x0ecredentialData\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\"I\n" +
	"\"FinishWebAuthnRegistrationResponse\x12#\n" +
	"\x06claims\x18\x01 \x01(\v2\v.jwt.ClaimsR\x06claims\"\x1b\n" +
	"\x19BeginWebAuthnLoginRequest\"[\n" +
	"\x1aBeginWebAuthnLoginResponse\x12\x18\n" +
	"\aoptions\x18\x01 \x01(\fR\aoptions\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\"h\n" +
	"\x1aFinishWebAuthnLoginRequest\x12%\n" +
	"\x0eassertion_data\x18\x01 \x01(\fR\rassertionData\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\"B\n" +
	"\x1bFinishWebAuthnLoginResponse\x12#\n" +
	"\x06claims\x18\x01 \x01(\v2\v.jwt.ClaimsR\x06claims\"G\n" +
	"\x1cAddWebAuthnCredentialRequest\x12'\n" +
	"\x0fcredential_data\x18\x01 \x01(\fR\x0ecredentialData\"9\n" +
	"\x1dAddWebAuthnCredentialResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\" \n" +
	"\x1eListWebAuthnCredentialsRequest\"a\n" +
	"\x1fListWebAuthnCredentialsResponse\x12>\n" +
	"\vcredentials\x18\x01 \x03(\v2\x1c.webauthn.WebAuthnCredentialR\vcredentials\"F\n" +
	"\x1fDeleteWebAuthnCredentialRequest\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\tR\fcredentialId\"<\n" +
	" DeleteWebAuthnCredentialResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x92\x06\n" +
	"\x0fWebAuthnService\x12t\n" +
	"\x19BeginWebAuthnRegistration\x12*.webauthn.BeginWebAuthnRegistrationRequest\x1a+.webauthn.BeginWebAuthnRegistrationResponse\x12w\n" +
	"\x1aFinishWebAuthnRegistration\x12+.webauthn.FinishWebAuthnRegistrationRequest\x1a,.webauthn.FinishWebAuthnRegistrationResponse\x12_\n" +
	"\x12BeginWebAuthnLogin\x12#.webauthn.BeginWebAuthnLoginRequest\x1a$.webauthn.BeginWebAuthnLoginResponse\x12b\n" +
	"\x13FinishWebAuthnLogin\x12$.webauthn.FinishWebAuthnLoginRequest\x1a%.webauthn.FinishWebAuthnLoginResponse\x12h\n" +
	"\x15AddWebAuthnCredential\x12&.webauthn.AddWebAuthnCredentialRequest\x1a'.webauthn.AddWebAuthnCredentialResponse\x12n\n" +
	"\x17ListWebAuthnCredentials\x12(.webauthn.ListWebAuthnCredentialsRequest\x1a).webauthn.ListWebAuthnCredentialsResponse\x12q\n" +
	"\x18DeleteWebAuthnCredential\x12).webauthn.DeleteWebAuthnCredentialRequest\x1a*.webauthn.DeleteWebAuthnCredentialResponseB2Z0git.sonicoriginal.software/grpc-auth-api;authapib\x06proto3"

var (
	file_webauthn_webauthn_service_proto_rawDescOnce sync.Once
	file_webauthn_webauthn_service_proto_rawDescData []byte
)

func file_webauthn_webauthn_service_proto_rawDescGZIP() []byte {
	file_webauthn_webauthn_service_proto_rawDescOnce.Do(func() {
		file_webauthn_webauthn_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webauthn_webauthn_service_proto_rawDesc), len(file_webauthn_webauthn_service_proto_rawDesc)))
	})
	return file_webauthn_webauthn_service_proto_rawDescData
}

var file_webauthn_webauthn_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_webauthn_webauthn_service_proto_goTypes = []any{
	(*CredentialFlags)(nil),                    // 0: webauthn.CredentialFlags
	(*Authenticator)(nil),                      // 1: webauthn.Authenticator
	(*CredentialAttestation)(nil),              // 2: webauthn.CredentialAttestation
	(*WebAuthnCredential)(nil),                 // 3: webauthn.WebAuthnCredential
	(*BeginWebAuthnRegistrationRequest)(nil),   // 4: webauthn.BeginWebAuthnRegistrationRequest
	(*BeginWebAuthnRegistrationResponse)(nil),  // 5: webauthn.BeginWebAuthnRegistrationResponse
	(*FinishWebAuthnRegistrationRequest)(nil),  // 6: webauthn.FinishWebAuthnRegistrationRequest
	(*FinishWebAuthnRegistrationResponse)(nil), // 7: webauthn.FinishWebAuthnRegistrationResponse
	(*BeginWebAuthnLoginRequest)(nil),          // 8: webauthn.BeginWebAuthnLoginRequest
	(*BeginWebAuthnLoginResponse)(nil),         // 9: webauthn.BeginWebAuthnLoginResponse
	(*FinishWebAuthnLoginRequest)(nil),         // 10: webauthn.FinishWebAuthnLoginRequest
	(*FinishWebAuthnLoginResponse)(nil),        // 11: webauthn.FinishWebAuthnLoginResponse
	(*AddWebAuthnCredentialRequest)(nil),       // 12: webauthn.AddWebAuthnCredentialRequest
	(*AddWebAuthnCredentialResponse)(nil),      // 13: webauthn.AddWebAuthnCredentialResponse
	(*ListWebAuthnCredentialsRequest)(nil),     // 14: webauthn.ListWebAuthnCredentialsRequest
	(*ListWebAuthnCredentialsResponse)(nil),    // 15: webauthn.ListWebAuthnCredentialsResponse
	(*DeleteWebAuthnCredentialRequest)(nil),    // 16: webauthn.DeleteWebAuthnCredentialRequest
	(*DeleteWebAuthnCredentialResponse)(nil),   // 17: webauthn.DeleteWebAuthnCredentialResponse
	(*Claims)(nil),                             // 18: jwt.Claims
}
var file_webauthn_webauthn_service_proto_depIdxs = []int32{
	0,  // 0: webauthn.WebAuthnCredential.flags:type_name -> webauthn.CredentialFlags
	1,  // 1: webauthn.WebAuthnCredential.authenticator:type_name -> webauthn.Authenticator
	2,  // 2: webauthn.WebAuthnCredential.attestation:type_name -> webauthn.CredentialAttestation
	18, // 3: webauthn.FinishWebAuthnRegistrationResponse.claims:type_name -> jwt.Claims
	18, // 4: webauthn.FinishWebAuthnLoginResponse.claims:type_name -> jwt.Claims
	3,  // 5: webauthn.ListWebAuthnCredentialsResponse.credentials:type_name -> webauthn.WebAuthnCredential
	4,  // 6: webauthn.WebAuthnService.BeginWebAuthnRegistration:input_type -> webauthn.BeginWebAuthnRegistrationRequest
	6,  // 7: webauthn.WebAuthnService.FinishWebAuthnRegistration:input_type -> webauthn.FinishWebAuthnRegistrationRequest
	8,  // 8: webauthn.WebAuthnService.BeginWebAuthnLogin:input_type -> webauthn.BeginWebAuthnLoginRequest
	10, // 9: webauthn.WebAuthnService.FinishWebAuthnLogin:input_type -> webauthn.FinishWebAuthnLoginRequest
	12, // 10: webauthn.WebAuthnService.AddWebAuthnCredential:input_type -> webauthn.AddWebAuthnCredentialRequest
	14, // 11: webauthn.WebAuthnService.ListWebAuthnCredentials:input_type -> webauthn.ListWebAuthnCredentialsRequest
	16, // 12: webauthn.WebAuthnService.DeleteWebAuthnCredential:input_type -> webauthn.DeleteWebAuthnCredentialRequest
	5,  // 13: webauthn.WebAuthnService.BeginWebAuthnRegistration:output_type -> webauthn.BeginWebAuthnRegistrationResponse
	7,  // 14: webauthn.WebAuthnService.FinishWebAuthnRegistration:output_type -> webauthn.FinishWebAuthnRegistrationResponse
	9,  // 15: webauthn.WebAuthnService.BeginWebAuthnLogin:output_type -> webauthn.BeginWebAuthnLoginResponse
	11, // 16: webauthn.WebAuthnService.FinishWebAuthnLogin:output_type -> webauthn.FinishWebAuthnLoginResponse
	13, // 17: webauthn.WebAuthnService.AddWebAuthnCredential:output_type -> webauthn.AddWebAuthnCredentialResponse
	15, // 18: webauthn.WebAuthnService.ListWebAuthnCredentials:output_type -> webauthn.ListWebAuthnCredentialsResponse
	17, // 19: webauthn.WebAuthnService.DeleteWebAuthnCredential:output_type -> webauthn.DeleteWebAuthnCredentialResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_webauthn_webauthn_service_proto_init() }
func file_webauthn_webauthn_service_proto_init() {
	if File_webauthn_webauthn_service_proto != nil {
		return
	}
	file_jwt_claims_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webauthn_webauthn_service_proto_rawDesc), len(file_webauthn_webauthn_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webauthn_webauthn_service_proto_goTypes,
		DependencyIndexes: file_webauthn_webauthn_service_proto_depIdxs,
		MessageInfos:      file_webauthn_webauthn_service_proto_msgTypes,
	}.Build()
	File_webauthn_webauthn_service_proto = out.File
	file_webauthn_webauthn_service_proto_goTypes = nil
	file_webauthn_webauthn_service_proto_depIdxs = nil
}
