// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: webauthn/webauthn_service.proto

package authapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebAuthnService_BeginWebAuthnRegistration_FullMethodName  = "/webauthn.WebAuthnService/BeginWebAuthnRegistration"
	WebAuthnService_FinishWebAuthnRegistration_FullMethodName = "/webauthn.WebAuthnService/FinishWebAuthnRegistration"
	WebAuthnService_BeginWebAuthnLogin_FullMethodName         = "/webauthn.WebAuthnService/BeginWebAuthnLogin"
	WebAuthnService_FinishWebAuthnLogin_FullMethodName        = "/webauthn.WebAuthnService/FinishWebAuthnLogin"
	WebAuthnService_AddWebAuthnCredential_FullMethodName      = "/webauthn.WebAuthnService/AddWebAuthnCredential"
	WebAuthnService_ListWebAuthnCredentials_FullMethodName    = "/webauthn.WebAuthnService/ListWebAuthnCredentials"
	WebAuthnService_DeleteWebAuthnCredential_FullMethodName   = "/webauthn.WebAuthnService/DeleteWebAuthnCredential"
)

// WebAuthnServiceClient is the client API for WebAuthnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WebAuthnService handles WebAuthn/Passkey identity verification
type WebAuthnServiceClient interface {
	// BeginRegistration starts WebAuthn registration (returns challenge)
	BeginWebAuthnRegistration(ctx context.Context, in *BeginWebAuthnRegistrationRequest, opts ...grpc.CallOption) (*BeginWebAuthnRegistrationResponse, error)
	// FinishRegistration completes registration and creates principal
	FinishWebAuthnRegistration(ctx context.Context, in *FinishWebAuthnRegistrationRequest, opts ...grpc.CallOption) (*FinishWebAuthnRegistrationResponse, error)
	// BeginLogin starts WebAuthn authentication (returns challenge)
	BeginWebAuthnLogin(ctx context.Context, in *BeginWebAuthnLoginRequest, opts ...grpc.CallOption) (*BeginWebAuthnLoginResponse, error)
	// FinishLogin completes authentication and returns access token
	FinishWebAuthnLogin(ctx context.Context, in *FinishWebAuthnLoginRequest, opts ...grpc.CallOption) (*FinishWebAuthnLoginResponse, error)
	// Add additional WebAuthn credential to authenticated principal's account
	AddWebAuthnCredential(ctx context.Context, in *AddWebAuthnCredentialRequest, opts ...grpc.CallOption) (*AddWebAuthnCredentialResponse, error)
	// List all WebAuthn credentials for authenticated principal
	ListWebAuthnCredentials(ctx context.Context, in *ListWebAuthnCredentialsRequest, opts ...grpc.CallOption) (*ListWebAuthnCredentialsResponse, error)
	// Delete a specific WebAuthn credential (revoke compromised authenticator)
	DeleteWebAuthnCredential(ctx context.Context, in *DeleteWebAuthnCredentialRequest, opts ...grpc.CallOption) (*DeleteWebAuthnCredentialResponse, error)
}

type webAuthnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebAuthnServiceClient(cc grpc.ClientConnInterface) WebAuthnServiceClient {
	return &webAuthnServiceClient{cc}
}

func (c *webAuthnServiceClient) BeginWebAuthnRegistration(ctx context.Context, in *BeginWebAuthnRegistrationRequest, opts ...grpc.CallOption) (*BeginWebAuthnRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginWebAuthnRegistrationResponse)
	err := c.cc.Invoke(ctx, WebAuthnService_BeginWebAuthnRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webAuthnServiceClient) FinishWebAuthnRegistration(ctx context.Context, in *FinishWebAuthnRegistrationRequest, opts ...grpc.CallOption) (*FinishWebAuthnRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishWebAuthnRegistrationResponse)
	err := c.cc.Invoke(ctx, WebAuthnService_FinishWebAuthnRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webAuthnServiceClient) BeginWebAuthnLogin(ctx context.Context, in *BeginWebAuthnLoginRequest, opts ...grpc.CallOption) (*BeginWebAuthnLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginWebAuthnLoginResponse)
	err := c.cc.Invoke(ctx, WebAuthnService_BeginWebAuthnLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webAuthnServiceClient) FinishWebAuthnLogin(ctx context.Context, in *FinishWebAuthnLoginRequest, opts ...grpc.CallOption) (*FinishWebAuthnLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishWebAuthnLoginResponse)
	err := c.cc.Invoke(ctx, WebAuthnService_FinishWebAuthnLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webAuthnServiceClient) AddWebAuthnCredential(ctx context.Context, in *AddWebAuthnCredentialRequest, opts ...grpc.CallOption) (*AddWebAuthnCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddWebAuthnCredentialResponse)
	err := c.cc.Invoke(ctx, WebAuthnService_AddWebAuthnCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webAuthnServiceClient) ListWebAuthnCredentials(ctx context.Context, in *ListWebAuthnCredentialsRequest, opts ...grpc.CallOption) (*ListWebAuthnCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWebAuthnCredentialsResponse)
	err := c.cc.Invoke(ctx, WebAuthnService_ListWebAuthnCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webAuthnServiceClient) DeleteWebAuthnCredential(ctx context.Context, in *DeleteWebAuthnCredentialRequest, opts ...grpc.CallOption) (*DeleteWebAuthnCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWebAuthnCredentialResponse)
	err := c.cc.Invoke(ctx, WebAuthnService_DeleteWebAuthnCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebAuthnServiceServer is the server API for WebAuthnService service.
// All implementations must embed UnimplementedWebAuthnServiceServer
// for forward compatibility.
//
// WebAuthnService handles WebAuthn/Passkey identity verification
type WebAuthnServiceServer interface {
	// BeginRegistration starts WebAuthn registration (returns challenge)
	BeginWebAuthnRegistration(context.Context, *BeginWebAuthnRegistrationRequest) (*BeginWebAuthnRegistrationResponse, error)
	// FinishRegistration completes registration and creates principal
	FinishWebAuthnRegistration(context.Context, *FinishWebAuthnRegistrationRequest) (*FinishWebAuthnRegistrationResponse, error)
	// BeginLogin starts WebAuthn authentication (returns challenge)
	BeginWebAuthnLogin(context.Context, *BeginWebAuthnLoginRequest) (*BeginWebAuthnLoginResponse, error)
	// FinishLogin completes authentication and returns access token
	FinishWebAuthnLogin(context.Context, *FinishWebAuthnLoginRequest) (*FinishWebAuthnLoginResponse, error)
	// Add additional WebAuthn credential to authenticated principal's account
	AddWebAuthnCredential(context.Context, *AddWebAuthnCredentialRequest) (*AddWebAuthnCredentialResponse, error)
	// List all WebAuthn credentials for authenticated principal
	ListWebAuthnCredentials(context.Context, *ListWebAuthnCredentialsRequest) (*ListWebAuthnCredentialsResponse, error)
	// Delete a specific WebAuthn credential (revoke compromised authenticator)
	DeleteWebAuthnCredential(context.Context, *DeleteWebAuthnCredentialRequest) (*DeleteWebAuthnCredentialResponse, error)
	mustEmbedUnimplementedWebAuthnServiceServer()
}

// UnimplementedWebAuthnServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebAuthnServiceServer struct{}

func (UnimplementedWebAuthnServiceServer) BeginWebAuthnRegistration(context.Context, *BeginWebAuthnRegistrationRequest) (*BeginWebAuthnRegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginWebAuthnRegistration not implemented")
}
func (UnimplementedWebAuthnServiceServer) FinishWebAuthnRegistration(context.Context, *FinishWebAuthnRegistrationRequest) (*FinishWebAuthnRegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinishWebAuthnRegistration not implemented")
}
func (UnimplementedWebAuthnServiceServer) BeginWebAuthnLogin(context.Context, *BeginWebAuthnLoginRequest) (*BeginWebAuthnLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginWebAuthnLogin not implemented")
}
func (UnimplementedWebAuthnServiceServer) FinishWebAuthnLogin(context.Context, *FinishWebAuthnLoginRequest) (*FinishWebAuthnLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinishWebAuthnLogin not implemented")
}
func (UnimplementedWebAuthnServiceServer) AddWebAuthnCredential(context.Context, *AddWebAuthnCredentialRequest) (*AddWebAuthnCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddWebAuthnCredential not implemented")
}
func (UnimplementedWebAuthnServiceServer) ListWebAuthnCredentials(context.Context, *ListWebAuthnCredentialsRequest) (*ListWebAuthnCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWebAuthnCredentials not implemented")
}
func (UnimplementedWebAuthnServiceServer) DeleteWebAuthnCredential(context.Context, *DeleteWebAuthnCredentialRequest) (*DeleteWebAuthnCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWebAuthnCredential not implemented")
}
func (UnimplementedWebAuthnServiceServer) mustEmbedUnimplementedWebAuthnServiceServer() {}
func (UnimplementedWebAuthnServiceServer) testEmbeddedByValue()                         {}

// UnsafeWebAuthnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebAuthnServiceServer will
// result in compilation errors.
type UnsafeWebAuthnServiceServer interface {
	mustEmbedUnimplementedWebAuthnServiceServer()
}

func RegisterWebAuthnServiceServer(s grpc.ServiceRegistrar, srv WebAuthnServiceServer) {
	// If the following call panics, it indicates UnimplementedWebAuthnServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebAuthnService_ServiceDesc, srv)
}

func _WebAuthnService_BeginWebAuthnRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginWebAuthnRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebAuthnServiceServer).BeginWebAuthnRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebAuthnService_BeginWebAuthnRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebAuthnServiceServer).BeginWebAuthnRegistration(ctx, req.(*BeginWebAuthnRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebAuthnService_FinishWebAuthnRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishWebAuthnRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebAuthnServiceServer).FinishWebAuthnRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebAuthnService_FinishWebAuthnRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebAuthnServiceServer).FinishWebAuthnRegistration(ctx, req.(*FinishWebAuthnRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebAuthnService_BeginWebAuthnLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginWebAuthnLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebAuthnServiceServer).BeginWebAuthnLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebAuthnService_BeginWebAuthnLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebAuthnServiceServer).BeginWebAuthnLogin(ctx, req.(*BeginWebAuthnLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebAuthnService_FinishWebAuthnLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishWebAuthnLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebAuthnServiceServer).FinishWebAuthnLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebAuthnService_FinishWebAuthnLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebAuthnServiceServer).FinishWebAuthnLogin(ctx, req.(*FinishWebAuthnLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebAuthnService_AddWebAuthnCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWebAuthnCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebAuthnServiceServer).AddWebAuthnCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebAuthnService_AddWebAuthnCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebAuthnServiceServer).AddWebAuthnCredential(ctx, req.(*AddWebAuthnCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebAuthnService_ListWebAuthnCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWebAuthnCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebAuthnServiceServer).ListWebAuthnCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebAuthnService_ListWebAuthnCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebAuthnServiceServer).ListWebAuthnCredentials(ctx, req.(*ListWebAuthnCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebAuthnService_DeleteWebAuthnCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWebAuthnCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebAuthnServiceServer).DeleteWebAuthnCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebAuthnService_DeleteWebAuthnCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebAuthnServiceServer).DeleteWebAuthnCredential(ctx, req.(*DeleteWebAuthnCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebAuthnService_ServiceDesc is the grpc.ServiceDesc for WebAuthnService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebAuthnService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webauthn.WebAuthnService",
	HandlerType: (*WebAuthnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeginWebAuthnRegistration",
			Handler:    _WebAuthnService_BeginWebAuthnRegistration_Handler,
		},
		{
			MethodName: "FinishWebAuthnRegistration",
			Handler:    _WebAuthnService_FinishWebAuthnRegistration_Handler,
		},
		{
			MethodName: "BeginWebAuthnLogin",
			Handler:    _WebAuthnService_BeginWebAuthnLogin_Handler,
		},
		{
			MethodName: "FinishWebAuthnLogin",
			Handler:    _WebAuthnService_FinishWebAuthnLogin_Handler,
		},
		{
			MethodName: "AddWebAuthnCredential",
			Handler:    _WebAuthnService_AddWebAuthnCredential_Handler,
		},
		{
			MethodName: "ListWebAuthnCredentials",
			Handler:    _WebAuthnService_ListWebAuthnCredentials_Handler,
		},
		{
			MethodName: "DeleteWebAuthnCredential",
			Handler:    _WebAuthnService_DeleteWebAuthnCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "webauthn/webauthn_service.proto",
}
