// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: webauthn/webauthn_service.proto

package authapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebAuthnService_BeginRegistration_FullMethodName  = "/webauthn.WebAuthnService/BeginRegistration"
	WebAuthnService_FinishRegistration_FullMethodName = "/webauthn.WebAuthnService/FinishRegistration"
	WebAuthnService_BeginLogin_FullMethodName         = "/webauthn.WebAuthnService/BeginLogin"
	WebAuthnService_FinishLogin_FullMethodName        = "/webauthn.WebAuthnService/FinishLogin"
	WebAuthnService_AddCredential_FullMethodName      = "/webauthn.WebAuthnService/AddCredential"
	WebAuthnService_ListCredentials_FullMethodName    = "/webauthn.WebAuthnService/ListCredentials"
	WebAuthnService_DeleteCredential_FullMethodName   = "/webauthn.WebAuthnService/DeleteCredential"
)

// WebAuthnServiceClient is the client API for WebAuthnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WebAuthnService handles WebAuthn/Passkey identity verification
type WebAuthnServiceClient interface {
	// BeginRegistration starts WebAuthn registration (returns challenge)
	BeginRegistration(ctx context.Context, in *BeginRegistrationRequest, opts ...grpc.CallOption) (*BeginRegistrationResponse, error)
	// FinishRegistration completes registration and creates principal
	FinishRegistration(ctx context.Context, in *FinishRegistrationRequest, opts ...grpc.CallOption) (*FinishRegistrationResponse, error)
	// BeginLogin starts WebAuthn authentication (returns challenge)
	BeginLogin(ctx context.Context, in *BeginLoginRequest, opts ...grpc.CallOption) (*BeginLoginResponse, error)
	// FinishLogin completes authentication and returns access token
	FinishLogin(ctx context.Context, in *FinishLoginRequest, opts ...grpc.CallOption) (*FinishLoginResponse, error)
	// Add additional WebAuthn credential to authenticated principal's account
	AddCredential(ctx context.Context, in *AddCredentialRequest, opts ...grpc.CallOption) (*AddCredentialResponse, error)
	// List all WebAuthn credentials for authenticated principal
	ListCredentials(ctx context.Context, in *ListCredentialsRequest, opts ...grpc.CallOption) (*ListCredentialsResponse, error)
	// Delete a specific WebAuthn credential (revoke compromised authenticator)
	DeleteCredential(ctx context.Context, in *DeleteCredentialRequest, opts ...grpc.CallOption) (*DeleteCredentialResponse, error)
}

type webAuthnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebAuthnServiceClient(cc grpc.ClientConnInterface) WebAuthnServiceClient {
	return &webAuthnServiceClient{cc}
}

func (c *webAuthnServiceClient) BeginRegistration(ctx context.Context, in *BeginRegistrationRequest, opts ...grpc.CallOption) (*BeginRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginRegistrationResponse)
	err := c.cc.Invoke(ctx, WebAuthnService_BeginRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webAuthnServiceClient) FinishRegistration(ctx context.Context, in *FinishRegistrationRequest, opts ...grpc.CallOption) (*FinishRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishRegistrationResponse)
	err := c.cc.Invoke(ctx, WebAuthnService_FinishRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webAuthnServiceClient) BeginLogin(ctx context.Context, in *BeginLoginRequest, opts ...grpc.CallOption) (*BeginLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginLoginResponse)
	err := c.cc.Invoke(ctx, WebAuthnService_BeginLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webAuthnServiceClient) FinishLogin(ctx context.Context, in *FinishLoginRequest, opts ...grpc.CallOption) (*FinishLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishLoginResponse)
	err := c.cc.Invoke(ctx, WebAuthnService_FinishLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webAuthnServiceClient) AddCredential(ctx context.Context, in *AddCredentialRequest, opts ...grpc.CallOption) (*AddCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCredentialResponse)
	err := c.cc.Invoke(ctx, WebAuthnService_AddCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webAuthnServiceClient) ListCredentials(ctx context.Context, in *ListCredentialsRequest, opts ...grpc.CallOption) (*ListCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCredentialsResponse)
	err := c.cc.Invoke(ctx, WebAuthnService_ListCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webAuthnServiceClient) DeleteCredential(ctx context.Context, in *DeleteCredentialRequest, opts ...grpc.CallOption) (*DeleteCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCredentialResponse)
	err := c.cc.Invoke(ctx, WebAuthnService_DeleteCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebAuthnServiceServer is the server API for WebAuthnService service.
// All implementations must embed UnimplementedWebAuthnServiceServer
// for forward compatibility.
//
// WebAuthnService handles WebAuthn/Passkey identity verification
type WebAuthnServiceServer interface {
	// BeginRegistration starts WebAuthn registration (returns challenge)
	BeginRegistration(context.Context, *BeginRegistrationRequest) (*BeginRegistrationResponse, error)
	// FinishRegistration completes registration and creates principal
	FinishRegistration(context.Context, *FinishRegistrationRequest) (*FinishRegistrationResponse, error)
	// BeginLogin starts WebAuthn authentication (returns challenge)
	BeginLogin(context.Context, *BeginLoginRequest) (*BeginLoginResponse, error)
	// FinishLogin completes authentication and returns access token
	FinishLogin(context.Context, *FinishLoginRequest) (*FinishLoginResponse, error)
	// Add additional WebAuthn credential to authenticated principal's account
	AddCredential(context.Context, *AddCredentialRequest) (*AddCredentialResponse, error)
	// List all WebAuthn credentials for authenticated principal
	ListCredentials(context.Context, *ListCredentialsRequest) (*ListCredentialsResponse, error)
	// Delete a specific WebAuthn credential (revoke compromised authenticator)
	DeleteCredential(context.Context, *DeleteCredentialRequest) (*DeleteCredentialResponse, error)
	mustEmbedUnimplementedWebAuthnServiceServer()
}

// UnimplementedWebAuthnServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebAuthnServiceServer struct{}

func (UnimplementedWebAuthnServiceServer) BeginRegistration(context.Context, *BeginRegistrationRequest) (*BeginRegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginRegistration not implemented")
}
func (UnimplementedWebAuthnServiceServer) FinishRegistration(context.Context, *FinishRegistrationRequest) (*FinishRegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinishRegistration not implemented")
}
func (UnimplementedWebAuthnServiceServer) BeginLogin(context.Context, *BeginLoginRequest) (*BeginLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginLogin not implemented")
}
func (UnimplementedWebAuthnServiceServer) FinishLogin(context.Context, *FinishLoginRequest) (*FinishLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinishLogin not implemented")
}
func (UnimplementedWebAuthnServiceServer) AddCredential(context.Context, *AddCredentialRequest) (*AddCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCredential not implemented")
}
func (UnimplementedWebAuthnServiceServer) ListCredentials(context.Context, *ListCredentialsRequest) (*ListCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCredentials not implemented")
}
func (UnimplementedWebAuthnServiceServer) DeleteCredential(context.Context, *DeleteCredentialRequest) (*DeleteCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCredential not implemented")
}
func (UnimplementedWebAuthnServiceServer) mustEmbedUnimplementedWebAuthnServiceServer() {}
func (UnimplementedWebAuthnServiceServer) testEmbeddedByValue()                         {}

// UnsafeWebAuthnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebAuthnServiceServer will
// result in compilation errors.
type UnsafeWebAuthnServiceServer interface {
	mustEmbedUnimplementedWebAuthnServiceServer()
}

func RegisterWebAuthnServiceServer(s grpc.ServiceRegistrar, srv WebAuthnServiceServer) {
	// If the following call panics, it indicates UnimplementedWebAuthnServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebAuthnService_ServiceDesc, srv)
}

func _WebAuthnService_BeginRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebAuthnServiceServer).BeginRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebAuthnService_BeginRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebAuthnServiceServer).BeginRegistration(ctx, req.(*BeginRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebAuthnService_FinishRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebAuthnServiceServer).FinishRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebAuthnService_FinishRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebAuthnServiceServer).FinishRegistration(ctx, req.(*FinishRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebAuthnService_BeginLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebAuthnServiceServer).BeginLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebAuthnService_BeginLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebAuthnServiceServer).BeginLogin(ctx, req.(*BeginLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebAuthnService_FinishLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebAuthnServiceServer).FinishLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebAuthnService_FinishLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebAuthnServiceServer).FinishLogin(ctx, req.(*FinishLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebAuthnService_AddCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebAuthnServiceServer).AddCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebAuthnService_AddCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebAuthnServiceServer).AddCredential(ctx, req.(*AddCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebAuthnService_ListCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebAuthnServiceServer).ListCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebAuthnService_ListCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebAuthnServiceServer).ListCredentials(ctx, req.(*ListCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebAuthnService_DeleteCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebAuthnServiceServer).DeleteCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebAuthnService_DeleteCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebAuthnServiceServer).DeleteCredential(ctx, req.(*DeleteCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebAuthnService_ServiceDesc is the grpc.ServiceDesc for WebAuthnService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebAuthnService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webauthn.WebAuthnService",
	HandlerType: (*WebAuthnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeginRegistration",
			Handler:    _WebAuthnService_BeginRegistration_Handler,
		},
		{
			MethodName: "FinishRegistration",
			Handler:    _WebAuthnService_FinishRegistration_Handler,
		},
		{
			MethodName: "BeginLogin",
			Handler:    _WebAuthnService_BeginLogin_Handler,
		},
		{
			MethodName: "FinishLogin",
			Handler:    _WebAuthnService_FinishLogin_Handler,
		},
		{
			MethodName: "AddCredential",
			Handler:    _WebAuthnService_AddCredential_Handler,
		},
		{
			MethodName: "ListCredentials",
			Handler:    _WebAuthnService_ListCredentials_Handler,
		},
		{
			MethodName: "DeleteCredential",
			Handler:    _WebAuthnService_DeleteCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "webauthn/webauthn_service.proto",
}
