// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: webauthn/webauthn_service.proto

package authapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CredentialFlags contains authenticator flags
type CredentialFlags struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User present (UP) - user was present during authentication
	UserPresent bool `protobuf:"varint,1,opt,name=user_present,json=userPresent,proto3" json:"user_present,omitempty"`
	// User verified (UV) - user was verified (biometric, PIN, etc.)
	UserVerified bool `protobuf:"varint,2,opt,name=user_verified,json=userVerified,proto3" json:"user_verified,omitempty"`
	// Backup eligible (BE) - credential can be backed up
	BackupEligible bool `protobuf:"varint,3,opt,name=backup_eligible,json=backupEligible,proto3" json:"backup_eligible,omitempty"`
	// Backup state (BS) - credential is currently backed up
	BackupState   bool `protobuf:"varint,4,opt,name=backup_state,json=backupState,proto3" json:"backup_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialFlags) Reset() {
	*x = CredentialFlags{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialFlags) ProtoMessage() {}

func (x *CredentialFlags) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialFlags.ProtoReflect.Descriptor instead.
func (*CredentialFlags) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{0}
}

func (x *CredentialFlags) GetUserPresent() bool {
	if x != nil {
		return x.UserPresent
	}
	return false
}

func (x *CredentialFlags) GetUserVerified() bool {
	if x != nil {
		return x.UserVerified
	}
	return false
}

func (x *CredentialFlags) GetBackupEligible() bool {
	if x != nil {
		return x.BackupEligible
	}
	return false
}

func (x *CredentialFlags) GetBackupState() bool {
	if x != nil {
		return x.BackupState
	}
	return false
}

// Authenticator information for a credential
type Authenticator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AAGUID - Authenticator Attestation GUID
	Aaguid []byte `protobuf:"bytes,1,opt,name=aaguid,proto3" json:"aaguid,omitempty"`
	// Sign counter for replay attack detection
	SignCount int64 `protobuf:"varint,2,opt,name=sign_count,json=signCount,proto3" json:"sign_count,omitempty"`
	// Clone warning - if true, possible cloned authenticator detected
	CloneWarning bool `protobuf:"varint,3,opt,name=clone_warning,json=cloneWarning,proto3" json:"clone_warning,omitempty"`
	// Attachment type (platform, cross-platform)
	Attachment    string `protobuf:"bytes,4,opt,name=attachment,proto3" json:"attachment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authenticator) Reset() {
	*x = Authenticator{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authenticator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authenticator) ProtoMessage() {}

func (x *Authenticator) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authenticator.ProtoReflect.Descriptor instead.
func (*Authenticator) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{1}
}

func (x *Authenticator) GetAaguid() []byte {
	if x != nil {
		return x.Aaguid
	}
	return nil
}

func (x *Authenticator) GetSignCount() int64 {
	if x != nil {
		return x.SignCount
	}
	return 0
}

func (x *Authenticator) GetCloneWarning() bool {
	if x != nil {
		return x.CloneWarning
	}
	return false
}

func (x *Authenticator) GetAttachment() string {
	if x != nil {
		return x.Attachment
	}
	return ""
}

// CredentialAttestation contains attestation data from registration
type CredentialAttestation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attestation object - CBOR encoded attestation data
	Object []byte `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// Client data JSON from registration
	ClientDataJson []byte `protobuf:"bytes,2,opt,name=client_data_json,json=clientDataJson,proto3" json:"client_data_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CredentialAttestation) Reset() {
	*x = CredentialAttestation{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialAttestation) ProtoMessage() {}

func (x *CredentialAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialAttestation.ProtoReflect.Descriptor instead.
func (*CredentialAttestation) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{2}
}

func (x *CredentialAttestation) GetObject() []byte {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *CredentialAttestation) GetClientDataJson() []byte {
	if x != nil {
		return x.ClientDataJson
	}
	return nil
}

// WebAuthn credential for passkey authentication
type WebAuthnCredential struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Credential ID - unique identifier for this credential
	CredentialId string `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	// Public key for signature verification
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Attestation type (e.g., "packed", "fido-u2f", "none")
	AttestationType string `protobuf:"bytes,3,opt,name=attestation_type,json=attestationType,proto3" json:"attestation_type,omitempty"`
	// Transport methods supported by this authenticator
	// Values from WebAuthn spec: "usb", "nfc", "ble", "internal", "hybrid", "smart-card"
	// Forward-compatible with future transport types
	Transport []string `protobuf:"bytes,4,rep,name=transport,proto3" json:"transport,omitempty"`
	// Authenticator flags
	Flags *CredentialFlags `protobuf:"bytes,5,opt,name=flags,proto3" json:"flags,omitempty"`
	// Authenticator information
	Authenticator *Authenticator `protobuf:"bytes,6,opt,name=authenticator,proto3" json:"authenticator,omitempty"`
	// Attestation data (can be omitted if attestation_type is "none")
	Attestation *CredentialAttestation `protobuf:"bytes,7,opt,name=attestation,proto3" json:"attestation,omitempty"`
	// Human-readable name for this credential (e.g., "YubiKey 5", "iPhone 15")
	Name string `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	// When this credential was created
	CreatedAt int64 `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last time this credential was used for authentication
	LastUsedAt    int64 `protobuf:"varint,10,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebAuthnCredential) Reset() {
	*x = WebAuthnCredential{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAuthnCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAuthnCredential) ProtoMessage() {}

func (x *WebAuthnCredential) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAuthnCredential.ProtoReflect.Descriptor instead.
func (*WebAuthnCredential) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{3}
}

func (x *WebAuthnCredential) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *WebAuthnCredential) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *WebAuthnCredential) GetAttestationType() string {
	if x != nil {
		return x.AttestationType
	}
	return ""
}

func (x *WebAuthnCredential) GetTransport() []string {
	if x != nil {
		return x.Transport
	}
	return nil
}

func (x *WebAuthnCredential) GetFlags() *CredentialFlags {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *WebAuthnCredential) GetAuthenticator() *Authenticator {
	if x != nil {
		return x.Authenticator
	}
	return nil
}

func (x *WebAuthnCredential) GetAttestation() *CredentialAttestation {
	if x != nil {
		return x.Attestation
	}
	return nil
}

func (x *WebAuthnCredential) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WebAuthnCredential) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *WebAuthnCredential) GetLastUsedAt() int64 {
	if x != nil {
		return x.LastUsedAt
	}
	return 0
}

// Begin WebAuthn registration
type BeginRegistrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional user name (e.g., username or email)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional display name for UI presentation
	DisplayName   string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // NOTE: user.id is always server-generated from principal ID, never client-provided
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginRegistrationRequest) Reset() {
	*x = BeginRegistrationRequest{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRegistrationRequest) ProtoMessage() {}

func (x *BeginRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRegistrationRequest.ProtoReflect.Descriptor instead.
func (*BeginRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{4}
}

func (x *BeginRegistrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BeginRegistrationRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type BeginRegistrationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Challenge options to send to browser (JSON-encoded CredentialCreationOptions)
	Options []byte `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	// Session token for completing registration (stateless session via JWT)
	SessionToken  string `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginRegistrationResponse) Reset() {
	*x = BeginRegistrationResponse{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRegistrationResponse) ProtoMessage() {}

func (x *BeginRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRegistrationResponse.ProtoReflect.Descriptor instead.
func (*BeginRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{5}
}

func (x *BeginRegistrationResponse) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *BeginRegistrationResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

// Finish WebAuthn registration
type FinishRegistrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WebAuthn credential data from browser
	CredentialData []byte `protobuf:"bytes,1,opt,name=credential_data,json=credentialData,proto3" json:"credential_data,omitempty"`
	// Session token from BeginRegistration
	SessionToken  string `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishRegistrationRequest) Reset() {
	*x = FinishRegistrationRequest{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRegistrationRequest) ProtoMessage() {}

func (x *FinishRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishRegistrationRequest.ProtoReflect.Descriptor instead.
func (*FinishRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{6}
}

func (x *FinishRegistrationRequest) GetCredentialData() []byte {
	if x != nil {
		return x.CredentialData
	}
	return nil
}

func (x *FinishRegistrationRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type FinishRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        *Claims                `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishRegistrationResponse) Reset() {
	*x = FinishRegistrationResponse{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRegistrationResponse) ProtoMessage() {}

func (x *FinishRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishRegistrationResponse.ProtoReflect.Descriptor instead.
func (*FinishRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{7}
}

func (x *FinishRegistrationResponse) GetClaims() *Claims {
	if x != nil {
		return x.Claims
	}
	return nil
}

// Begin WebAuthn login
type BeginLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginLoginRequest) Reset() {
	*x = BeginLoginRequest{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginLoginRequest) ProtoMessage() {}

func (x *BeginLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginLoginRequest.ProtoReflect.Descriptor instead.
func (*BeginLoginRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{8}
}

type BeginLoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Challenge options to send to browser (JSON-encoded CredentialRequestOptions)
	Options []byte `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	// Session token for completing login
	SessionToken  string `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginLoginResponse) Reset() {
	*x = BeginLoginResponse{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginLoginResponse) ProtoMessage() {}

func (x *BeginLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginLoginResponse.ProtoReflect.Descriptor instead.
func (*BeginLoginResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{9}
}

func (x *BeginLoginResponse) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *BeginLoginResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

// Finish WebAuthn login
type FinishLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Assertion data from browser
	AssertionData []byte `protobuf:"bytes,1,opt,name=assertion_data,json=assertionData,proto3" json:"assertion_data,omitempty"`
	// Session token from BeginLogin
	SessionToken  string `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishLoginRequest) Reset() {
	*x = FinishLoginRequest{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishLoginRequest) ProtoMessage() {}

func (x *FinishLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishLoginRequest.ProtoReflect.Descriptor instead.
func (*FinishLoginRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{10}
}

func (x *FinishLoginRequest) GetAssertionData() []byte {
	if x != nil {
		return x.AssertionData
	}
	return nil
}

func (x *FinishLoginRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type FinishLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        *Claims                `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishLoginResponse) Reset() {
	*x = FinishLoginResponse{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishLoginResponse) ProtoMessage() {}

func (x *FinishLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishLoginResponse.ProtoReflect.Descriptor instead.
func (*FinishLoginResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{11}
}

func (x *FinishLoginResponse) GetClaims() *Claims {
	if x != nil {
		return x.Claims
	}
	return nil
}

// Add credential request
type AddCredentialRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WebAuthn credential data from browser (contains credential_id, public_key, etc.)
	CredentialData []byte `protobuf:"bytes,1,opt,name=credential_data,json=credentialData,proto3" json:"credential_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddCredentialRequest) Reset() {
	*x = AddCredentialRequest{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCredentialRequest) ProtoMessage() {}

func (x *AddCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCredentialRequest.ProtoReflect.Descriptor instead.
func (*AddCredentialRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{12}
}

func (x *AddCredentialRequest) GetCredentialData() []byte {
	if x != nil {
		return x.CredentialData
	}
	return nil
}

// Add credential response
type AddCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCredentialResponse) Reset() {
	*x = AddCredentialResponse{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCredentialResponse) ProtoMessage() {}

func (x *AddCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCredentialResponse.ProtoReflect.Descriptor instead.
func (*AddCredentialResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{13}
}

func (x *AddCredentialResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// List credentials request
type ListCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCredentialsRequest) Reset() {
	*x = ListCredentialsRequest{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCredentialsRequest) ProtoMessage() {}

func (x *ListCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCredentialsRequest.ProtoReflect.Descriptor instead.
func (*ListCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{14}
}

type ListCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []*WebAuthnCredential  `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCredentialsResponse) Reset() {
	*x = ListCredentialsResponse{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCredentialsResponse) ProtoMessage() {}

func (x *ListCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCredentialsResponse.ProtoReflect.Descriptor instead.
func (*ListCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListCredentialsResponse) GetCredentials() []*WebAuthnCredential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

// Delete credential request
type DeleteCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CredentialId  string                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCredentialRequest) Reset() {
	*x = DeleteCredentialRequest{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialRequest) ProtoMessage() {}

func (x *DeleteCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialRequest.ProtoReflect.Descriptor instead.
func (*DeleteCredentialRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteCredentialRequest) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

type DeleteCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCredentialResponse) Reset() {
	*x = DeleteCredentialResponse{}
	mi := &file_webauthn_webauthn_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialResponse) ProtoMessage() {}

func (x *DeleteCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_webauthn_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialResponse.ProtoReflect.Descriptor instead.
func (*DeleteCredentialResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_webauthn_service_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteCredentialResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_webauthn_webauthn_service_proto protoreflect.FileDescriptor

const file_webauthn_webauthn_service_proto_rawDesc = "" +
	"\n" +
	"\x1fwebauthn/webauthn_service.proto\x12\bwebauthn\x1a\x10jwt/claims.proto\"\xa5\x01\n" +
	"\x0fCredentialFlags\x12!\n" +
	"\fuser_present\x18\x01 \x01(\bR\vuserPresent\x12#\n" +
	"\ruser_verified\x18\x02 \x01(\bR\fuserVerified\x12'\n" +
	"\x0fbackup_eligible\x18\x03 \x01(\bR\x0ebackupEligible\x12!\n" +
	"\fbackup_state\x18\x04 \x01(\bR\vbackupState\"\x8b\x01\n" +
	"\rAuthenticator\x12\x16\n" +
	"\x06aaguid\x18\x01 \x01(\fR\x06aaguid\x12\x1d\n" +
	"\n" +
	"sign_count\x18\x02 \x01(\x03R\tsignCount\x12#\n" +
	"\rclone_warning\x18\x03 \x01(\bR\fcloneWarning\x12\x1e\n" +
	"\n" +
	"attachment\x18\x04 \x01(\tR\n" +
	"attachment\"Y\n" +
	"\x15CredentialAttestation\x12\x16\n" +
	"\x06object\x18\x01 \x01(\fR\x06object\x12(\n" +
	"\x10client_data_json\x18\x02 \x01(\fR\x0eclientDataJson\"\xa9\x03\n" +
	"\x12WebAuthnCredential\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\tR\fcredentialId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12)\n" +
	"\x10attestation_type\x18\x03 \x01(\tR\x0fattestationType\x12\x1c\n" +
	"\ttransport\x18\x04 \x03(\tR\ttransport\x12/\n" +
	"\x05flags\x18\x05 \x01(\v2\x19.webauthn.CredentialFlagsR\x05flags\x12=\n" +
	"\rauthenticator\x18\x06 \x01(\v2\x17.webauthn.AuthenticatorR\rauthenticator\x12A\n" +
	"\vattestation\x18\a \x01(\v2\x1f.webauthn.CredentialAttestationR\vattestation\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12 \n" +
	"\flast_used_at\x18\n" +
	" \x01(\x03R\n" +
	"lastUsedAt\"Q\n" +
	"\x18BeginRegistrationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"Z\n" +
	"\x19BeginRegistrationResponse\x12\x18\n" +
	"\aoptions\x18\x01 \x01(\fR\aoptions\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\"i\n" +
	"\x19FinishRegistrationRequest\x12'\n" +
	"\x0fcredential_data\x18\x01 \x01(\fR\x0ecredentialData\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\"A\n" +
	"\x1aFinishRegistrationResponse\x12#\n" +
	"\x06claims\x18\x01 \x01(\v2\v.jwt.ClaimsR\x06claims\"\x13\n" +
	"\x11BeginLoginRequest\"S\n" +
	"\x12BeginLoginResponse\x12\x18\n" +
	"\aoptions\x18\x01 \x01(\fR\aoptions\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\"`\n" +
	"\x12FinishLoginRequest\x12%\n" +
	"\x0eassertion_data\x18\x01 \x01(\fR\rassertionData\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\":\n" +
	"\x13FinishLoginResponse\x12#\n" +
	"\x06claims\x18\x01 \x01(\v2\v.jwt.ClaimsR\x06claims\"?\n" +
	"\x14AddCredentialRequest\x12'\n" +
	"\x0fcredential_data\x18\x01 \x01(\fR\x0ecredentialData\"1\n" +
	"\x15AddCredentialResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x18\n" +
	"\x16ListCredentialsRequest\"Y\n" +
	"\x17ListCredentialsResponse\x12>\n" +
	"\vcredentials\x18\x01 \x03(\v2\x1c.webauthn.WebAuthnCredentialR\vcredentials\">\n" +
	"\x17DeleteCredentialRequest\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\tR\fcredentialId\"4\n" +
	"\x18DeleteCredentialResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xea\x04\n" +
	"\x0fWebAuthnService\x12\\\n" +
	"\x11BeginRegistration\x12\".webauthn.BeginRegistrationRequest\x1a#.webauthn.BeginRegistrationResponse\x12_\n" +
	"\x12FinishRegistration\x12#.webauthn.FinishRegistrationRequest\x1a$.webauthn.FinishRegistrationResponse\x12G\n" +
	"\n" +
	"BeginLogin\x12\x1b.webauthn.BeginLoginRequest\x1a\x1c.webauthn.BeginLoginResponse\x12J\n" +
	"\vFinishLogin\x12\x1c.webauthn.FinishLoginRequest\x1a\x1d.webauthn.FinishLoginResponse\x12P\n" +
	"\rAddCredential\x12\x1e.webauthn.AddCredentialRequest\x1a\x1f.webauthn.AddCredentialResponse\x12V\n" +
	"\x0fListCredentials\x12 .webauthn.ListCredentialsRequest\x1a!.webauthn.ListCredentialsResponse\x12Y\n" +
	"\x10DeleteCredential\x12!.webauthn.DeleteCredentialRequest\x1a\".webauthn.DeleteCredentialResponseB2Z0git.sonicoriginal.software/grpc-auth-api;authapib\x06proto3"

var (
	file_webauthn_webauthn_service_proto_rawDescOnce sync.Once
	file_webauthn_webauthn_service_proto_rawDescData []byte
)

func file_webauthn_webauthn_service_proto_rawDescGZIP() []byte {
	file_webauthn_webauthn_service_proto_rawDescOnce.Do(func() {
		file_webauthn_webauthn_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webauthn_webauthn_service_proto_rawDesc), len(file_webauthn_webauthn_service_proto_rawDesc)))
	})
	return file_webauthn_webauthn_service_proto_rawDescData
}

var file_webauthn_webauthn_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_webauthn_webauthn_service_proto_goTypes = []any{
	(*CredentialFlags)(nil),            // 0: webauthn.CredentialFlags
	(*Authenticator)(nil),              // 1: webauthn.Authenticator
	(*CredentialAttestation)(nil),      // 2: webauthn.CredentialAttestation
	(*WebAuthnCredential)(nil),         // 3: webauthn.WebAuthnCredential
	(*BeginRegistrationRequest)(nil),   // 4: webauthn.BeginRegistrationRequest
	(*BeginRegistrationResponse)(nil),  // 5: webauthn.BeginRegistrationResponse
	(*FinishRegistrationRequest)(nil),  // 6: webauthn.FinishRegistrationRequest
	(*FinishRegistrationResponse)(nil), // 7: webauthn.FinishRegistrationResponse
	(*BeginLoginRequest)(nil),          // 8: webauthn.BeginLoginRequest
	(*BeginLoginResponse)(nil),         // 9: webauthn.BeginLoginResponse
	(*FinishLoginRequest)(nil),         // 10: webauthn.FinishLoginRequest
	(*FinishLoginResponse)(nil),        // 11: webauthn.FinishLoginResponse
	(*AddCredentialRequest)(nil),       // 12: webauthn.AddCredentialRequest
	(*AddCredentialResponse)(nil),      // 13: webauthn.AddCredentialResponse
	(*ListCredentialsRequest)(nil),     // 14: webauthn.ListCredentialsRequest
	(*ListCredentialsResponse)(nil),    // 15: webauthn.ListCredentialsResponse
	(*DeleteCredentialRequest)(nil),    // 16: webauthn.DeleteCredentialRequest
	(*DeleteCredentialResponse)(nil),   // 17: webauthn.DeleteCredentialResponse
	(*Claims)(nil),                     // 18: jwt.Claims
}
var file_webauthn_webauthn_service_proto_depIdxs = []int32{
	0,  // 0: webauthn.WebAuthnCredential.flags:type_name -> webauthn.CredentialFlags
	1,  // 1: webauthn.WebAuthnCredential.authenticator:type_name -> webauthn.Authenticator
	2,  // 2: webauthn.WebAuthnCredential.attestation:type_name -> webauthn.CredentialAttestation
	18, // 3: webauthn.FinishRegistrationResponse.claims:type_name -> jwt.Claims
	18, // 4: webauthn.FinishLoginResponse.claims:type_name -> jwt.Claims
	3,  // 5: webauthn.ListCredentialsResponse.credentials:type_name -> webauthn.WebAuthnCredential
	4,  // 6: webauthn.WebAuthnService.BeginRegistration:input_type -> webauthn.BeginRegistrationRequest
	6,  // 7: webauthn.WebAuthnService.FinishRegistration:input_type -> webauthn.FinishRegistrationRequest
	8,  // 8: webauthn.WebAuthnService.BeginLogin:input_type -> webauthn.BeginLoginRequest
	10, // 9: webauthn.WebAuthnService.FinishLogin:input_type -> webauthn.FinishLoginRequest
	12, // 10: webauthn.WebAuthnService.AddCredential:input_type -> webauthn.AddCredentialRequest
	14, // 11: webauthn.WebAuthnService.ListCredentials:input_type -> webauthn.ListCredentialsRequest
	16, // 12: webauthn.WebAuthnService.DeleteCredential:input_type -> webauthn.DeleteCredentialRequest
	5,  // 13: webauthn.WebAuthnService.BeginRegistration:output_type -> webauthn.BeginRegistrationResponse
	7,  // 14: webauthn.WebAuthnService.FinishRegistration:output_type -> webauthn.FinishRegistrationResponse
	9,  // 15: webauthn.WebAuthnService.BeginLogin:output_type -> webauthn.BeginLoginResponse
	11, // 16: webauthn.WebAuthnService.FinishLogin:output_type -> webauthn.FinishLoginResponse
	13, // 17: webauthn.WebAuthnService.AddCredential:output_type -> webauthn.AddCredentialResponse
	15, // 18: webauthn.WebAuthnService.ListCredentials:output_type -> webauthn.ListCredentialsResponse
	17, // 19: webauthn.WebAuthnService.DeleteCredential:output_type -> webauthn.DeleteCredentialResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_webauthn_webauthn_service_proto_init() }
func file_webauthn_webauthn_service_proto_init() {
	if File_webauthn_webauthn_service_proto != nil {
		return
	}
	file_jwt_claims_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webauthn_webauthn_service_proto_rawDesc), len(file_webauthn_webauthn_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webauthn_webauthn_service_proto_goTypes,
		DependencyIndexes: file_webauthn_webauthn_service_proto_depIdxs,
		MessageInfos:      file_webauthn_webauthn_service_proto_msgTypes,
	}.Build()
	File_webauthn_webauthn_service_proto = out.File
	file_webauthn_webauthn_service_proto_goTypes = nil
	file_webauthn_webauthn_service_proto_depIdxs = nil
}
