// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: webauthn/authenticator.proto

package webauthn

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticatorAttachment int32

const (
	AuthenticatorAttachment_AUTHENTICATOR_ATTACHMENT_UNSPECIFIED    AuthenticatorAttachment = 0
	AuthenticatorAttachment_AUTHENTICATOR_ATTACHMENT_PLATFORM       AuthenticatorAttachment = 1
	AuthenticatorAttachment_AUTHENTICATOR_ATTACHMENT_CROSS_PLATFORM AuthenticatorAttachment = 2
)

// Enum value maps for AuthenticatorAttachment.
var (
	AuthenticatorAttachment_name = map[int32]string{
		0: "AUTHENTICATOR_ATTACHMENT_UNSPECIFIED",
		1: "AUTHENTICATOR_ATTACHMENT_PLATFORM",
		2: "AUTHENTICATOR_ATTACHMENT_CROSS_PLATFORM",
	}
	AuthenticatorAttachment_value = map[string]int32{
		"AUTHENTICATOR_ATTACHMENT_UNSPECIFIED":    0,
		"AUTHENTICATOR_ATTACHMENT_PLATFORM":       1,
		"AUTHENTICATOR_ATTACHMENT_CROSS_PLATFORM": 2,
	}
)

func (x AuthenticatorAttachment) Enum() *AuthenticatorAttachment {
	p := new(AuthenticatorAttachment)
	*p = x
	return p
}

func (x AuthenticatorAttachment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthenticatorAttachment) Descriptor() protoreflect.EnumDescriptor {
	return file_webauthn_authenticator_proto_enumTypes[0].Descriptor()
}

func (AuthenticatorAttachment) Type() protoreflect.EnumType {
	return &file_webauthn_authenticator_proto_enumTypes[0]
}

func (x AuthenticatorAttachment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthenticatorAttachment.Descriptor instead.
func (AuthenticatorAttachment) EnumDescriptor() ([]byte, []int) {
	return file_webauthn_authenticator_proto_rawDescGZIP(), []int{0}
}

type ResidentKeyRequirement int32

const (
	ResidentKeyRequirement_RESIDENT_KEY_REQUIREMENT_UNSPECIFIED ResidentKeyRequirement = 0
	ResidentKeyRequirement_RESIDENT_KEY_REQUIREMENT_DISCOURAGED ResidentKeyRequirement = 1
	ResidentKeyRequirement_RESIDENT_KEY_REQUIREMENT_PREFERRED   ResidentKeyRequirement = 2
	ResidentKeyRequirement_RESIDENT_KEY_REQUIREMENT_REQUIRED    ResidentKeyRequirement = 3
)

// Enum value maps for ResidentKeyRequirement.
var (
	ResidentKeyRequirement_name = map[int32]string{
		0: "RESIDENT_KEY_REQUIREMENT_UNSPECIFIED",
		1: "RESIDENT_KEY_REQUIREMENT_DISCOURAGED",
		2: "RESIDENT_KEY_REQUIREMENT_PREFERRED",
		3: "RESIDENT_KEY_REQUIREMENT_REQUIRED",
	}
	ResidentKeyRequirement_value = map[string]int32{
		"RESIDENT_KEY_REQUIREMENT_UNSPECIFIED": 0,
		"RESIDENT_KEY_REQUIREMENT_DISCOURAGED": 1,
		"RESIDENT_KEY_REQUIREMENT_PREFERRED":   2,
		"RESIDENT_KEY_REQUIREMENT_REQUIRED":    3,
	}
)

func (x ResidentKeyRequirement) Enum() *ResidentKeyRequirement {
	p := new(ResidentKeyRequirement)
	*p = x
	return p
}

func (x ResidentKeyRequirement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResidentKeyRequirement) Descriptor() protoreflect.EnumDescriptor {
	return file_webauthn_authenticator_proto_enumTypes[1].Descriptor()
}

func (ResidentKeyRequirement) Type() protoreflect.EnumType {
	return &file_webauthn_authenticator_proto_enumTypes[1]
}

func (x ResidentKeyRequirement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResidentKeyRequirement.Descriptor instead.
func (ResidentKeyRequirement) EnumDescriptor() ([]byte, []int) {
	return file_webauthn_authenticator_proto_rawDescGZIP(), []int{1}
}

type UserVerificationRequirement int32

const (
	UserVerificationRequirement_USER_VERIFICATION_REQUIREMENT_UNSPECIFIED UserVerificationRequirement = 0
	UserVerificationRequirement_USER_VERIFICATION_REQUIREMENT_DISCOURAGED UserVerificationRequirement = 1
	UserVerificationRequirement_USER_VERIFICATION_REQUIREMENT_PREFERRED   UserVerificationRequirement = 2
	UserVerificationRequirement_USER_VERIFICATION_REQUIREMENT_REQUIRED    UserVerificationRequirement = 3
)

// Enum value maps for UserVerificationRequirement.
var (
	UserVerificationRequirement_name = map[int32]string{
		0: "USER_VERIFICATION_REQUIREMENT_UNSPECIFIED",
		1: "USER_VERIFICATION_REQUIREMENT_DISCOURAGED",
		2: "USER_VERIFICATION_REQUIREMENT_PREFERRED",
		3: "USER_VERIFICATION_REQUIREMENT_REQUIRED",
	}
	UserVerificationRequirement_value = map[string]int32{
		"USER_VERIFICATION_REQUIREMENT_UNSPECIFIED": 0,
		"USER_VERIFICATION_REQUIREMENT_DISCOURAGED": 1,
		"USER_VERIFICATION_REQUIREMENT_PREFERRED":   2,
		"USER_VERIFICATION_REQUIREMENT_REQUIRED":    3,
	}
)

func (x UserVerificationRequirement) Enum() *UserVerificationRequirement {
	p := new(UserVerificationRequirement)
	*p = x
	return p
}

func (x UserVerificationRequirement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserVerificationRequirement) Descriptor() protoreflect.EnumDescriptor {
	return file_webauthn_authenticator_proto_enumTypes[2].Descriptor()
}

func (UserVerificationRequirement) Type() protoreflect.EnumType {
	return &file_webauthn_authenticator_proto_enumTypes[2]
}

func (x UserVerificationRequirement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserVerificationRequirement.Descriptor instead.
func (UserVerificationRequirement) EnumDescriptor() ([]byte, []int) {
	return file_webauthn_authenticator_proto_rawDescGZIP(), []int{2}
}

type AuthenticatorSelectionCriteria struct {
	state                   protoimpl.MessageState      `protogen:"open.v1"`
	AuthenticatorAttachment AuthenticatorAttachment     `protobuf:"varint,1,opt,name=authenticator_attachment,json=authenticatorAttachment,proto3,enum=webauthn.AuthenticatorAttachment" json:"authenticator_attachment,omitempty"`
	ResidentKey             ResidentKeyRequirement      `protobuf:"varint,2,opt,name=resident_key,json=residentKey,proto3,enum=webauthn.ResidentKeyRequirement" json:"resident_key,omitempty"`
	RequireResidentKey      bool                        `protobuf:"varint,3,opt,name=require_resident_key,json=requireResidentKey,proto3" json:"require_resident_key,omitempty"`
	UserVerification        UserVerificationRequirement `protobuf:"varint,4,opt,name=user_verification,json=userVerification,proto3,enum=webauthn.UserVerificationRequirement" json:"user_verification,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AuthenticatorSelectionCriteria) Reset() {
	*x = AuthenticatorSelectionCriteria{}
	mi := &file_webauthn_authenticator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticatorSelectionCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticatorSelectionCriteria) ProtoMessage() {}

func (x *AuthenticatorSelectionCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_authenticator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticatorSelectionCriteria.ProtoReflect.Descriptor instead.
func (*AuthenticatorSelectionCriteria) Descriptor() ([]byte, []int) {
	return file_webauthn_authenticator_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticatorSelectionCriteria) GetAuthenticatorAttachment() AuthenticatorAttachment {
	if x != nil {
		return x.AuthenticatorAttachment
	}
	return AuthenticatorAttachment_AUTHENTICATOR_ATTACHMENT_UNSPECIFIED
}

func (x *AuthenticatorSelectionCriteria) GetResidentKey() ResidentKeyRequirement {
	if x != nil {
		return x.ResidentKey
	}
	return ResidentKeyRequirement_RESIDENT_KEY_REQUIREMENT_UNSPECIFIED
}

func (x *AuthenticatorSelectionCriteria) GetRequireResidentKey() bool {
	if x != nil {
		return x.RequireResidentKey
	}
	return false
}

func (x *AuthenticatorSelectionCriteria) GetUserVerification() UserVerificationRequirement {
	if x != nil {
		return x.UserVerification
	}
	return UserVerificationRequirement_USER_VERIFICATION_REQUIREMENT_UNSPECIFIED
}

// Authenticator response to the registration ceremony
type AuthenticatorAttestationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClientDataJson    []byte                 `protobuf:"bytes,1,opt,name=client_data_json,json=clientDataJson,proto3" json:"client_data_json,omitempty"`
	AttestationObject []byte                 `protobuf:"bytes,2,opt,name=attestation_object,json=attestationObject,proto3" json:"attestation_object,omitempty"`
	Transports        []string               `protobuf:"bytes,3,rep,name=transports,proto3" json:"transports,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthenticatorAttestationResponse) Reset() {
	*x = AuthenticatorAttestationResponse{}
	mi := &file_webauthn_authenticator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticatorAttestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticatorAttestationResponse) ProtoMessage() {}

func (x *AuthenticatorAttestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_authenticator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticatorAttestationResponse.ProtoReflect.Descriptor instead.
func (*AuthenticatorAttestationResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_authenticator_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticatorAttestationResponse) GetClientDataJson() []byte {
	if x != nil {
		return x.ClientDataJson
	}
	return nil
}

func (x *AuthenticatorAttestationResponse) GetAttestationObject() []byte {
	if x != nil {
		return x.AttestationObject
	}
	return nil
}

func (x *AuthenticatorAttestationResponse) GetTransports() []string {
	if x != nil {
		return x.Transports
	}
	return nil
}

// Authenticator response to the login ceremony
type AuthenticatorAssertionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClientDataJson    []byte                 `protobuf:"bytes,1,opt,name=client_data_json,json=clientDataJson,proto3" json:"client_data_json,omitempty"`
	AuthenticatorData []byte                 `protobuf:"bytes,2,opt,name=authenticator_data,json=authenticatorData,proto3" json:"authenticator_data,omitempty"`
	Signature         []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	UserHandle        []byte                 `protobuf:"bytes,4,opt,name=user_handle,json=userHandle,proto3" json:"user_handle,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthenticatorAssertionResponse) Reset() {
	*x = AuthenticatorAssertionResponse{}
	mi := &file_webauthn_authenticator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticatorAssertionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticatorAssertionResponse) ProtoMessage() {}

func (x *AuthenticatorAssertionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_authenticator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticatorAssertionResponse.ProtoReflect.Descriptor instead.
func (*AuthenticatorAssertionResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_authenticator_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticatorAssertionResponse) GetClientDataJson() []byte {
	if x != nil {
		return x.ClientDataJson
	}
	return nil
}

func (x *AuthenticatorAssertionResponse) GetAuthenticatorData() []byte {
	if x != nil {
		return x.AuthenticatorData
	}
	return nil
}

func (x *AuthenticatorAssertionResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AuthenticatorAssertionResponse) GetUserHandle() []byte {
	if x != nil {
		return x.UserHandle
	}
	return nil
}

var File_webauthn_authenticator_proto protoreflect.FileDescriptor

const file_webauthn_authenticator_proto_rawDesc = "" +
	"\n" +
	"\x1cwebauthn/authenticator.proto\x12\bwebauthn\"\xc9\x02\n" +
	"\x1eAuthenticatorSelectionCriteria\x12\\\n" +
	"\x18authenticator_attachment\x18\x01 \x01(\x0e2!.webauthn.AuthenticatorAttachmentR\x17authenticatorAttachment\x12C\n" +
	"\fresident_key\x18\x02 \x01(\x0e2 .webauthn.ResidentKeyRequirementR\vresidentKey\x120\n" +
	"\x14require_resident_key\x18\x03 \x01(\bR\x12requireResidentKey\x12R\n" +
	"\x11user_verification\x18\x04 \x01(\x0e2%.webauthn.UserVerificationRequirementR\x10userVerification\"\x9b\x01\n" +
	" AuthenticatorAttestationResponse\x12(\n" +
	"\x10client_data_json\x18\x01 \x01(\fR\x0eclientDataJson\x12-\n" +
	"\x12attestation_object\x18\x02 \x01(\fR\x11attestationObject\x12\x1e\n" +
	"\n" +
	"transports\x18\x03 \x03(\tR\n" +
	"transports\"\xb8\x01\n" +
	"\x1eAuthenticatorAssertionResponse\x12(\n" +
	"\x10client_data_json\x18\x01 \x01(\fR\x0eclientDataJson\x12-\n" +
	"\x12authenticator_data\x18\x02 \x01(\fR\x11authenticatorData\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x1f\n" +
	"\vuser_handle\x18\x04 \x01(\fR\n" +
	"userHandle*\x97\x01\n" +
	"\x17AuthenticatorAttachment\x12(\n" +
	"$AUTHENTICATOR_ATTACHMENT_UNSPECIFIED\x10\x00\x12%\n" +
	"!AUTHENTICATOR_ATTACHMENT_PLATFORM\x10\x01\x12+\n" +
	"'AUTHENTICATOR_ATTACHMENT_CROSS_PLATFORM\x10\x02*\xbb\x01\n" +
	"\x16ResidentKeyRequirement\x12(\n" +
	"$RESIDENT_KEY_REQUIREMENT_UNSPECIFIED\x10\x00\x12(\n" +
	"$RESIDENT_KEY_REQUIREMENT_DISCOURAGED\x10\x01\x12&\n" +
	"\"RESIDENT_KEY_REQUIREMENT_PREFERRED\x10\x02\x12%\n" +
	"!RESIDENT_KEY_REQUIREMENT_REQUIRED\x10\x03*\xd4\x01\n" +
	"\x1bUserVerificationRequirement\x12-\n" +
	")USER_VERIFICATION_REQUIREMENT_UNSPECIFIED\x10\x00\x12-\n" +
	")USER_VERIFICATION_REQUIREMENT_DISCOURAGED\x10\x01\x12+\n" +
	"'USER_VERIFICATION_REQUIREMENT_PREFERRED\x10\x02\x12*\n" +
	"&USER_VERIFICATION_REQUIREMENT_REQUIRED\x10\x03B!Z\x1fgithub.com/authaas/api/webauthnb\x06proto3"

var (
	file_webauthn_authenticator_proto_rawDescOnce sync.Once
	file_webauthn_authenticator_proto_rawDescData []byte
)

func file_webauthn_authenticator_proto_rawDescGZIP() []byte {
	file_webauthn_authenticator_proto_rawDescOnce.Do(func() {
		file_webauthn_authenticator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webauthn_authenticator_proto_rawDesc), len(file_webauthn_authenticator_proto_rawDesc)))
	})
	return file_webauthn_authenticator_proto_rawDescData
}

var file_webauthn_authenticator_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_webauthn_authenticator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_webauthn_authenticator_proto_goTypes = []any{
	(AuthenticatorAttachment)(0),             // 0: webauthn.AuthenticatorAttachment
	(ResidentKeyRequirement)(0),              // 1: webauthn.ResidentKeyRequirement
	(UserVerificationRequirement)(0),         // 2: webauthn.UserVerificationRequirement
	(*AuthenticatorSelectionCriteria)(nil),   // 3: webauthn.AuthenticatorSelectionCriteria
	(*AuthenticatorAttestationResponse)(nil), // 4: webauthn.AuthenticatorAttestationResponse
	(*AuthenticatorAssertionResponse)(nil),   // 5: webauthn.AuthenticatorAssertionResponse
}
var file_webauthn_authenticator_proto_depIdxs = []int32{
	0, // 0: webauthn.AuthenticatorSelectionCriteria.authenticator_attachment:type_name -> webauthn.AuthenticatorAttachment
	1, // 1: webauthn.AuthenticatorSelectionCriteria.resident_key:type_name -> webauthn.ResidentKeyRequirement
	2, // 2: webauthn.AuthenticatorSelectionCriteria.user_verification:type_name -> webauthn.UserVerificationRequirement
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_webauthn_authenticator_proto_init() }
func file_webauthn_authenticator_proto_init() {
	if File_webauthn_authenticator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webauthn_authenticator_proto_rawDesc), len(file_webauthn_authenticator_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webauthn_authenticator_proto_goTypes,
		DependencyIndexes: file_webauthn_authenticator_proto_depIdxs,
		EnumInfos:         file_webauthn_authenticator_proto_enumTypes,
		MessageInfos:      file_webauthn_authenticator_proto_msgTypes,
	}.Build()
	File_webauthn_authenticator_proto = out.File
	file_webauthn_authenticator_proto_goTypes = nil
	file_webauthn_authenticator_proto_depIdxs = nil
}
