// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: webauthn/login.proto

package webauthn

import (
	identity "github.com/authaas/api/identity"
	token "github.com/authaas/api/token"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicKeyCredentialRequestOptions struct {
	state            protoimpl.MessageState           `protogen:"open.v1"`
	Challenge        []byte                           `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Timeout          uint32                           `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	RpId             string                           `protobuf:"bytes,3,opt,name=rp_id,json=rpId,proto3" json:"rp_id,omitempty"`
	AllowCredentials []*PublicKeyCredentialDescriptor `protobuf:"bytes,4,rep,name=allow_credentials,json=allowCredentials,proto3" json:"allow_credentials,omitempty"`
	UserVerification UserVerificationRequirement      `protobuf:"varint,5,opt,name=user_verification,json=userVerification,proto3,enum=webauthn.UserVerificationRequirement" json:"user_verification,omitempty"`
	Hints            []string                         `protobuf:"bytes,6,rep,name=hints,proto3" json:"hints,omitempty"`
	Extensions       []byte                           `protobuf:"bytes,7,opt,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PublicKeyCredentialRequestOptions) Reset() {
	*x = PublicKeyCredentialRequestOptions{}
	mi := &file_webauthn_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyCredentialRequestOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyCredentialRequestOptions) ProtoMessage() {}

func (x *PublicKeyCredentialRequestOptions) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyCredentialRequestOptions.ProtoReflect.Descriptor instead.
func (*PublicKeyCredentialRequestOptions) Descriptor() ([]byte, []int) {
	return file_webauthn_login_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKeyCredentialRequestOptions) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *PublicKeyCredentialRequestOptions) GetTimeout() uint32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *PublicKeyCredentialRequestOptions) GetRpId() string {
	if x != nil {
		return x.RpId
	}
	return ""
}

func (x *PublicKeyCredentialRequestOptions) GetAllowCredentials() []*PublicKeyCredentialDescriptor {
	if x != nil {
		return x.AllowCredentials
	}
	return nil
}

func (x *PublicKeyCredentialRequestOptions) GetUserVerification() UserVerificationRequirement {
	if x != nil {
		return x.UserVerification
	}
	return UserVerificationRequirement_USER_VERIFICATION_REQUIREMENT_UNSPECIFIED
}

func (x *PublicKeyCredentialRequestOptions) GetHints() []string {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *PublicKeyCredentialRequestOptions) GetExtensions() []byte {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*LoginRequest_Start
	//	*LoginRequest_Credential
	Message       isLoginRequest_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_webauthn_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_login_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetMessage() isLoginRequest_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *LoginRequest) GetStart() *LoginRequest_LoginStart {
	if x != nil {
		if x, ok := x.Message.(*LoginRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *LoginRequest) GetCredential() *LoginRequest_AssertionCredential {
	if x != nil {
		if x, ok := x.Message.(*LoginRequest_Credential); ok {
			return x.Credential
		}
	}
	return nil
}

type isLoginRequest_Message interface {
	isLoginRequest_Message()
}

type LoginRequest_Start struct {
	Start *LoginRequest_LoginStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type LoginRequest_Credential struct {
	Credential *LoginRequest_AssertionCredential `protobuf:"bytes,2,opt,name=credential,proto3,oneof"`
}

func (*LoginRequest_Start) isLoginRequest_Message() {}

func (*LoginRequest_Credential) isLoginRequest_Message() {}

type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*LoginResponse_Options
	//	*LoginResponse_Result
	Message       isLoginResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_webauthn_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_login_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetMessage() isLoginResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *LoginResponse) GetOptions() *PublicKeyCredentialRequestOptions {
	if x != nil {
		if x, ok := x.Message.(*LoginResponse_Options); ok {
			return x.Options
		}
	}
	return nil
}

func (x *LoginResponse) GetResult() *LoginResponse_LoginResult {
	if x != nil {
		if x, ok := x.Message.(*LoginResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isLoginResponse_Message interface {
	isLoginResponse_Message()
}

type LoginResponse_Options struct {
	Options *PublicKeyCredentialRequestOptions `protobuf:"bytes,1,opt,name=options,proto3,oneof"`
}

type LoginResponse_Result struct {
	Result *LoginResponse_LoginResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*LoginResponse_Options) isLoginResponse_Message() {}

func (*LoginResponse_Result) isLoginResponse_Message() {}

type LoginRequest_LoginStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest_LoginStart) Reset() {
	*x = LoginRequest_LoginStart{}
	mi := &file_webauthn_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest_LoginStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest_LoginStart) ProtoMessage() {}

func (x *LoginRequest_LoginStart) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest_LoginStart.ProtoReflect.Descriptor instead.
func (*LoginRequest_LoginStart) Descriptor() ([]byte, []int) {
	return file_webauthn_login_proto_rawDescGZIP(), []int{1, 0}
}

type LoginRequest_AssertionCredential struct {
	state                   protoimpl.MessageState          `protogen:"open.v1"`
	RawId                   []byte                          `protobuf:"bytes,1,opt,name=raw_id,json=rawId,proto3" json:"raw_id,omitempty"`
	Type                    PublicKeyCredentialType         `protobuf:"varint,2,opt,name=type,proto3,enum=webauthn.PublicKeyCredentialType" json:"type,omitempty"`
	AuthenticatorAttachment AuthenticatorAttachment         `protobuf:"varint,3,opt,name=authenticator_attachment,json=authenticatorAttachment,proto3,enum=webauthn.AuthenticatorAttachment" json:"authenticator_attachment,omitempty"`
	ClientExtensionResults  []byte                          `protobuf:"bytes,4,opt,name=client_extension_results,json=clientExtensionResults,proto3" json:"client_extension_results,omitempty"`
	Response                *AuthenticatorAssertionResponse `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LoginRequest_AssertionCredential) Reset() {
	*x = LoginRequest_AssertionCredential{}
	mi := &file_webauthn_login_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest_AssertionCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest_AssertionCredential) ProtoMessage() {}

func (x *LoginRequest_AssertionCredential) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_login_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest_AssertionCredential.ProtoReflect.Descriptor instead.
func (*LoginRequest_AssertionCredential) Descriptor() ([]byte, []int) {
	return file_webauthn_login_proto_rawDescGZIP(), []int{1, 1}
}

func (x *LoginRequest_AssertionCredential) GetRawId() []byte {
	if x != nil {
		return x.RawId
	}
	return nil
}

func (x *LoginRequest_AssertionCredential) GetType() PublicKeyCredentialType {
	if x != nil {
		return x.Type
	}
	return PublicKeyCredentialType_PUBLIC_KEY_CREDENTIAL_TYPE_UNSPECIFIED
}

func (x *LoginRequest_AssertionCredential) GetAuthenticatorAttachment() AuthenticatorAttachment {
	if x != nil {
		return x.AuthenticatorAttachment
	}
	return AuthenticatorAttachment_AUTHENTICATOR_ATTACHMENT_UNSPECIFIED
}

func (x *LoginRequest_AssertionCredential) GetClientExtensionResults() []byte {
	if x != nil {
		return x.ClientExtensionResults
	}
	return nil
}

func (x *LoginRequest_AssertionCredential) GetResponse() *AuthenticatorAssertionResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type LoginResponse_LoginResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     *identity.Principal    `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	Grant         *token.Grant           `protobuf:"bytes,2,opt,name=grant,proto3" json:"grant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse_LoginResult) Reset() {
	*x = LoginResponse_LoginResult{}
	mi := &file_webauthn_login_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse_LoginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse_LoginResult) ProtoMessage() {}

func (x *LoginResponse_LoginResult) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_login_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse_LoginResult.ProtoReflect.Descriptor instead.
func (*LoginResponse_LoginResult) Descriptor() ([]byte, []int) {
	return file_webauthn_login_proto_rawDescGZIP(), []int{2, 0}
}

func (x *LoginResponse_LoginResult) GetPrincipal() *identity.Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *LoginResponse_LoginResult) GetGrant() *token.Grant {
	if x != nil {
		return x.Grant
	}
	return nil
}

var File_webauthn_login_proto protoreflect.FileDescriptor

const file_webauthn_login_proto_rawDesc = "" +
	"\n" +
	"\x14webauthn/login.proto\x12\bwebauthn\x1a\x18identity/principal.proto\x1a\x11token/grant.proto\x1a\x1cwebauthn/authenticator.proto\x1a$webauthn/public_key_credential.proto\"\xd0\x02\n" +
	"!PublicKeyCredentialRequestOptions\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\fR\tchallenge\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\rR\atimeout\x12\x13\n" +
	"\x05rp_id\x18\x03 \x01(\tR\x04rpId\x12T\n" +
	"\x11allow_credentials\x18\x04 \x03(\v2'.webauthn.PublicKeyCredentialDescriptorR\x10allowCredentials\x12R\n" +
	"\x11user_verification\x18\x05 \x01(\x0e2%.webauthn.UserVerificationRequirementR\x10userVerification\x12\x14\n" +
	"\x05hints\x18\x06 \x03(\tR\x05hints\x12\x1e\n" +
	"\n" +
	"extensions\x18\a \x01(\fR\n" +
	"extensions\"\xf4\x03\n" +
	"\fLoginRequest\x129\n" +
	"\x05start\x18\x01 \x01(\v2!.webauthn.LoginRequest.LoginStartH\x00R\x05start\x12L\n" +
	"\n" +
	"credential\x18\x02 \x01(\v2*.webauthn.LoginRequest.AssertionCredentialH\x00R\n" +
	"credential\x1a\f\n" +
	"\n" +
	"LoginStart\x1a\xc1\x02\n" +
	"\x13AssertionCredential\x12\x15\n" +
	"\x06raw_id\x18\x01 \x01(\fR\x05rawId\x125\n" +
	"\x04type\x18\x02 \x01(\x0e2!.webauthn.PublicKeyCredentialTypeR\x04type\x12\\\n" +
	"\x18authenticator_attachment\x18\x03 \x01(\x0e2!.webauthn.AuthenticatorAttachmentR\x17authenticatorAttachment\x128\n" +
	"\x18client_extension_results\x18\x04 \x01(\fR\x16clientExtensionResults\x12D\n" +
	"\bresponse\x18\x05 \x01(\v2(.webauthn.AuthenticatorAssertionResponseR\bresponseB\t\n" +
	"\amessage\"\x88\x02\n" +
	"\rLoginResponse\x12G\n" +
	"\aoptions\x18\x01 \x01(\v2+.webauthn.PublicKeyCredentialRequestOptionsH\x00R\aoptions\x12=\n" +
	"\x06result\x18\x02 \x01(\v2#.webauthn.LoginResponse.LoginResultH\x00R\x06result\x1ad\n" +
	"\vLoginResult\x121\n" +
	"\tprincipal\x18\x01 \x01(\v2\x13.identity.PrincipalR\tprincipal\x12\"\n" +
	"\x05grant\x18\x02 \x01(\v2\f.token.GrantR\x05grantB\t\n" +
	"\amessageB!Z\x1fgithub.com/authaas/api/webauthnb\x06proto3"

var (
	file_webauthn_login_proto_rawDescOnce sync.Once
	file_webauthn_login_proto_rawDescData []byte
)

func file_webauthn_login_proto_rawDescGZIP() []byte {
	file_webauthn_login_proto_rawDescOnce.Do(func() {
		file_webauthn_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webauthn_login_proto_rawDesc), len(file_webauthn_login_proto_rawDesc)))
	})
	return file_webauthn_login_proto_rawDescData
}

var file_webauthn_login_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_webauthn_login_proto_goTypes = []any{
	(*PublicKeyCredentialRequestOptions)(nil), // 0: webauthn.PublicKeyCredentialRequestOptions
	(*LoginRequest)(nil),                      // 1: webauthn.LoginRequest
	(*LoginResponse)(nil),                     // 2: webauthn.LoginResponse
	(*LoginRequest_LoginStart)(nil),           // 3: webauthn.LoginRequest.LoginStart
	(*LoginRequest_AssertionCredential)(nil),  // 4: webauthn.LoginRequest.AssertionCredential
	(*LoginResponse_LoginResult)(nil),         // 5: webauthn.LoginResponse.LoginResult
	(*PublicKeyCredentialDescriptor)(nil),     // 6: webauthn.PublicKeyCredentialDescriptor
	(UserVerificationRequirement)(0),          // 7: webauthn.UserVerificationRequirement
	(PublicKeyCredentialType)(0),              // 8: webauthn.PublicKeyCredentialType
	(AuthenticatorAttachment)(0),              // 9: webauthn.AuthenticatorAttachment
	(*AuthenticatorAssertionResponse)(nil),    // 10: webauthn.AuthenticatorAssertionResponse
	(*identity.Principal)(nil),                // 11: identity.Principal
	(*token.Grant)(nil),                       // 12: token.Grant
}
var file_webauthn_login_proto_depIdxs = []int32{
	6,  // 0: webauthn.PublicKeyCredentialRequestOptions.allow_credentials:type_name -> webauthn.PublicKeyCredentialDescriptor
	7,  // 1: webauthn.PublicKeyCredentialRequestOptions.user_verification:type_name -> webauthn.UserVerificationRequirement
	3,  // 2: webauthn.LoginRequest.start:type_name -> webauthn.LoginRequest.LoginStart
	4,  // 3: webauthn.LoginRequest.credential:type_name -> webauthn.LoginRequest.AssertionCredential
	0,  // 4: webauthn.LoginResponse.options:type_name -> webauthn.PublicKeyCredentialRequestOptions
	5,  // 5: webauthn.LoginResponse.result:type_name -> webauthn.LoginResponse.LoginResult
	8,  // 6: webauthn.LoginRequest.AssertionCredential.type:type_name -> webauthn.PublicKeyCredentialType
	9,  // 7: webauthn.LoginRequest.AssertionCredential.authenticator_attachment:type_name -> webauthn.AuthenticatorAttachment
	10, // 8: webauthn.LoginRequest.AssertionCredential.response:type_name -> webauthn.AuthenticatorAssertionResponse
	11, // 9: webauthn.LoginResponse.LoginResult.principal:type_name -> identity.Principal
	12, // 10: webauthn.LoginResponse.LoginResult.grant:type_name -> token.Grant
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_webauthn_login_proto_init() }
func file_webauthn_login_proto_init() {
	if File_webauthn_login_proto != nil {
		return
	}
	file_webauthn_authenticator_proto_init()
	file_webauthn_public_key_credential_proto_init()
	file_webauthn_login_proto_msgTypes[1].OneofWrappers = []any{
		(*LoginRequest_Start)(nil),
		(*LoginRequest_Credential)(nil),
	}
	file_webauthn_login_proto_msgTypes[2].OneofWrappers = []any{
		(*LoginResponse_Options)(nil),
		(*LoginResponse_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webauthn_login_proto_rawDesc), len(file_webauthn_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webauthn_login_proto_goTypes,
		DependencyIndexes: file_webauthn_login_proto_depIdxs,
		MessageInfos:      file_webauthn_login_proto_msgTypes,
	}.Build()
	File_webauthn_login_proto = out.File
	file_webauthn_login_proto_goTypes = nil
	file_webauthn_login_proto_depIdxs = nil
}
