// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: webauthn/public_key_credential.proto

package webauthn

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoseAlgorithm int32

const (
	CoseAlgorithm_COSE_ALGORITHM_UNSPECIFIED CoseAlgorithm = 0
	CoseAlgorithm_COSE_ALGORITHM_EDDSA       CoseAlgorithm = -8
	CoseAlgorithm_COSE_ALGORITHM_ES256       CoseAlgorithm = -7
	CoseAlgorithm_COSE_ALGORITHM_RS256       CoseAlgorithm = -257
)

// Enum value maps for CoseAlgorithm.
var (
	CoseAlgorithm_name = map[int32]string{
		0:    "COSE_ALGORITHM_UNSPECIFIED",
		-8:   "COSE_ALGORITHM_EDDSA",
		-7:   "COSE_ALGORITHM_ES256",
		-257: "COSE_ALGORITHM_RS256",
	}
	CoseAlgorithm_value = map[string]int32{
		"COSE_ALGORITHM_UNSPECIFIED": 0,
		"COSE_ALGORITHM_EDDSA":       -8,
		"COSE_ALGORITHM_ES256":       -7,
		"COSE_ALGORITHM_RS256":       -257,
	}
)

func (x CoseAlgorithm) Enum() *CoseAlgorithm {
	p := new(CoseAlgorithm)
	*p = x
	return p
}

func (x CoseAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoseAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_webauthn_public_key_credential_proto_enumTypes[0].Descriptor()
}

func (CoseAlgorithm) Type() protoreflect.EnumType {
	return &file_webauthn_public_key_credential_proto_enumTypes[0]
}

func (x CoseAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoseAlgorithm.Descriptor instead.
func (CoseAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_webauthn_public_key_credential_proto_rawDescGZIP(), []int{0}
}

type PublicKeyCredentialType int32

const (
	PublicKeyCredentialType_PUBLIC_KEY_CREDENTIAL_TYPE_UNSPECIFIED PublicKeyCredentialType = 0
	PublicKeyCredentialType_PUBLIC_KEY_CREDENTIAL_TYPE_PUBLIC_KEY  PublicKeyCredentialType = 1
)

// Enum value maps for PublicKeyCredentialType.
var (
	PublicKeyCredentialType_name = map[int32]string{
		0: "PUBLIC_KEY_CREDENTIAL_TYPE_UNSPECIFIED",
		1: "PUBLIC_KEY_CREDENTIAL_TYPE_PUBLIC_KEY",
	}
	PublicKeyCredentialType_value = map[string]int32{
		"PUBLIC_KEY_CREDENTIAL_TYPE_UNSPECIFIED": 0,
		"PUBLIC_KEY_CREDENTIAL_TYPE_PUBLIC_KEY":  1,
	}
)

func (x PublicKeyCredentialType) Enum() *PublicKeyCredentialType {
	p := new(PublicKeyCredentialType)
	*p = x
	return p
}

func (x PublicKeyCredentialType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublicKeyCredentialType) Descriptor() protoreflect.EnumDescriptor {
	return file_webauthn_public_key_credential_proto_enumTypes[1].Descriptor()
}

func (PublicKeyCredentialType) Type() protoreflect.EnumType {
	return &file_webauthn_public_key_credential_proto_enumTypes[1]
}

func (x PublicKeyCredentialType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublicKeyCredentialType.Descriptor instead.
func (PublicKeyCredentialType) EnumDescriptor() ([]byte, []int) {
	return file_webauthn_public_key_credential_proto_rawDescGZIP(), []int{1}
}

type AttestationConveyancePreference int32

const (
	AttestationConveyancePreference_ATTESTATION_CONVEYANCE_PREFERENCE_UNSPECIFIED AttestationConveyancePreference = 0
	AttestationConveyancePreference_ATTESTATION_CONVEYANCE_PREFERENCE_NONE        AttestationConveyancePreference = 1
	AttestationConveyancePreference_ATTESTATION_CONVEYANCE_PREFERENCE_INDIRECT    AttestationConveyancePreference = 2
	AttestationConveyancePreference_ATTESTATION_CONVEYANCE_PREFERENCE_DIRECT      AttestationConveyancePreference = 3
	AttestationConveyancePreference_ATTESTATION_CONVEYANCE_PREFERENCE_ENTERPRISE  AttestationConveyancePreference = 4
)

// Enum value maps for AttestationConveyancePreference.
var (
	AttestationConveyancePreference_name = map[int32]string{
		0: "ATTESTATION_CONVEYANCE_PREFERENCE_UNSPECIFIED",
		1: "ATTESTATION_CONVEYANCE_PREFERENCE_NONE",
		2: "ATTESTATION_CONVEYANCE_PREFERENCE_INDIRECT",
		3: "ATTESTATION_CONVEYANCE_PREFERENCE_DIRECT",
		4: "ATTESTATION_CONVEYANCE_PREFERENCE_ENTERPRISE",
	}
	AttestationConveyancePreference_value = map[string]int32{
		"ATTESTATION_CONVEYANCE_PREFERENCE_UNSPECIFIED": 0,
		"ATTESTATION_CONVEYANCE_PREFERENCE_NONE":        1,
		"ATTESTATION_CONVEYANCE_PREFERENCE_INDIRECT":    2,
		"ATTESTATION_CONVEYANCE_PREFERENCE_DIRECT":      3,
		"ATTESTATION_CONVEYANCE_PREFERENCE_ENTERPRISE":  4,
	}
)

func (x AttestationConveyancePreference) Enum() *AttestationConveyancePreference {
	p := new(AttestationConveyancePreference)
	*p = x
	return p
}

func (x AttestationConveyancePreference) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttestationConveyancePreference) Descriptor() protoreflect.EnumDescriptor {
	return file_webauthn_public_key_credential_proto_enumTypes[2].Descriptor()
}

func (AttestationConveyancePreference) Type() protoreflect.EnumType {
	return &file_webauthn_public_key_credential_proto_enumTypes[2]
}

func (x AttestationConveyancePreference) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttestationConveyancePreference.Descriptor instead.
func (AttestationConveyancePreference) EnumDescriptor() ([]byte, []int) {
	return file_webauthn_public_key_credential_proto_rawDescGZIP(), []int{2}
}

type PublicKeyCredentialParameters struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          PublicKeyCredentialType `protobuf:"varint,1,opt,name=type,proto3,enum=webauthn.PublicKeyCredentialType" json:"type,omitempty"`
	Alg           CoseAlgorithm           `protobuf:"varint,2,opt,name=alg,proto3,enum=webauthn.CoseAlgorithm" json:"alg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeyCredentialParameters) Reset() {
	*x = PublicKeyCredentialParameters{}
	mi := &file_webauthn_public_key_credential_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyCredentialParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyCredentialParameters) ProtoMessage() {}

func (x *PublicKeyCredentialParameters) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_public_key_credential_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyCredentialParameters.ProtoReflect.Descriptor instead.
func (*PublicKeyCredentialParameters) Descriptor() ([]byte, []int) {
	return file_webauthn_public_key_credential_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKeyCredentialParameters) GetType() PublicKeyCredentialType {
	if x != nil {
		return x.Type
	}
	return PublicKeyCredentialType_PUBLIC_KEY_CREDENTIAL_TYPE_UNSPECIFIED
}

func (x *PublicKeyCredentialParameters) GetAlg() CoseAlgorithm {
	if x != nil {
		return x.Alg
	}
	return CoseAlgorithm_COSE_ALGORITHM_UNSPECIFIED
}

type PublicKeyCredentialDescriptor struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            []byte                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          PublicKeyCredentialType `protobuf:"varint,2,opt,name=type,proto3,enum=webauthn.PublicKeyCredentialType" json:"type,omitempty"`
	Transports    []string                `protobuf:"bytes,3,rep,name=transports,proto3" json:"transports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeyCredentialDescriptor) Reset() {
	*x = PublicKeyCredentialDescriptor{}
	mi := &file_webauthn_public_key_credential_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyCredentialDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyCredentialDescriptor) ProtoMessage() {}

func (x *PublicKeyCredentialDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_public_key_credential_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyCredentialDescriptor.ProtoReflect.Descriptor instead.
func (*PublicKeyCredentialDescriptor) Descriptor() ([]byte, []int) {
	return file_webauthn_public_key_credential_proto_rawDescGZIP(), []int{1}
}

func (x *PublicKeyCredentialDescriptor) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PublicKeyCredentialDescriptor) GetType() PublicKeyCredentialType {
	if x != nil {
		return x.Type
	}
	return PublicKeyCredentialType_PUBLIC_KEY_CREDENTIAL_TYPE_UNSPECIFIED
}

func (x *PublicKeyCredentialDescriptor) GetTransports() []string {
	if x != nil {
		return x.Transports
	}
	return nil
}

var File_webauthn_public_key_credential_proto protoreflect.FileDescriptor

const file_webauthn_public_key_credential_proto_rawDesc = "" +
	"\n" +
	"$webauthn/public_key_credential.proto\x12\bwebauthn\"\x81\x01\n" +
	"\x1dPublicKeyCredentialParameters\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.webauthn.PublicKeyCredentialTypeR\x04type\x12)\n" +
	"\x03alg\x18\x02 \x01(\x0e2\x17.webauthn.CoseAlgorithmR\x03alg\"\x86\x01\n" +
	"\x1dPublicKeyCredentialDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x125\n" +
	"\x04type\x18\x02 \x01(\x0e2!.webauthn.PublicKeyCredentialTypeR\x04type\x12\x1e\n" +
	"\n" +
	"transports\x18\x03 \x03(\tR\n" +
	"transports*\x98\x01\n" +
	"\rCoseAlgorithm\x12\x1e\n" +
	"\x1aCOSE_ALGORITHM_UNSPECIFIED\x10\x00\x12!\n" +
	"\x14COSE_ALGORITHM_EDDSA\x10\xf8\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12!\n" +
	"\x14COSE_ALGORITHM_ES256\x10\xf9\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12!\n" +
	"\x14COSE_ALGORITHM_RS256\x10\xff\xfd\xff\xff\xff\xff\xff\xff\xff\x01*p\n" +
	"\x17PublicKeyCredentialType\x12*\n" +
	"&PUBLIC_KEY_CREDENTIAL_TYPE_UNSPECIFIED\x10\x00\x12)\n" +
	"%PUBLIC_KEY_CREDENTIAL_TYPE_PUBLIC_KEY\x10\x01*\x90\x02\n" +
	"\x1fAttestationConveyancePreference\x121\n" +
	"-ATTESTATION_CONVEYANCE_PREFERENCE_UNSPECIFIED\x10\x00\x12*\n" +
	"&ATTESTATION_CONVEYANCE_PREFERENCE_NONE\x10\x01\x12.\n" +
	"*ATTESTATION_CONVEYANCE_PREFERENCE_INDIRECT\x10\x02\x12,\n" +
	"(ATTESTATION_CONVEYANCE_PREFERENCE_DIRECT\x10\x03\x120\n" +
	",ATTESTATION_CONVEYANCE_PREFERENCE_ENTERPRISE\x10\x04B3Z1git.sonicoriginal.software/grpc-auth-api/webauthnb\x06proto3"

var (
	file_webauthn_public_key_credential_proto_rawDescOnce sync.Once
	file_webauthn_public_key_credential_proto_rawDescData []byte
)

func file_webauthn_public_key_credential_proto_rawDescGZIP() []byte {
	file_webauthn_public_key_credential_proto_rawDescOnce.Do(func() {
		file_webauthn_public_key_credential_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webauthn_public_key_credential_proto_rawDesc), len(file_webauthn_public_key_credential_proto_rawDesc)))
	})
	return file_webauthn_public_key_credential_proto_rawDescData
}

var file_webauthn_public_key_credential_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_webauthn_public_key_credential_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_webauthn_public_key_credential_proto_goTypes = []any{
	(CoseAlgorithm)(0),                    // 0: webauthn.CoseAlgorithm
	(PublicKeyCredentialType)(0),          // 1: webauthn.PublicKeyCredentialType
	(AttestationConveyancePreference)(0),  // 2: webauthn.AttestationConveyancePreference
	(*PublicKeyCredentialParameters)(nil), // 3: webauthn.PublicKeyCredentialParameters
	(*PublicKeyCredentialDescriptor)(nil), // 4: webauthn.PublicKeyCredentialDescriptor
}
var file_webauthn_public_key_credential_proto_depIdxs = []int32{
	1, // 0: webauthn.PublicKeyCredentialParameters.type:type_name -> webauthn.PublicKeyCredentialType
	0, // 1: webauthn.PublicKeyCredentialParameters.alg:type_name -> webauthn.CoseAlgorithm
	1, // 2: webauthn.PublicKeyCredentialDescriptor.type:type_name -> webauthn.PublicKeyCredentialType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_webauthn_public_key_credential_proto_init() }
func file_webauthn_public_key_credential_proto_init() {
	if File_webauthn_public_key_credential_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webauthn_public_key_credential_proto_rawDesc), len(file_webauthn_public_key_credential_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webauthn_public_key_credential_proto_goTypes,
		DependencyIndexes: file_webauthn_public_key_credential_proto_depIdxs,
		EnumInfos:         file_webauthn_public_key_credential_proto_enumTypes,
		MessageInfos:      file_webauthn_public_key_credential_proto_msgTypes,
	}.Build()
	File_webauthn_public_key_credential_proto = out.File
	file_webauthn_public_key_credential_proto_goTypes = nil
	file_webauthn_public_key_credential_proto_depIdxs = nil
}
