// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: webauthn/register.proto

package webauthn

import (
	identity "git.sonicoriginal.software/grpc-auth-api/identity"
	token "git.sonicoriginal.software/grpc-auth-api/token"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicKeyCredentialCreationOptions struct {
	state                  protoimpl.MessageState           `protogen:"open.v1"`
	Challenge              []byte                           `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Timeout                uint32                           `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Rp                     *PublicKeyCredentialRpEntity     `protobuf:"bytes,3,opt,name=rp,proto3" json:"rp,omitempty"`
	User                   *identity.Principal              `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	PubKeyCredParams       []*PublicKeyCredentialParameters `protobuf:"bytes,5,rep,name=pub_key_cred_params,json=pubKeyCredParams,proto3" json:"pub_key_cred_params,omitempty"`
	ExcludeCredentials     []*PublicKeyCredentialDescriptor `protobuf:"bytes,6,rep,name=exclude_credentials,json=excludeCredentials,proto3" json:"exclude_credentials,omitempty"`
	AuthenticatorSelection *AuthenticatorSelectionCriteria  `protobuf:"bytes,7,opt,name=authenticator_selection,json=authenticatorSelection,proto3" json:"authenticator_selection,omitempty"`
	Hints                  []string                         `protobuf:"bytes,8,rep,name=hints,proto3" json:"hints,omitempty"`
	Attestation            AttestationConveyancePreference  `protobuf:"varint,9,opt,name=attestation,proto3,enum=webauthn.AttestationConveyancePreference" json:"attestation,omitempty"`
	AttestationFormats     []string                         `protobuf:"bytes,10,rep,name=attestation_formats,json=attestationFormats,proto3" json:"attestation_formats,omitempty"`
	Extensions             []byte                           `protobuf:"bytes,11,opt,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PublicKeyCredentialCreationOptions) Reset() {
	*x = PublicKeyCredentialCreationOptions{}
	mi := &file_webauthn_register_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyCredentialCreationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyCredentialCreationOptions) ProtoMessage() {}

func (x *PublicKeyCredentialCreationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_register_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyCredentialCreationOptions.ProtoReflect.Descriptor instead.
func (*PublicKeyCredentialCreationOptions) Descriptor() ([]byte, []int) {
	return file_webauthn_register_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKeyCredentialCreationOptions) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *PublicKeyCredentialCreationOptions) GetTimeout() uint32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *PublicKeyCredentialCreationOptions) GetRp() *PublicKeyCredentialRpEntity {
	if x != nil {
		return x.Rp
	}
	return nil
}

func (x *PublicKeyCredentialCreationOptions) GetUser() *identity.Principal {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *PublicKeyCredentialCreationOptions) GetPubKeyCredParams() []*PublicKeyCredentialParameters {
	if x != nil {
		return x.PubKeyCredParams
	}
	return nil
}

func (x *PublicKeyCredentialCreationOptions) GetExcludeCredentials() []*PublicKeyCredentialDescriptor {
	if x != nil {
		return x.ExcludeCredentials
	}
	return nil
}

func (x *PublicKeyCredentialCreationOptions) GetAuthenticatorSelection() *AuthenticatorSelectionCriteria {
	if x != nil {
		return x.AuthenticatorSelection
	}
	return nil
}

func (x *PublicKeyCredentialCreationOptions) GetHints() []string {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *PublicKeyCredentialCreationOptions) GetAttestation() AttestationConveyancePreference {
	if x != nil {
		return x.Attestation
	}
	return AttestationConveyancePreference_ATTESTATION_CONVEYANCE_PREFERENCE_UNSPECIFIED
}

func (x *PublicKeyCredentialCreationOptions) GetAttestationFormats() []string {
	if x != nil {
		return x.AttestationFormats
	}
	return nil
}

func (x *PublicKeyCredentialCreationOptions) GetExtensions() []byte {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*RegisterRequest_Start
	//	*RegisterRequest_Credential
	Message       isRegisterRequest_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_webauthn_register_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_register_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_register_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetMessage() isRegisterRequest_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RegisterRequest) GetStart() *RegisterRequest_RegisterStart {
	if x != nil {
		if x, ok := x.Message.(*RegisterRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *RegisterRequest) GetCredential() *RegisterRequest_AttestationCredential {
	if x != nil {
		if x, ok := x.Message.(*RegisterRequest_Credential); ok {
			return x.Credential
		}
	}
	return nil
}

type isRegisterRequest_Message interface {
	isRegisterRequest_Message()
}

type RegisterRequest_Start struct {
	Start *RegisterRequest_RegisterStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type RegisterRequest_Credential struct {
	Credential *RegisterRequest_AttestationCredential `protobuf:"bytes,2,opt,name=credential,proto3,oneof"`
}

func (*RegisterRequest_Start) isRegisterRequest_Message() {}

func (*RegisterRequest_Credential) isRegisterRequest_Message() {}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*RegisterResponse_Options
	//	*RegisterResponse_Result
	Message       isRegisterResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_webauthn_register_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_register_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_register_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetMessage() isRegisterResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RegisterResponse) GetOptions() *PublicKeyCredentialCreationOptions {
	if x != nil {
		if x, ok := x.Message.(*RegisterResponse_Options); ok {
			return x.Options
		}
	}
	return nil
}

func (x *RegisterResponse) GetResult() *RegisterResponse_RegisterResult {
	if x != nil {
		if x, ok := x.Message.(*RegisterResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isRegisterResponse_Message interface {
	isRegisterResponse_Message()
}

type RegisterResponse_Options struct {
	Options *PublicKeyCredentialCreationOptions `protobuf:"bytes,1,opt,name=options,proto3,oneof"`
}

type RegisterResponse_Result struct {
	Result *RegisterResponse_RegisterResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*RegisterResponse_Options) isRegisterResponse_Message() {}

func (*RegisterResponse_Result) isRegisterResponse_Message() {}

type RegisterRequest_RegisterStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest_RegisterStart) Reset() {
	*x = RegisterRequest_RegisterStart{}
	mi := &file_webauthn_register_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest_RegisterStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest_RegisterStart) ProtoMessage() {}

func (x *RegisterRequest_RegisterStart) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_register_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest_RegisterStart.ProtoReflect.Descriptor instead.
func (*RegisterRequest_RegisterStart) Descriptor() ([]byte, []int) {
	return file_webauthn_register_proto_rawDescGZIP(), []int{1, 0}
}

func (x *RegisterRequest_RegisterStart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest_RegisterStart) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type RegisterRequest_AttestationCredential struct {
	state                   protoimpl.MessageState            `protogen:"open.v1"`
	RawId                   []byte                            `protobuf:"bytes,1,opt,name=raw_id,json=rawId,proto3" json:"raw_id,omitempty"`
	Type                    PublicKeyCredentialType           `protobuf:"varint,2,opt,name=type,proto3,enum=webauthn.PublicKeyCredentialType" json:"type,omitempty"`
	AuthenticatorAttachment AuthenticatorAttachment           `protobuf:"varint,3,opt,name=authenticator_attachment,json=authenticatorAttachment,proto3,enum=webauthn.AuthenticatorAttachment" json:"authenticator_attachment,omitempty"`
	ClientExtensionResults  []byte                            `protobuf:"bytes,4,opt,name=client_extension_results,json=clientExtensionResults,proto3" json:"client_extension_results,omitempty"`
	Response                *AuthenticatorAttestationResponse `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RegisterRequest_AttestationCredential) Reset() {
	*x = RegisterRequest_AttestationCredential{}
	mi := &file_webauthn_register_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest_AttestationCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest_AttestationCredential) ProtoMessage() {}

func (x *RegisterRequest_AttestationCredential) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_register_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest_AttestationCredential.ProtoReflect.Descriptor instead.
func (*RegisterRequest_AttestationCredential) Descriptor() ([]byte, []int) {
	return file_webauthn_register_proto_rawDescGZIP(), []int{1, 1}
}

func (x *RegisterRequest_AttestationCredential) GetRawId() []byte {
	if x != nil {
		return x.RawId
	}
	return nil
}

func (x *RegisterRequest_AttestationCredential) GetType() PublicKeyCredentialType {
	if x != nil {
		return x.Type
	}
	return PublicKeyCredentialType_PUBLIC_KEY_CREDENTIAL_TYPE_UNSPECIFIED
}

func (x *RegisterRequest_AttestationCredential) GetAuthenticatorAttachment() AuthenticatorAttachment {
	if x != nil {
		return x.AuthenticatorAttachment
	}
	return AuthenticatorAttachment_AUTHENTICATOR_ATTACHMENT_UNSPECIFIED
}

func (x *RegisterRequest_AttestationCredential) GetClientExtensionResults() []byte {
	if x != nil {
		return x.ClientExtensionResults
	}
	return nil
}

func (x *RegisterRequest_AttestationCredential) GetResponse() *AuthenticatorAttestationResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type RegisterResponse_RegisterResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     *identity.Principal    `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	Grant         *token.Grant           `protobuf:"bytes,2,opt,name=grant,proto3" json:"grant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse_RegisterResult) Reset() {
	*x = RegisterResponse_RegisterResult{}
	mi := &file_webauthn_register_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse_RegisterResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse_RegisterResult) ProtoMessage() {}

func (x *RegisterResponse_RegisterResult) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_register_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse_RegisterResult.ProtoReflect.Descriptor instead.
func (*RegisterResponse_RegisterResult) Descriptor() ([]byte, []int) {
	return file_webauthn_register_proto_rawDescGZIP(), []int{2, 0}
}

func (x *RegisterResponse_RegisterResult) GetPrincipal() *identity.Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *RegisterResponse_RegisterResult) GetGrant() *token.Grant {
	if x != nil {
		return x.Grant
	}
	return nil
}

var File_webauthn_register_proto protoreflect.FileDescriptor

const file_webauthn_register_proto_rawDesc = "" +
	"\n" +
	"\x17webauthn/register.proto\x12\bwebauthn\x1a\x18identity/principal.proto\x1a\x11token/grant.proto\x1a\x1cwebauthn/authenticator.proto\x1a$webauthn/public_key_credential.proto\x1a\x1cwebauthn/relying_party.proto\"\x85\x05\n" +
	"\"PublicKeyCredentialCreationOptions\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\fR\tchallenge\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\rR\atimeout\x125\n" +
	"\x02rp\x18\x03 \x01(\v2%.webauthn.PublicKeyCredentialRpEntityR\x02rp\x12'\n" +
	"\x04user\x18\x04 \x01(\v2\x13.identity.PrincipalR\x04user\x12V\n" +
	"\x13pub_key_cred_params\x18\x05 \x03(\v2'.webauthn.PublicKeyCredentialParametersR\x10pubKeyCredParams\x12X\n" +
	"\x13exclude_credentials\x18\x06 \x03(\v2'.webauthn.PublicKeyCredentialDescriptorR\x12excludeCredentials\x12a\n" +
	"\x17authenticator_selection\x18\a \x01(\v2(.webauthn.AuthenticatorSelectionCriteriaR\x16authenticatorSelection\x12\x14\n" +
	"\x05hints\x18\b \x03(\tR\x05hints\x12K\n" +
	"\vattestation\x18\t \x01(\x0e2).webauthn.AttestationConveyancePreferenceR\vattestation\x12/\n" +
	"\x13attestation_formats\x18\n" +
	" \x03(\tR\x12attestationFormats\x12\x1e\n" +
	"\n" +
	"extensions\x18\v \x01(\fR\n" +
	"extensions\"\xc0\x04\n" +
	"\x0fRegisterRequest\x12?\n" +
	"\x05start\x18\x01 \x01(\v2'.webauthn.RegisterRequest.RegisterStartH\x00R\x05start\x12Q\n" +
	"\n" +
	"credential\x18\x02 \x01(\v2/.webauthn.RegisterRequest.AttestationCredentialH\x00R\n" +
	"credential\x1aF\n" +
	"\rRegisterStart\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x1a\xc5\x02\n" +
	"\x15AttestationCredential\x12\x15\n" +
	"\x06raw_id\x18\x01 \x01(\fR\x05rawId\x125\n" +
	"\x04type\x18\x02 \x01(\x0e2!.webauthn.PublicKeyCredentialTypeR\x04type\x12\\\n" +
	"\x18authenticator_attachment\x18\x03 \x01(\x0e2!.webauthn.AuthenticatorAttachmentR\x17authenticatorAttachment\x128\n" +
	"\x18client_extension_results\x18\x04 \x01(\fR\x16clientExtensionResults\x12F\n" +
	"\bresponse\x18\x05 \x01(\v2*.webauthn.AuthenticatorAttestationResponseR\bresponseB\t\n" +
	"\amessage\"\x95\x02\n" +
	"\x10RegisterResponse\x12H\n" +
	"\aoptions\x18\x01 \x01(\v2,.webauthn.PublicKeyCredentialCreationOptionsH\x00R\aoptions\x12C\n" +
	"\x06result\x18\x02 \x01(\v2).webauthn.RegisterResponse.RegisterResultH\x00R\x06result\x1ag\n" +
	"\x0eRegisterResult\x121\n" +
	"\tprincipal\x18\x01 \x01(\v2\x13.identity.PrincipalR\tprincipal\x12\"\n" +
	"\x05grant\x18\x02 \x01(\v2\f.token.GrantR\x05grantB\t\n" +
	"\amessageB3Z1git.sonicoriginal.software/grpc-auth-api/webauthnb\x06proto3"

var (
	file_webauthn_register_proto_rawDescOnce sync.Once
	file_webauthn_register_proto_rawDescData []byte
)

func file_webauthn_register_proto_rawDescGZIP() []byte {
	file_webauthn_register_proto_rawDescOnce.Do(func() {
		file_webauthn_register_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webauthn_register_proto_rawDesc), len(file_webauthn_register_proto_rawDesc)))
	})
	return file_webauthn_register_proto_rawDescData
}

var file_webauthn_register_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_webauthn_register_proto_goTypes = []any{
	(*PublicKeyCredentialCreationOptions)(nil),    // 0: webauthn.PublicKeyCredentialCreationOptions
	(*RegisterRequest)(nil),                       // 1: webauthn.RegisterRequest
	(*RegisterResponse)(nil),                      // 2: webauthn.RegisterResponse
	(*RegisterRequest_RegisterStart)(nil),         // 3: webauthn.RegisterRequest.RegisterStart
	(*RegisterRequest_AttestationCredential)(nil), // 4: webauthn.RegisterRequest.AttestationCredential
	(*RegisterResponse_RegisterResult)(nil),       // 5: webauthn.RegisterResponse.RegisterResult
	(*PublicKeyCredentialRpEntity)(nil),           // 6: webauthn.PublicKeyCredentialRpEntity
	(*identity.Principal)(nil),                    // 7: identity.Principal
	(*PublicKeyCredentialParameters)(nil),         // 8: webauthn.PublicKeyCredentialParameters
	(*PublicKeyCredentialDescriptor)(nil),         // 9: webauthn.PublicKeyCredentialDescriptor
	(*AuthenticatorSelectionCriteria)(nil),        // 10: webauthn.AuthenticatorSelectionCriteria
	(AttestationConveyancePreference)(0),          // 11: webauthn.AttestationConveyancePreference
	(PublicKeyCredentialType)(0),                  // 12: webauthn.PublicKeyCredentialType
	(AuthenticatorAttachment)(0),                  // 13: webauthn.AuthenticatorAttachment
	(*AuthenticatorAttestationResponse)(nil),      // 14: webauthn.AuthenticatorAttestationResponse
	(*token.Grant)(nil),                           // 15: token.Grant
}
var file_webauthn_register_proto_depIdxs = []int32{
	6,  // 0: webauthn.PublicKeyCredentialCreationOptions.rp:type_name -> webauthn.PublicKeyCredentialRpEntity
	7,  // 1: webauthn.PublicKeyCredentialCreationOptions.user:type_name -> identity.Principal
	8,  // 2: webauthn.PublicKeyCredentialCreationOptions.pub_key_cred_params:type_name -> webauthn.PublicKeyCredentialParameters
	9,  // 3: webauthn.PublicKeyCredentialCreationOptions.exclude_credentials:type_name -> webauthn.PublicKeyCredentialDescriptor
	10, // 4: webauthn.PublicKeyCredentialCreationOptions.authenticator_selection:type_name -> webauthn.AuthenticatorSelectionCriteria
	11, // 5: webauthn.PublicKeyCredentialCreationOptions.attestation:type_name -> webauthn.AttestationConveyancePreference
	3,  // 6: webauthn.RegisterRequest.start:type_name -> webauthn.RegisterRequest.RegisterStart
	4,  // 7: webauthn.RegisterRequest.credential:type_name -> webauthn.RegisterRequest.AttestationCredential
	0,  // 8: webauthn.RegisterResponse.options:type_name -> webauthn.PublicKeyCredentialCreationOptions
	5,  // 9: webauthn.RegisterResponse.result:type_name -> webauthn.RegisterResponse.RegisterResult
	12, // 10: webauthn.RegisterRequest.AttestationCredential.type:type_name -> webauthn.PublicKeyCredentialType
	13, // 11: webauthn.RegisterRequest.AttestationCredential.authenticator_attachment:type_name -> webauthn.AuthenticatorAttachment
	14, // 12: webauthn.RegisterRequest.AttestationCredential.response:type_name -> webauthn.AuthenticatorAttestationResponse
	7,  // 13: webauthn.RegisterResponse.RegisterResult.principal:type_name -> identity.Principal
	15, // 14: webauthn.RegisterResponse.RegisterResult.grant:type_name -> token.Grant
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_webauthn_register_proto_init() }
func file_webauthn_register_proto_init() {
	if File_webauthn_register_proto != nil {
		return
	}
	file_webauthn_authenticator_proto_init()
	file_webauthn_public_key_credential_proto_init()
	file_webauthn_relying_party_proto_init()
	file_webauthn_register_proto_msgTypes[1].OneofWrappers = []any{
		(*RegisterRequest_Start)(nil),
		(*RegisterRequest_Credential)(nil),
	}
	file_webauthn_register_proto_msgTypes[2].OneofWrappers = []any{
		(*RegisterResponse_Options)(nil),
		(*RegisterResponse_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webauthn_register_proto_rawDesc), len(file_webauthn_register_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webauthn_register_proto_goTypes,
		DependencyIndexes: file_webauthn_register_proto_depIdxs,
		MessageInfos:      file_webauthn_register_proto_msgTypes,
	}.Build()
	File_webauthn_register_proto = out.File
	file_webauthn_register_proto_goTypes = nil
	file_webauthn_register_proto_depIdxs = nil
}
