syntax = "proto3";

package webauthn;

option go_package = "github.com/authaas/api/webauthn";

enum CoseAlgorithm {
  COSE_ALGORITHM_UNSPECIFIED = 0;
  COSE_ALGORITHM_EDDSA = -8;
  COSE_ALGORITHM_ES256 = -7;
  COSE_ALGORITHM_RS256 = -257;
}

enum PublicKeyCredentialType {
  PUBLIC_KEY_CREDENTIAL_TYPE_UNSPECIFIED = 0;
  PUBLIC_KEY_CREDENTIAL_TYPE_PUBLIC_KEY = 1;
}

message PublicKeyCredentialParameters {
  PublicKeyCredentialType type = 1;
  CoseAlgorithm alg = 2;
}

enum AttestationConveyancePreference {
  ATTESTATION_CONVEYANCE_PREFERENCE_UNSPECIFIED = 0;
  ATTESTATION_CONVEYANCE_PREFERENCE_NONE = 1;
  ATTESTATION_CONVEYANCE_PREFERENCE_INDIRECT = 2;
  ATTESTATION_CONVEYANCE_PREFERENCE_DIRECT = 3;
  ATTESTATION_CONVEYANCE_PREFERENCE_ENTERPRISE = 4;
}

message PublicKeyCredentialDescriptor {
  bytes id = 1;
  PublicKeyCredentialType type = 2;
  repeated string transports = 3;
}
