// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: services/principal.proto

package services

import (
	identity "git.sonicoriginal.software/grpc-auth-api/identity"
	token "git.sonicoriginal.software/grpc-auth-api/token"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Delete principal
type DeletePrincipalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     *identity.Principal    `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePrincipalRequest) Reset() {
	*x = DeletePrincipalRequest{}
	mi := &file_services_principal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePrincipalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePrincipalRequest) ProtoMessage() {}

func (x *DeletePrincipalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_principal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePrincipalRequest.ProtoReflect.Descriptor instead.
func (*DeletePrincipalRequest) Descriptor() ([]byte, []int) {
	return file_services_principal_proto_rawDescGZIP(), []int{0}
}

func (x *DeletePrincipalRequest) GetPrincipal() *identity.Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

type DeletePrincipalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePrincipalResponse) Reset() {
	*x = DeletePrincipalResponse{}
	mi := &file_services_principal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePrincipalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePrincipalResponse) ProtoMessage() {}

func (x *DeletePrincipalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_principal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePrincipalResponse.ProtoReflect.Descriptor instead.
func (*DeletePrincipalResponse) Descriptor() ([]byte, []int) {
	return file_services_principal_proto_rawDescGZIP(), []int{1}
}

type GetGrantHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     *identity.Principal    `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGrantHashRequest) Reset() {
	*x = GetGrantHashRequest{}
	mi := &file_services_principal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGrantHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGrantHashRequest) ProtoMessage() {}

func (x *GetGrantHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_principal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGrantHashRequest.ProtoReflect.Descriptor instead.
func (*GetGrantHashRequest) Descriptor() ([]byte, []int) {
	return file_services_principal_proto_rawDescGZIP(), []int{2}
}

func (x *GetGrantHashRequest) GetPrincipal() *identity.Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

type GetGrantHashResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SHA-256 digest; unset when no grant is issued
	GrantHash     []byte `protobuf:"bytes,1,opt,name=grant_hash,json=grantHash,proto3,oneof" json:"grant_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGrantHashResponse) Reset() {
	*x = GetGrantHashResponse{}
	mi := &file_services_principal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGrantHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGrantHashResponse) ProtoMessage() {}

func (x *GetGrantHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_principal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGrantHashResponse.ProtoReflect.Descriptor instead.
func (*GetGrantHashResponse) Descriptor() ([]byte, []int) {
	return file_services_principal_proto_rawDescGZIP(), []int{3}
}

func (x *GetGrantHashResponse) GetGrantHash() []byte {
	if x != nil {
		return x.GrantHash
	}
	return nil
}

type ClearGrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     *identity.Principal    `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	Grant         *token.Grant           `protobuf:"bytes,2,opt,name=grant,proto3" json:"grant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearGrantRequest) Reset() {
	*x = ClearGrantRequest{}
	mi := &file_services_principal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearGrantRequest) ProtoMessage() {}

func (x *ClearGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_principal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearGrantRequest.ProtoReflect.Descriptor instead.
func (*ClearGrantRequest) Descriptor() ([]byte, []int) {
	return file_services_principal_proto_rawDescGZIP(), []int{4}
}

func (x *ClearGrantRequest) GetPrincipal() *identity.Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *ClearGrantRequest) GetGrant() *token.Grant {
	if x != nil {
		return x.Grant
	}
	return nil
}

type ClearGrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearGrantResponse) Reset() {
	*x = ClearGrantResponse{}
	mi := &file_services_principal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearGrantResponse) ProtoMessage() {}

func (x *ClearGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_principal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearGrantResponse.ProtoReflect.Descriptor instead.
func (*ClearGrantResponse) Descriptor() ([]byte, []int) {
	return file_services_principal_proto_rawDescGZIP(), []int{5}
}

var File_services_principal_proto protoreflect.FileDescriptor

const file_services_principal_proto_rawDesc = "" +
	"\n" +
	"\x18services/principal.proto\x12\bservices\x1a\x18identity/principal.proto\x1a\x11token/grant.proto\"K\n" +
	"\x16DeletePrincipalRequest\x121\n" +
	"\tprincipal\x18\x01 \x01(\v2\x13.identity.PrincipalR\tprincipal\"\x19\n" +
	"\x17DeletePrincipalResponse\"H\n" +
	"\x13GetGrantHashRequest\x121\n" +
	"\tprincipal\x18\x01 \x01(\v2\x13.identity.PrincipalR\tprincipal\"I\n" +
	"\x14GetGrantHashResponse\x12\"\n" +
	"\n" +
	"grant_hash\x18\x01 \x01(\fH\x00R\tgrantHash\x88\x01\x01B\r\n" +
	"\v_grant_hash\"j\n" +
	"\x11ClearGrantRequest\x121\n" +
	"\tprincipal\x18\x01 \x01(\v2\x13.identity.PrincipalR\tprincipal\x12\"\n" +
	"\x05grant\x18\x02 \x01(\v2\f.token.GrantR\x05grant\"\x14\n" +
	"\x12ClearGrantResponse2\x82\x02\n" +
	"\x10PrincipalService\x12V\n" +
	"\x0fDeletePrincipal\x12 .services.DeletePrincipalRequest\x1a!.services.DeletePrincipalResponse\x12M\n" +
	"\fGetGrantHash\x12\x1d.services.GetGrantHashRequest\x1a\x1e.services.GetGrantHashResponse\x12G\n" +
	"\n" +
	"ClearGrant\x12\x1b.services.ClearGrantRequest\x1a\x1c.services.ClearGrantResponseB3Z1git.sonicoriginal.software/grpc-auth-api/servicesb\x06proto3"

var (
	file_services_principal_proto_rawDescOnce sync.Once
	file_services_principal_proto_rawDescData []byte
)

func file_services_principal_proto_rawDescGZIP() []byte {
	file_services_principal_proto_rawDescOnce.Do(func() {
		file_services_principal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_principal_proto_rawDesc), len(file_services_principal_proto_rawDesc)))
	})
	return file_services_principal_proto_rawDescData
}

var file_services_principal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_services_principal_proto_goTypes = []any{
	(*DeletePrincipalRequest)(nil),  // 0: services.DeletePrincipalRequest
	(*DeletePrincipalResponse)(nil), // 1: services.DeletePrincipalResponse
	(*GetGrantHashRequest)(nil),     // 2: services.GetGrantHashRequest
	(*GetGrantHashResponse)(nil),    // 3: services.GetGrantHashResponse
	(*ClearGrantRequest)(nil),       // 4: services.ClearGrantRequest
	(*ClearGrantResponse)(nil),      // 5: services.ClearGrantResponse
	(*identity.Principal)(nil),      // 6: identity.Principal
	(*token.Grant)(nil),             // 7: token.Grant
}
var file_services_principal_proto_depIdxs = []int32{
	6, // 0: services.DeletePrincipalRequest.principal:type_name -> identity.Principal
	6, // 1: services.GetGrantHashRequest.principal:type_name -> identity.Principal
	6, // 2: services.ClearGrantRequest.principal:type_name -> identity.Principal
	7, // 3: services.ClearGrantRequest.grant:type_name -> token.Grant
	0, // 4: services.PrincipalService.DeletePrincipal:input_type -> services.DeletePrincipalRequest
	2, // 5: services.PrincipalService.GetGrantHash:input_type -> services.GetGrantHashRequest
	4, // 6: services.PrincipalService.ClearGrant:input_type -> services.ClearGrantRequest
	1, // 7: services.PrincipalService.DeletePrincipal:output_type -> services.DeletePrincipalResponse
	3, // 8: services.PrincipalService.GetGrantHash:output_type -> services.GetGrantHashResponse
	5, // 9: services.PrincipalService.ClearGrant:output_type -> services.ClearGrantResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_services_principal_proto_init() }
func file_services_principal_proto_init() {
	if File_services_principal_proto != nil {
		return
	}
	file_services_principal_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_principal_proto_rawDesc), len(file_services_principal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_principal_proto_goTypes,
		DependencyIndexes: file_services_principal_proto_depIdxs,
		MessageInfos:      file_services_principal_proto_msgTypes,
	}.Build()
	File_services_principal_proto = out.File
	file_services_principal_proto_goTypes = nil
	file_services_principal_proto_depIdxs = nil
}
