// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: services/principal.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrincipalService_CreatePrincipal_FullMethodName = "/services.PrincipalService/CreatePrincipal"
	PrincipalService_DeletePrincipal_FullMethodName = "/services.PrincipalService/DeletePrincipal"
)

// PrincipalServiceClient is the client API for PrincipalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PrincipalService handles principal management operations
type PrincipalServiceClient interface {
	// Create a new principal
	CreatePrincipal(ctx context.Context, in *CreatePrincipalRequest, opts ...grpc.CallOption) (*CreatePrincipalResponse, error)
	// Delete principal
	DeletePrincipal(ctx context.Context, in *DeletePrincipalRequest, opts ...grpc.CallOption) (*DeletePrincipalResponse, error)
}

type principalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrincipalServiceClient(cc grpc.ClientConnInterface) PrincipalServiceClient {
	return &principalServiceClient{cc}
}

func (c *principalServiceClient) CreatePrincipal(ctx context.Context, in *CreatePrincipalRequest, opts ...grpc.CallOption) (*CreatePrincipalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePrincipalResponse)
	err := c.cc.Invoke(ctx, PrincipalService_CreatePrincipal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *principalServiceClient) DeletePrincipal(ctx context.Context, in *DeletePrincipalRequest, opts ...grpc.CallOption) (*DeletePrincipalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePrincipalResponse)
	err := c.cc.Invoke(ctx, PrincipalService_DeletePrincipal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrincipalServiceServer is the server API for PrincipalService service.
// All implementations must embed UnimplementedPrincipalServiceServer
// for forward compatibility.
//
// PrincipalService handles principal management operations
type PrincipalServiceServer interface {
	// Create a new principal
	CreatePrincipal(context.Context, *CreatePrincipalRequest) (*CreatePrincipalResponse, error)
	// Delete principal
	DeletePrincipal(context.Context, *DeletePrincipalRequest) (*DeletePrincipalResponse, error)
	mustEmbedUnimplementedPrincipalServiceServer()
}

// UnimplementedPrincipalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrincipalServiceServer struct{}

func (UnimplementedPrincipalServiceServer) CreatePrincipal(context.Context, *CreatePrincipalRequest) (*CreatePrincipalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePrincipal not implemented")
}
func (UnimplementedPrincipalServiceServer) DeletePrincipal(context.Context, *DeletePrincipalRequest) (*DeletePrincipalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePrincipal not implemented")
}
func (UnimplementedPrincipalServiceServer) mustEmbedUnimplementedPrincipalServiceServer() {}
func (UnimplementedPrincipalServiceServer) testEmbeddedByValue()                          {}

// UnsafePrincipalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrincipalServiceServer will
// result in compilation errors.
type UnsafePrincipalServiceServer interface {
	mustEmbedUnimplementedPrincipalServiceServer()
}

func RegisterPrincipalServiceServer(s grpc.ServiceRegistrar, srv PrincipalServiceServer) {
	// If the following call panics, it indicates UnimplementedPrincipalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrincipalService_ServiceDesc, srv)
}

func _PrincipalService_CreatePrincipal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePrincipalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrincipalServiceServer).CreatePrincipal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrincipalService_CreatePrincipal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrincipalServiceServer).CreatePrincipal(ctx, req.(*CreatePrincipalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrincipalService_DeletePrincipal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePrincipalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrincipalServiceServer).DeletePrincipal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrincipalService_DeletePrincipal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrincipalServiceServer).DeletePrincipal(ctx, req.(*DeletePrincipalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PrincipalService_ServiceDesc is the grpc.ServiceDesc for PrincipalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrincipalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.PrincipalService",
	HandlerType: (*PrincipalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePrincipal",
			Handler:    _PrincipalService_CreatePrincipal_Handler,
		},
		{
			MethodName: "DeletePrincipal",
			Handler:    _PrincipalService_DeletePrincipal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/principal.proto",
}
