// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: services/token_issuer.proto

package services

import (
	token "github.com/authaas/api/token"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Issue a signed JWT
type IssueTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Grant         *token.Grant           `protobuf:"bytes,2,opt,name=grant,proto3" json:"grant,omitempty"`
	ExpiresAt     *int64                 `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"` // Optional - If empty, doesn't expire
	NotBefore     *int64                 `protobuf:"varint,4,opt,name=not_before,json=notBefore,proto3,oneof" json:"not_before,omitempty"` // Optional - If empty, set to now
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenRequest) Reset() {
	*x = IssueTokenRequest{}
	mi := &file_services_token_issuer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenRequest) ProtoMessage() {}

func (x *IssueTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_token_issuer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueTokenRequest) Descriptor() ([]byte, []int) {
	return file_services_token_issuer_proto_rawDescGZIP(), []int{0}
}

func (x *IssueTokenRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *IssueTokenRequest) GetGrant() *token.Grant {
	if x != nil {
		return x.Grant
	}
	return nil
}

func (x *IssueTokenRequest) GetExpiresAt() int64 {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return 0
}

func (x *IssueTokenRequest) GetNotBefore() int64 {
	if x != nil && x.NotBefore != nil {
		return *x.NotBefore
	}
	return 0
}

type IssueTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenResponse) Reset() {
	*x = IssueTokenResponse{}
	mi := &file_services_token_issuer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenResponse) ProtoMessage() {}

func (x *IssueTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_token_issuer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueTokenResponse) Descriptor() ([]byte, []int) {
	return file_services_token_issuer_proto_rawDescGZIP(), []int{1}
}

func (x *IssueTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_services_token_issuer_proto protoreflect.FileDescriptor

const file_services_token_issuer_proto_rawDesc = "" +
	"\n" +
	"\x1bservices/token_issuer.proto\x12\bservices\x1a\x11token/grant.proto\"\xb7\x01\n" +
	"\x11IssueTokenRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\"\n" +
	"\x05grant\x18\x02 \x01(\v2\f.token.GrantR\x05grant\x12\"\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03H\x00R\texpiresAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"not_before\x18\x04 \x01(\x03H\x01R\tnotBefore\x88\x01\x01B\r\n" +
	"\v_expires_atB\r\n" +
	"\v_not_before\"*\n" +
	"\x12IssueTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2]\n" +
	"\x12TokenIssuerService\x12G\n" +
	"\n" +
	"IssueToken\x12\x1b.services.IssueTokenRequest\x1a\x1c.services.IssueTokenResponseB!Z\x1fgithub.com/authaas/api/servicesb\x06proto3"

var (
	file_services_token_issuer_proto_rawDescOnce sync.Once
	file_services_token_issuer_proto_rawDescData []byte
)

func file_services_token_issuer_proto_rawDescGZIP() []byte {
	file_services_token_issuer_proto_rawDescOnce.Do(func() {
		file_services_token_issuer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_token_issuer_proto_rawDesc), len(file_services_token_issuer_proto_rawDesc)))
	})
	return file_services_token_issuer_proto_rawDescData
}

var file_services_token_issuer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_token_issuer_proto_goTypes = []any{
	(*IssueTokenRequest)(nil),  // 0: services.IssueTokenRequest
	(*IssueTokenResponse)(nil), // 1: services.IssueTokenResponse
	(*token.Grant)(nil),        // 2: token.Grant
}
var file_services_token_issuer_proto_depIdxs = []int32{
	2, // 0: services.IssueTokenRequest.grant:type_name -> token.Grant
	0, // 1: services.TokenIssuerService.IssueToken:input_type -> services.IssueTokenRequest
	1, // 2: services.TokenIssuerService.IssueToken:output_type -> services.IssueTokenResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_token_issuer_proto_init() }
func file_services_token_issuer_proto_init() {
	if File_services_token_issuer_proto != nil {
		return
	}
	file_services_token_issuer_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_token_issuer_proto_rawDesc), len(file_services_token_issuer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_token_issuer_proto_goTypes,
		DependencyIndexes: file_services_token_issuer_proto_depIdxs,
		MessageInfos:      file_services_token_issuer_proto_msgTypes,
	}.Build()
	File_services_token_issuer_proto = out.File
	file_services_token_issuer_proto_goTypes = nil
	file_services_token_issuer_proto_depIdxs = nil
}
