// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: services/token_verifier.proto

package services

import (
	token "github.com/authaas/api/token"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Decode JWT into claims
type DecodeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeTokenRequest) Reset() {
	*x = DecodeTokenRequest{}
	mi := &file_services_token_verifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeTokenRequest) ProtoMessage() {}

func (x *DecodeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_token_verifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeTokenRequest.ProtoReflect.Descriptor instead.
func (*DecodeTokenRequest) Descriptor() ([]byte, []int) {
	return file_services_token_verifier_proto_rawDescGZIP(), []int{0}
}

func (x *DecodeTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DecodeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *token.JWT             `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeTokenResponse) Reset() {
	*x = DecodeTokenResponse{}
	mi := &file_services_token_verifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeTokenResponse) ProtoMessage() {}

func (x *DecodeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_token_verifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeTokenResponse.ProtoReflect.Descriptor instead.
func (*DecodeTokenResponse) Descriptor() ([]byte, []int) {
	return file_services_token_verifier_proto_rawDescGZIP(), []int{1}
}

func (x *DecodeTokenResponse) GetToken() *token.JWT {
	if x != nil {
		return x.Token
	}
	return nil
}

var File_services_token_verifier_proto protoreflect.FileDescriptor

const file_services_token_verifier_proto_rawDesc = "" +
	"\n" +
	"\x1dservices/token_verifier.proto\x12\bservices\x1a\x0ftoken/jwt.proto\"*\n" +
	"\x12DecodeTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"7\n" +
	"\x13DecodeTokenResponse\x12 \n" +
	"\x05token\x18\x01 \x01(\v2\n" +
	".token.JWTR\x05token2b\n" +
	"\x14TokenVerifierService\x12J\n" +
	"\vDecodeToken\x12\x1c.services.DecodeTokenRequest\x1a\x1d.services.DecodeTokenResponseB!Z\x1fgithub.com/authaas/api/servicesb\x06proto3"

var (
	file_services_token_verifier_proto_rawDescOnce sync.Once
	file_services_token_verifier_proto_rawDescData []byte
)

func file_services_token_verifier_proto_rawDescGZIP() []byte {
	file_services_token_verifier_proto_rawDescOnce.Do(func() {
		file_services_token_verifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_token_verifier_proto_rawDesc), len(file_services_token_verifier_proto_rawDesc)))
	})
	return file_services_token_verifier_proto_rawDescData
}

var file_services_token_verifier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_token_verifier_proto_goTypes = []any{
	(*DecodeTokenRequest)(nil),  // 0: services.DecodeTokenRequest
	(*DecodeTokenResponse)(nil), // 1: services.DecodeTokenResponse
	(*token.JWT)(nil),           // 2: token.JWT
}
var file_services_token_verifier_proto_depIdxs = []int32{
	2, // 0: services.DecodeTokenResponse.token:type_name -> token.JWT
	0, // 1: services.TokenVerifierService.DecodeToken:input_type -> services.DecodeTokenRequest
	1, // 2: services.TokenVerifierService.DecodeToken:output_type -> services.DecodeTokenResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_token_verifier_proto_init() }
func file_services_token_verifier_proto_init() {
	if File_services_token_verifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_token_verifier_proto_rawDesc), len(file_services_token_verifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_token_verifier_proto_goTypes,
		DependencyIndexes: file_services_token_verifier_proto_depIdxs,
		MessageInfos:      file_services_token_verifier_proto_msgTypes,
	}.Build()
	File_services_token_verifier_proto = out.File
	file_services_token_verifier_proto_goTypes = nil
	file_services_token_verifier_proto_depIdxs = nil
}
