// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: services/token_issuer.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenIssuerService_IssueToken_FullMethodName = "/services.TokenIssuerService/IssueToken"
)

// TokenIssuerServiceClient is the client API for TokenIssuerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TokenIssuerService handles Token issuance operations
type TokenIssuerServiceClient interface {
	// Issue a signed JWT
	IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error)
}

type tokenIssuerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenIssuerServiceClient(cc grpc.ClientConnInterface) TokenIssuerServiceClient {
	return &tokenIssuerServiceClient{cc}
}

func (c *tokenIssuerServiceClient) IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueTokenResponse)
	err := c.cc.Invoke(ctx, TokenIssuerService_IssueToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenIssuerServiceServer is the server API for TokenIssuerService service.
// All implementations must embed UnimplementedTokenIssuerServiceServer
// for forward compatibility.
//
// TokenIssuerService handles Token issuance operations
type TokenIssuerServiceServer interface {
	// Issue a signed JWT
	IssueToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error)
	mustEmbedUnimplementedTokenIssuerServiceServer()
}

// UnimplementedTokenIssuerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenIssuerServiceServer struct{}

func (UnimplementedTokenIssuerServiceServer) IssueToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueToken not implemented")
}
func (UnimplementedTokenIssuerServiceServer) mustEmbedUnimplementedTokenIssuerServiceServer() {}
func (UnimplementedTokenIssuerServiceServer) testEmbeddedByValue()                            {}

// UnsafeTokenIssuerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenIssuerServiceServer will
// result in compilation errors.
type UnsafeTokenIssuerServiceServer interface {
	mustEmbedUnimplementedTokenIssuerServiceServer()
}

func RegisterTokenIssuerServiceServer(s grpc.ServiceRegistrar, srv TokenIssuerServiceServer) {
	// If the following call panics, it indicates UnimplementedTokenIssuerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenIssuerService_ServiceDesc, srv)
}

func _TokenIssuerService_IssueToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenIssuerServiceServer).IssueToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenIssuerService_IssueToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenIssuerServiceServer).IssueToken(ctx, req.(*IssueTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenIssuerService_ServiceDesc is the grpc.ServiceDesc for TokenIssuerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenIssuerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.TokenIssuerService",
	HandlerType: (*TokenIssuerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueToken",
			Handler:    _TokenIssuerService_IssueToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/token_issuer.proto",
}
