// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: services/token_verifier.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenVerifierService_DecodeToken_FullMethodName = "/services.TokenVerifierService/DecodeToken"
)

// TokenVerifierServiceClient is the client API for TokenVerifierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TokenVerifierService handles token verification operations
type TokenVerifierServiceClient interface {
	// Decode and validate JWT, returning claims
	DecodeToken(ctx context.Context, in *DecodeTokenRequest, opts ...grpc.CallOption) (*DecodeTokenResponse, error)
}

type tokenVerifierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenVerifierServiceClient(cc grpc.ClientConnInterface) TokenVerifierServiceClient {
	return &tokenVerifierServiceClient{cc}
}

func (c *tokenVerifierServiceClient) DecodeToken(ctx context.Context, in *DecodeTokenRequest, opts ...grpc.CallOption) (*DecodeTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecodeTokenResponse)
	err := c.cc.Invoke(ctx, TokenVerifierService_DecodeToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenVerifierServiceServer is the server API for TokenVerifierService service.
// All implementations must embed UnimplementedTokenVerifierServiceServer
// for forward compatibility.
//
// TokenVerifierService handles token verification operations
type TokenVerifierServiceServer interface {
	// Decode and validate JWT, returning claims
	DecodeToken(context.Context, *DecodeTokenRequest) (*DecodeTokenResponse, error)
	mustEmbedUnimplementedTokenVerifierServiceServer()
}

// UnimplementedTokenVerifierServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenVerifierServiceServer struct{}

func (UnimplementedTokenVerifierServiceServer) DecodeToken(context.Context, *DecodeTokenRequest) (*DecodeTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecodeToken not implemented")
}
func (UnimplementedTokenVerifierServiceServer) mustEmbedUnimplementedTokenVerifierServiceServer() {}
func (UnimplementedTokenVerifierServiceServer) testEmbeddedByValue()                              {}

// UnsafeTokenVerifierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenVerifierServiceServer will
// result in compilation errors.
type UnsafeTokenVerifierServiceServer interface {
	mustEmbedUnimplementedTokenVerifierServiceServer()
}

func RegisterTokenVerifierServiceServer(s grpc.ServiceRegistrar, srv TokenVerifierServiceServer) {
	// If the following call panics, it indicates UnimplementedTokenVerifierServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenVerifierService_ServiceDesc, srv)
}

func _TokenVerifierService_DecodeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenVerifierServiceServer).DecodeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenVerifierService_DecodeToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenVerifierServiceServer).DecodeToken(ctx, req.(*DecodeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenVerifierService_ServiceDesc is the grpc.ServiceDesc for TokenVerifierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenVerifierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.TokenVerifierService",
	HandlerType: (*TokenVerifierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DecodeToken",
			Handler:    _TokenVerifierService_DecodeToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/token_verifier.proto",
}
