// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: services/webauthn.proto

package services

import (
	webauthn "github.com/authaas/api/webauthn"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_webauthn_proto protoreflect.FileDescriptor

const file_services_webauthn_proto_rawDesc = "" +
	"\n" +
	"\x17services/webauthn.proto\x12\bservices\x1a\x14webauthn/login.proto\x1a\x17webauthn/register.proto2\x96\x01\n" +
	"\x0fWebAuthnService\x12E\n" +
	"\bRegister\x12\x19.webauthn.RegisterRequest\x1a\x1a.webauthn.RegisterResponse(\x010\x01\x12<\n" +
	"\x05Login\x12\x16.webauthn.LoginRequest\x1a\x17.webauthn.LoginResponse(\x010\x01B!Z\x1fgithub.com/authaas/api/servicesb\x06proto3"

var file_services_webauthn_proto_goTypes = []any{
	(*webauthn.RegisterRequest)(nil),  // 0: webauthn.RegisterRequest
	(*webauthn.LoginRequest)(nil),     // 1: webauthn.LoginRequest
	(*webauthn.RegisterResponse)(nil), // 2: webauthn.RegisterResponse
	(*webauthn.LoginResponse)(nil),    // 3: webauthn.LoginResponse
}
var file_services_webauthn_proto_depIdxs = []int32{
	0, // 0: services.WebAuthnService.Register:input_type -> webauthn.RegisterRequest
	1, // 1: services.WebAuthnService.Login:input_type -> webauthn.LoginRequest
	2, // 2: services.WebAuthnService.Register:output_type -> webauthn.RegisterResponse
	3, // 3: services.WebAuthnService.Login:output_type -> webauthn.LoginResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_webauthn_proto_init() }
func file_services_webauthn_proto_init() {
	if File_services_webauthn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_webauthn_proto_rawDesc), len(file_services_webauthn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_webauthn_proto_goTypes,
		DependencyIndexes: file_services_webauthn_proto_depIdxs,
	}.Build()
	File_services_webauthn_proto = out.File
	file_services_webauthn_proto_goTypes = nil
	file_services_webauthn_proto_depIdxs = nil
}
