// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: services/webauthn.proto

package services

import (
	context "context"
	webauthn "git.sonicoriginal.software/grpc-auth-api/webauthn"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebAuthnService_Register_FullMethodName = "/services.WebAuthnService/Register"
	WebAuthnService_Login_FullMethodName    = "/services.WebAuthnService/Login"
)

// WebAuthnServiceClient is the client API for WebAuthnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WebAuthnService handles WebAuthn/Passkey identity verification
type WebAuthnServiceClient interface {
	// Run the webauthn registration ceremony
	Register(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[webauthn.RegisterRequest, webauthn.RegisterResponse], error)
	// Run the webauthn login ceremony
	Login(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[webauthn.LoginRequest, webauthn.LoginResponse], error)
}

type webAuthnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebAuthnServiceClient(cc grpc.ClientConnInterface) WebAuthnServiceClient {
	return &webAuthnServiceClient{cc}
}

func (c *webAuthnServiceClient) Register(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[webauthn.RegisterRequest, webauthn.RegisterResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WebAuthnService_ServiceDesc.Streams[0], WebAuthnService_Register_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[webauthn.RegisterRequest, webauthn.RegisterResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WebAuthnService_RegisterClient = grpc.BidiStreamingClient[webauthn.RegisterRequest, webauthn.RegisterResponse]

func (c *webAuthnServiceClient) Login(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[webauthn.LoginRequest, webauthn.LoginResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WebAuthnService_ServiceDesc.Streams[1], WebAuthnService_Login_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[webauthn.LoginRequest, webauthn.LoginResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WebAuthnService_LoginClient = grpc.BidiStreamingClient[webauthn.LoginRequest, webauthn.LoginResponse]

// WebAuthnServiceServer is the server API for WebAuthnService service.
// All implementations must embed UnimplementedWebAuthnServiceServer
// for forward compatibility.
//
// WebAuthnService handles WebAuthn/Passkey identity verification
type WebAuthnServiceServer interface {
	// Run the webauthn registration ceremony
	Register(grpc.BidiStreamingServer[webauthn.RegisterRequest, webauthn.RegisterResponse]) error
	// Run the webauthn login ceremony
	Login(grpc.BidiStreamingServer[webauthn.LoginRequest, webauthn.LoginResponse]) error
	mustEmbedUnimplementedWebAuthnServiceServer()
}

// UnimplementedWebAuthnServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebAuthnServiceServer struct{}

func (UnimplementedWebAuthnServiceServer) Register(grpc.BidiStreamingServer[webauthn.RegisterRequest, webauthn.RegisterResponse]) error {
	return status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedWebAuthnServiceServer) Login(grpc.BidiStreamingServer[webauthn.LoginRequest, webauthn.LoginResponse]) error {
	return status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedWebAuthnServiceServer) mustEmbedUnimplementedWebAuthnServiceServer() {}
func (UnimplementedWebAuthnServiceServer) testEmbeddedByValue()                         {}

// UnsafeWebAuthnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebAuthnServiceServer will
// result in compilation errors.
type UnsafeWebAuthnServiceServer interface {
	mustEmbedUnimplementedWebAuthnServiceServer()
}

func RegisterWebAuthnServiceServer(s grpc.ServiceRegistrar, srv WebAuthnServiceServer) {
	// If the following call panics, it indicates UnimplementedWebAuthnServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebAuthnService_ServiceDesc, srv)
}

func _WebAuthnService_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WebAuthnServiceServer).Register(&grpc.GenericServerStream[webauthn.RegisterRequest, webauthn.RegisterResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WebAuthnService_RegisterServer = grpc.BidiStreamingServer[webauthn.RegisterRequest, webauthn.RegisterResponse]

func _WebAuthnService_Login_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WebAuthnServiceServer).Login(&grpc.GenericServerStream[webauthn.LoginRequest, webauthn.LoginResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WebAuthnService_LoginServer = grpc.BidiStreamingServer[webauthn.LoginRequest, webauthn.LoginResponse]

// WebAuthnService_ServiceDesc is the grpc.ServiceDesc for WebAuthnService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebAuthnService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.WebAuthnService",
	HandlerType: (*WebAuthnServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _WebAuthnService_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Login",
			Handler:       _WebAuthnService_Login_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "services/webauthn.proto",
}
