syntax = "proto3";

package services;

import "identity/principal.proto";

option go_package = "git.sonicoriginal.software/grpc-auth-api/services";

// PrincipalService handles principal management operations
service PrincipalService {
  // Create a new principal
  rpc CreatePrincipal(CreatePrincipalRequest) returns (CreatePrincipalResponse);

  // Delete principal
  rpc DeletePrincipal(DeletePrincipalRequest) returns (DeletePrincipalResponse);
}

// Create new principal
message CreatePrincipalRequest {}

message CreatePrincipalResponse {
  identity.Principal principal = 1;
}

// Delete principal
message DeletePrincipalRequest {
  identity.Principal principal = 1;
}

message DeletePrincipalResponse {}
